<div class="header">
    <?= _t('Hi', 'system') ?>,
    <?= ($user->id ? '<b>' . $user->name . '</b>!' : _t('Guest', 'system') . '!') ?>
</div>
<div class="tmn">
    <?php if (isset($homeButton)): ?>
        <a href="<?= $config->homeurl ?>">
            <img src="<?= $config->homeurl ?>/themes/default/assets/images/old_menu_home.png" class="icon"><?= _t('Home', 'system') ?>
        </a>
        <br>
    <?php endif ?>
    <?php if ($user->isValid()): ?>
        <a href="<?= $config->homeurl ?>/profile/?act=office">
            <img src="<?= $config->homeurl ?>/themes/default/assets/images/old_menu_cabinet.png" class="icon">
            <?= _t('Personal', 'system') ?>
        </a>
    <?php else: ?>
        <a href="<?= $config->homeurl ?>/login/">
            <img src="<?= $config->homeurl ?>/themes/default/assets/images/old_menu_login.png" class="icon"><?= _t('Login', 'system') ?>
        </a>
    <?php endif ?>
</div>
