<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

use Johncms\NavChain;

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $title
 * @var string $message
 */

$nav_chain = di(NavChain::class);
$nav_chain->showHomePage(false);

$this->layout('system::layout/guest', ['title' => $title]);
?>
<div class="min-vh-100 d-flex align-items-center">
    <div class="card w-100 mx-auto py-4" style="max-width: 500px;">
        <div class="card-body text-center">
            <div class="text-center mb-3">
                <img src="<?= $this->asset('images/logo.svg') ?>" alt="logo" style="max-width: 200px;" class="img-fluid">
            </div>
            <div class="fw-bold h2"><?= $this->e($title) ?></div>
            <?php if (! empty($message)): ?>
                <p class="h4 text-muted"><?= $this->e($message) ?></p>
            <?php endif; ?>
            <a href="/" class="btn btn-primary mt-3"><?= __('Home') ?></a>
        </div>
    </div>
</div>
