<?php $this->layout('system::layout/old_default', ['title' => __('Redirect to an external link')]) ?>

<div class="phdr">
    <strong><?= __('External Link') ?></strong>
</div>
<div class="rmenu" style="padding-top: 16px; padding-bottom: 16px">
    <form action="?url=<?= $redirect_url ?>" method="post">
        <h3><?= __('ATTENTION!') ?></h3>
        <p>
            <?= __('You are going to leave our site and go to an external link') ?>:
            <span class="red"><?= htmlspecialchars($url) ?></span>
        </p>
        <p>
            <?= __('Administration of our site is not responsible for the content of external sites') ?><br>
            <?= sprintf(__('It is recommended not to specify your data, relating to %s (Login, Password), on third party sites'),
                '<strong>' . parse_url($config['homeurl'], PHP_URL_HOST) . '</strong>') ?>
        </p>
        <br><input type="submit" name="submit" value="<?= __('Go to Link') ?>"/>
    </form>
</div>
<div class="phdr">
    <a href="<?= $referer ?>"><?= __('Back') ?></a>
</div>
