<?php
/**
 * @var array $notifications
 * @var array $breadcrumbs
 */

$this->layout(
    'system::layout/default',
    [
        'title'       => __('Notifications'),
        'page_title'  => __('Notifications'),
        'breadcrumbs' => $breadcrumbs,
    ]
);
?>

<?php if (empty($notifications)): ?>
    <div class="alert alert-success shadow border-radius-12">
        <?= __('All notifications have already been read') ?>
    </div>
<?php else: ?>
    <div class="row">
        <div class="col-md-6">
            <div class="small-full-width list-items shadow mb-4 overflow-hidden">
                <?php foreach ($notifications as $notification): ?>
                    <a href="<?= $notification['url'] ?>" class="list-item d-flex">
                        <div class="flex-grow-1 item-content">
                            <div class="item-name"><?= $notification['name'] ?></div>
                            <?php if (! empty($notification['description'])): ?>
                                <div class="item-desc"><?= $notification['description'] ?></div>
                            <?php endif; ?>
                        </div>
                        <?php if (! empty($notification['counter'])): ?>
                            <div class="icon-right d-flex align-items-center pr-0">
                                <div class="badge badge-danger badge-pill"><?= $notification['counter'] ?></div>
                            </div>
                        <?php endif; ?>
                        <div class="icon-right">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-right"/>
                            </svg>
                        </div>
                    </a>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>


