<?php
/**
 * @var array $notifications
 */

$this->layout('system::layout/default', ['title' => _t('Notifications')])
?>
<h1 class="mb-0"><?= _t('Notifications') ?></h1>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/"><?= _t('Home page') ?></a></li>
        <li class="breadcrumb-item active" aria-current="page"><?= _t('Notifications') ?></li>
    </ol>
</nav>

<?php if(empty($notifications)):?>
    <div class="alert alert-success shadow border-radius-12">
        <?= _t('All notifications have already been read') ?>
    </div>
<?php else: ?>
    <div class="small-full-width list-items shadow mb-4 border-radius-12 overflow-hidden">
        <?php foreach ($notifications as $notification): ?>
            <a href="<?= $notification['url'] ?>" class="list-item d-flex">
                <div class="flex-grow-1 item-content">
                    <div class="item-name"><?= $notification['name'] ?></div>
                    <?php if(!empty($notification['description'])): ?>
                        <div class="item-desc"><?= $notification['description'] ?></div>
                    <?php endif; ?>
                </div>
                <?php if(!empty($notification['counter'])): ?>
                    <div class="icon-right d-flex align-items-center pr-0">
                        <div class="badge badge-danger badge-pill"><?= $notification['counter'] ?></div>
                    </div>
                <?php endif; ?>
                <div class="icon-right">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-right"/>
                    </svg>
                </div>
            </a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>


