<?php $this->layout('system::layout/old_default', ['title' => _t('List of users'), 'homeButton' => true]) ?>
<div class="phdr"><a href="./"><strong><?= _t('Community') ?></strong></a> | <?= _t('List of users') ?></div>
<!-- List of Users -->
<div class="list-striped">
    <?php foreach ($list() as $usr): ?>
        <div><?= $tools->displayUser($usr) ?></div>
    <?php endforeach ?>
</div>
<div class="phdr"><?= _t('Total') . ': ' . $total ?></div>
<!-- Pagination -->
<?php if ($total > $user->config->kmess): ?>
    <div class="topmenu"><?= $pagination ?></div>
<?php endif ?>
<p>
    <!-- Misc links -->
    <a href="search.php"><?= _t('User Search') ?></a><br/>
    <a href="./"><?= _t('Back') ?></a>
</p>
