<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['sec_menu' => ['ipban' => true]]));
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= $data['message'] ?>
    </div>
    <div>
        <a href="<?= $data['confirm_url'] ?>" class="btn btn-danger"><?= $data['confirm_url_name'] ?></a>
        <a href="<?= $data['back_url'] ?>" class="btn btn-primary"><?= $data['back_url_name'] ?></a>
    </div>
</div>
