<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['usr_menu' => ['usr_clean' => true]]));
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('This category includes profiles, recorded more than 6 months ago, with the date of last visit for more than 5 months ago and with zero activity.<br>Can safely remove them.') ?>
        <div>
            <?= __('Total') ?>: <b><?= $data['total'] ?></b>
        </div>
    </div>
    <div>
        <form action="<?= $data['form_action'] ?>" method="post">
            <button type="submit" name="submit" value="1" class="btn btn-danger"><?= __('Delete') ?></button>
            <a href="<?= $data['back_url'] ?>" class="btn btn-outline-secondary"><?= __('Cancel') ?></a>
        </form>
    </div>
</div>
