<?php
/**
 * @var Johncms\Utility\Counters   $counters
 * @var Johncms\Utility\NewsWidget $news
 * @var int                        $rights
 */

$this->layout('system::layout/default', ['title' => _t('Welcome', 'system')])
?>


<div class="jumbotron shadow pt-4 pb-5 bg-white mt-3 border-radius-12">
    <h1 class="display-4 font-weight-bold">JohnCMS</h1>
    <p class="lead">
        Бесплатная система управления контентом c открытым исходным кодом
    </p>
    <hr class="my-4">
    <p>
        Актуальная версия JohnCMS 9.0.0
    </p>
    <a class="btn btn-primary btn-lg mr-1" href="https://johncms.com/downloads/">Загрузить</a>
    <a class="btn btn-primary btn-lg mr-1" href="https://johncms.com/documentation/">Документация</a>
    <a href="https://github.com/simba77/johncms" class="btn btn-primary btn-lg-icon">
        <svg class="icon">
            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#github"/>
        </svg>
    </a>
</div>


<div class="card shadow border-radius-12 border-0">
    <div class="card-body">
        <h5 class="card-title h1 font-weight-bold">Особенности</h5>

        <div class="pt-2">
            <div class="border-bottom">
                <h3 class="mt-0 font-weight-bold">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                    </svg>
                    Адаптивная верстка
                </h3>
                <p>
                    Ваш сайт будет отображаться одинаково хорошо как на компьютерах, так и на мобильных устройствах
                </p>
            </div>
        </div>
        <div class="pt-2">
            <div class="border-bottom">
                <h3 class="mt-0 font-weight-bold">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                    </svg>
                    Шаблонная система
                </h3>
                <p>
                    Благодаря поддержке шаблонов, Вы можете полностью изменить стиль Вашего сайта так, чтобы он стал уникальным и не похожим на другие
                </p>
            </div>
        </div>
        <div class="pt-2">
            <div class="border-bottom">
                <h3 class="mt-0 font-weight-bold">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                    </svg>
                    Высокая производительность
                </h3>
                <p>
                    При разработке JohnCMS мы уделяем особое внимание производительности системы.<br>
                    Ваш сайт не будет требовать мощного сервера на столько долго, на сколько это возможно
                </p>
            </div>
        </div>
        <div class="pt-2">
            <div class="border-bottom">
                <h3 class="mt-0 font-weight-bold">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                    </svg>
                    Мультиязычность
                </h3>
                <p>
                    Охватывайте максимальную аудиторию благодаря мультиязычности. В систему уже встроено несколько языков.<br>
                    А если нужного языка нет, Вы сможете легко его добавить, благодаря продвинутым инструментам для перевода, которые поддерживают работу с JohnCMS
                </p>
            </div>
        </div>
        <div class="pt-2">
            <div>
                <h3 class="mt-0 font-weight-bold">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                    </svg>
                    Модульность
                </h3>
                <p>
                    В систему встроены основные наиболее популярные модули.<br>
                    Благодаря модульной системе Вы сможете устанавливать уже готовые дополнительные модули, создавать самостоятельно или же заказывать разработку новых модулей у других разработчиков.
                </p>
            </div>
        </div>

    </div>
</div>
