#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Johncms\Application;
use Johncms\Console\ConsoleApp;
use Johncms\Container\ContainerFactory;

$container = ContainerFactory::getContainer();
$container->get(Application::class)->run();

$application = new ConsoleApp();
try {
    $application->run();
} catch (Exception $e) {
    exit($e->getMessage());
}
