<?php $this->layout('system::layout/default', [
    'title'      => __('Delete message'),
    'page_title' => __('Delete message'),
]) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-8">
        <div class="card shadow border-0 border-radius-12">
            <div class="card-body">
                <h4 class="card-title"><?= __('Do you really want to delete?') ?></h4>
                <a href="/guestbook/delpost?id=<?= $id ?>&amp;yes" class="btn btn-danger"><?= __('Delete') ?></a>
                <a href="/guestbook/" class="btn btn-link"><?= __('Cancel') ?></a>
            </div>
        </div>
    </div>
</div>
