<form action="/guestbook/delpost" method="post">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
    <input type="hidden" name="id" value="<?= $id ?>">
    <div class="modal-header align-items-center">
        <h4 class="modal-title">
            <?= __('Delete message') ?>
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span class="icon">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <h4 class="alert alert-danger"><?= __('Do you really want to delete?') ?></h4>
    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-primary"><?= __('Delete') ?></button>
        <button type="button" data-dismiss="modal" aria-label="Close" class="btn btn-outline-primary ml-2"><?= __('Cancel') ?></button>
    </div>
</form>
