<?php $this->layout('system::layout/default') ?>
<?php if ($data['is_closed']): ?>
    <!-- Уведомление о закрытой гостевой -->
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-danger',
            'alert'      => __('The guestbook is closed'),
        ]
    ) ?>
<?php endif; ?>
<?php if (! empty($data['message'])): ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-success',
            'alert'      => $data['message'],
        ]
    ) ?>
<?php endif; ?>
<?php if ($data['can_write']): ?>
    <div class="row">
        <div class="col-12">
            <?php if (! empty($data['errors']['csrf_token'])): ?>
                <div class="alert alert-danger"><?= implode(', ', $data['errors']['csrf_token']) ?></div>
            <?php endif ?>
            <form name="form" action="/guestbook/" method="post">
                <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>"/>
                <?php if (! $user->isValid()): ?>
                    <div class="form-group">
                        <label for="name"><?= __('Name') ?></label>
                        <input type="text"
                               class="form-control <?= ! empty($data['errors']['name']) ? 'is-invalid' : '' ?>"
                               maxlength="25"
                               name="name"
                               id="name"
                               required
                               value="<?= $this->e($data['form_data']['name']) ?>"
                               placeholder="<?= __('Name') ?>"
                        >
                        <?php if (! empty($data['errors']['name'])): ?>
                            <div class="invalid-feedback d-block"><?= implode(', ', $data['errors']['name']) ?></div>
                        <?php endif ?>
                    </div>
                <?php endif; ?>
                <div class="form-group">
                    <label for="message"><?= __('Message') ?></label>
                    <textarea name="message" id="message" class="form-control <?= ! empty($data['errors']['message']) ? 'is-invalid' : '' ?>"><?= $this->e($data['form_data']['message']) ?></textarea>
                    <?php if (! empty($data['errors']['message'])): ?>
                        <div class="invalid-feedback d-block"><?= implode(', ', $data['errors']['message']) ?></div>
                    <?php endif ?>
                </div>

                <?php if (! $user->isValid()): ?>
                    <img alt="<?= __('Verification code') ?>" src="<?= $data['captcha'] ?>">
                    <div class="form-group">
                        <label for="code"><?= __('Symbols on the picture') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($data['errors']['code']) ? 'is-invalid' : '') ?>"
                               maxlength="6"
                               name="code"
                               id="code"
                               autocomplete="off"
                               required
                               placeholder="<?= __('Symbols on the picture') ?>"
                        >
                        <?php if (isset($data['errors']['code'])): ?>
                            <div class="invalid-feedback"><?= implode(', ', $data['errors']['code']) ?></div>
                        <?php endif ?>
                        <div class="text-muted small">
                            <?= __('If you cannot see the image code, enable graphics in your browser and refresh this page') ?>
                        </div>
                    </div>
                <?php endif; ?>

                <input type="submit" class="btn btn-primary" name="submit" value="<?= __('Write') ?>"/>
            </form>
        </div>
    </div>
<?php else: ?>
    <!-- Гостевая только для зарегистрированных -->
    <?php if (! $user->isValid()): ?>
        <?= $this->fetch(
            'system::app/alert',
            [
                'alert_type' => 'alert-danger',
                'alert'      => __('For registered users only'),
            ]
        ) ?>
    <?php endif; ?>
<?php endif; ?>
<div class="mt-4 border-bottom full-mobile-width"></div>
<!-- Отображаем сообщения -->
<?php if (empty($data['posts'])): ?>
    <div class="alert alert-info"><?= __('The guestbook is empty.<br><strong>Be the first! :)</strong>') ?></div>
<?php else: ?>
    <?php foreach ($data['posts']['data'] as $post): ?>
        <div class="new_post-item">
            <div class="new_post-header d-flex justify-content-between">
                <div class="post-user">
                    <?php if (! empty($post['user']) && ! empty($post['user']['profile_url'])): ?>
                        <a href="<?= $post['user']['profile_url'] ?>">
                            <div class="avatar">
                                <img src="<?= $this->avatar($post['user']['id'] ?? 0) ?>" class="img-fluid" alt=".">
                            </div>
                        </a>
                    <?php else: ?>
                        <div class="avatar">
                            <img src="<?= $this->avatar($post['user']['id'] ?? 0) ?>" class="img-fluid" alt=".">
                        </div>
                    <?php endif; ?>
                    <span class="user-status <?= $post['is_online'] ? 'online' : 'offline' ?> shadow"></span>
                    <?php if (! empty($post['user']['rights_name'])): ?>
                        <div class="post-of-user"
                             data-toggle="tooltip"
                             data-placement="top"
                             data-html="true"
                             title="<?= $post['user']['rights_name'] ?>">
                            <svg class="icon-post">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>?4#check"/>
                            </svg>
                        </div>
                    <?php endif ?>
                </div>
                <div class="flex-grow-1 post-user d-flex flex-wrap overflow-hidden d-flex align-items-center">
                    <div class="w-100">
                        <?php if (! empty($post['user']) && ! empty($post['user']['profile_url'])): ?>
                            <a href="<?= $post['user']['profile_url'] ?>">
                                <div class="user-name d-inline mr-2"><?= $post['name'] ?></div>
                            </a>
                        <?php else: ?>
                            <div class="user-name d-inline mr-2"><?= ! empty($post['user']) ? $post['name'] : (__('Guest') . ': ' . $post['name']) ?></div>
                        <?php endif; ?>
                        <span class="post-meta d-inline mr-2"><?= $post['created_at'] ?></span>
                        <?php if (! empty($post['edit_count'])): ?>
                            <div class="post-meta d-inline mr-2"
                                 data-toggle="tooltip"
                                 data-placement="top"
                                 data-html="true"
                                 title="<?= __('Edited:') ?> <?= $post['edited_by'] ?> <br> (<?= $post['edited_at'] ?>) [<?= $post['edit_count'] ?>]">
                                <?= __('Edited') ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php if (! empty($post['user']) && ! empty($post['user']['status'])): ?>
                        <div class="overflow-hidden text-nowrap text-dark-brown overflow-ellipsis small">
                            <span class="font-weight-bold"><?= $post['user']['status'] ?></span>
                        </div>
                    <?php endif ?>
                </div>
            </div>
            <div class="post-body last-p-no-margin pt-2">
                <?= $post['text'] ?>
                <?php if (! empty($post['reply_text'])): ?>
                    <div class="alert alert-warning mt-2 mb-n2">
                        <b><?= $post['reply_author'] ?></b> <?= $post['replied_at'] ?><br>
                        <?= $post['reply_text'] ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="post-footer d-flex justify-content-between mt-2">
                <div class="overflow-hidden">
                    <?php if ($post['meta']): ?>
                        <div class="post-meta d-flex">
                            <div class="user-ip mr-2">
                                <a href="<?= $post['meta']['search_ip_url'] ?>"><?= $post['meta']['ip'] ?></a>
                            </div>
                            <div class="useragent">
                                <span><?= $post['meta']['user_agent'] ?></span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="d-flex">
                    <?php if ($data['can_write'] && $post['user_id'] !== $user->id): ?>
                        <div class="ml-3">
                            <a href="#" onclick="reply_to_post('<?= $post['name'] ?>')"><?= __('Reply') ?></a>
                        </div>
                    <?php endif; ?>
                    <?php if (! empty($post['meta']['can_manage'])): ?>
                        <div class="dropdown ml-3">
                            <div class="cursor-pointer" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <svg class="icon text-primary">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>?1#more_horizontal"/>
                                </svg>
                            </div>
                            <div class="dropdown-menu dropdown-menu-right">
                                <?php if ($post['meta']['reply_url']): ?>
                                    <a href="<?= $post['meta']['reply_url'] ?>" class="dropdown-item"><?= __('Reply') ?></a>
                                <?php endif; ?>
                                <a href="<?= $post['meta']['edit_url'] ?>" class="dropdown-item"><?= __('Edit') ?></a>
                                <a href="<?= $post['meta']['delete_url'] ?>" class="dropdown-item"><?= __('Delete') ?></a>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

    <?php if (! empty($data['pagination'])): ?>
        <div class="mt-4"><?= $data['pagination'] ?></div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($data['can_clear']): ?>
    <div class="d-flex mt-4 pb-2">
        <button type="button" class="btn btn-danger" data-url="/guestbook/clean" data-toggle="modal" data-target=".ajax_modal"><?= __('Clear') ?></button>
    </div>
<?php endif ?>
<?php $this->push('scripts') ?>
<?php
if ($locale !== 'en') {
    try {
        echo '<script src="' . $this->asset('ckeditor5/translations/' . $locale . '.js') . '"></script>';
    } catch (Exception $exception) {
    }
}
?>
<script src="<?= $this->asset('ckeditor5/ckeditor.js') ?>"></script>
<script>
    // Disable prism
    //Prism.manual = true;
    var ckeditor_settings = {
        ckfinder: {
            uploadUrl: '/modules/blog/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files&responseType=json'
        },
        toolbar: {
            items: [
                'heading',
                '|',
                'bold',
                'italic',
                'link',
                'fontColor',
                'bulletedList',
                'numberedList',
                'removeFormat',
                '|',
                'alignment',
                'indent',
                'outdent',
                '|',
                'codeBlock',
                'blockQuote',
                'insertTable',
                'undo',
                'redo'
            ]
        },
        language: '<?= $locale ?>',
        table: {
            contentToolbar: [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties'
            ]
        },
        codeBlock: {
            languages: [
                {language: 'php', label: 'PHP', class: 'language-php line-numbers'},
                {language: 'css', label: 'CSS', class: 'language-css line-numbers'},
                {language: 'javascript', label: 'JavaScript', class: 'language-javascript line-numbers'},
                {language: 'html', label: 'HTML', class: 'language-html line-numbers'},
                {language: 'sql', label: 'SQL', class: 'language-sql line-numbers'},
                {language: 'xml', label: 'XML', class: 'language-xml line-numbers'},
            ]
        },
        heading: {
            options: [
                {model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph'},
                {model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1'},
                {model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2'},
                {
                    model: 'alertSuccess',
                    view: {
                        name: 'div',
                        classes: ['alert', 'alert-success']
                    },
                    title: 'alert-success',
                    class: 'alert alert-success',
                },
                {
                    model: 'alertInfo',
                    view: {
                        name: 'div',
                        classes: ['alert', 'alert-info']
                    },
                    title: 'alert-info',
                    class: 'alert alert-success',
                },
                {
                    model: 'alertDanger',
                    view: {
                        name: 'div',
                        classes: ['alert', 'alert-danger']
                    },
                    title: 'alert-danger',
                    class: 'alert alert-danger',
                },
                {
                    model: 'alertWarning',
                    view: {
                        name: 'div',
                        classes: ['alert', 'alert-warning']
                    },
                    title: 'alert-warning',
                    class: 'alert alert-warning',
                }
            ]
        },
        licenseKey: '',
    };

    ClassicEditor
        .create(document.querySelector('#message'), ckeditor_settings)
        .then(editor => {
            window.editor = editor;
        })
        .catch(error => {
            console.error(error);
        });

</script>
<script>
    function reply_to_post(user_name)
    {
        event.preventDefault();
        $('body,html').animate({scrollTop: 100}, 500);
        editor.editing.view.focus();
        editor.model.change(writer => {
            const insertPosition = editor.model.document.selection.getFirstPosition();
            writer.insertText(user_name + ', ', {}, insertPosition);
            writer.setSelection(writer.createPositionAt(editor.model.document.getRoot(), 'end'));
        });
    }
</script>
<?php $this->stop(); ?>
