<?php
/**
 * @var \Johncms\Modules\Guestbook\Application\DTO\GuestbookEntryDTO[] $posts
 * @var $pagination string
 */

$this->layout('system::layout/default') ?>
<?php if ($data['is_closed']): ?>
    <!-- Уведомление о закрытой гостевой -->
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-danger',
            'alert'      => __('The guestbook is closed'),
        ]
    ) ?>
<?php endif; ?>
<?php if (! empty($data['message'])): ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-success',
            'alert'      => $data['message'],
        ]
    ) ?>
<?php endif; ?>
<?php if ($data['can_write']): ?>
    <div class="row">
        <div class="col-12">
            <?php if (! empty($data['errors']['csrf_token'])): ?>
                <div class="alert alert-danger"><?= implode(', ', $data['errors']['csrf_token']) ?></div>
            <?php endif ?>
            <form name="form" action="/guestbook/" method="post">
                <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>"/>
                <?php if (! $user->isValid()): ?>
                    <div class="form-group">
                        <label for="name"><?= __('Name') ?></label>
                        <input type="text"
                               class="form-control <?= ! empty($data['errors']['name']) ? 'is-invalid' : '' ?>"
                               maxlength="25"
                               name="name"
                               id="name"
                               required
                               value="<?= $this->e($data['form_data']['name']) ?>"
                               placeholder="<?= __('Name') ?>"
                        >
                        <?php if (! empty($data['errors']['name'])): ?>
                            <div class="invalid-feedback d-block"><?= implode(', ', $data['errors']['name']) ?></div>
                        <?php endif ?>
                    </div>
                <?php endif; ?>
                <?= $this->fetch(
                    'guestbook::ckeditor',
                    [
                        'label'  => __('Message'),
                        'errors' => implode(', ', $data['errors']['message'] ?? []),
                        'value'  => $this->e($data['form_data']['message']),
                    ]
                ) ?>

                <?php if (! $user->isValid()): ?>
                    <img alt="<?= __('Verification code') ?>" src="<?= $data['captcha'] ?>">
                    <div class="form-group">
                        <label for="code"><?= __('Symbols on the picture') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($data['errors']['code']) ? 'is-invalid' : '') ?>"
                               maxlength="6"
                               name="code"
                               id="code"
                               autocomplete="off"
                               required
                               placeholder="<?= __('Symbols on the picture') ?>"
                        >
                        <?php if (isset($data['errors']['code'])): ?>
                            <div class="invalid-feedback"><?= implode(', ', $data['errors']['code']) ?></div>
                        <?php endif ?>
                        <div class="text-muted small">
                            <?= __('If you cannot see the image code, enable graphics in your browser and refresh this page') ?>
                        </div>
                    </div>
                <?php endif; ?>

                <input type="submit" class="btn btn-primary" name="submit" value="<?= __('Write') ?>"/>
            </form>
        </div>
    </div>
<?php else: ?>
    <!-- Гостевая только для зарегистрированных -->
    <?php if (! $user->isValid()): ?>
        <?= $this->fetch(
            'system::app/alert',
            [
                'alert_type' => 'alert-danger',
                'alert'      => __('For registered users only'),
            ]
        ) ?>
    <?php endif; ?>
<?php endif; ?>
<div class="mt-4 border-bottom full-mobile-width"></div>
<!-- Отображаем сообщения -->
<?php if (empty($posts)): ?>
    <div class="alert alert-info mt-3"><?= __('The guestbook is empty.<br><strong>Be the first! :)</strong>') ?></div>
<?php else: ?>
    <?php foreach ($posts as $post): ?>
        <div class="new_post-item">
            <div class="new_post-header d-flex justify-content-between">
                <div class="post-user">
                    <?php if ($post->user?->profileUrl): ?>
                        <a href="<?= $post->user->profileUrl ?>">
                            <div class="avatar">
                                <img src="<?= $this->avatar($post->user->id ?? 0) ?>" class="img-fluid" alt=".">
                            </div>
                        </a>
                    <?php else: ?>
                        <div class="avatar">
                            <img src="<?= $this->avatar($post->user->id ?? 0) ?>" class="img-fluid" alt=".">
                        </div>
                    <?php endif; ?>
                    <span class="user-status <?= $post->isOnline ? 'online' : 'offline' ?> shadow"></span>
                    <?php if (! empty($post->user?->rightsName)): ?>
                        <div class="post-of-user"
                             data-bs-toggle="tooltip"
                             data-bs-placement="top"
                             data-bs-html="true"
                             data-bs-title="<?= $post->user->rightsName ?>">
                            <svg class="icon-post">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>?4#check"/>
                            </svg>
                        </div>
                    <?php endif ?>
                </div>
                <div class="flex-grow-1 post-user d-flex flex-wrap overflow-hidden d-flex align-items-center">
                    <div class="w-100">
                        <?php if ($post->user?->profileUrl): ?>
                            <a href="<?= $post->user->profileUrl ?>">
                                <div class="user-name d-inline me-2"><?= $post->name ?></div>
                            </a>
                        <?php else: ?>
                            <div class="user-name d-inline me-2"><?= ! empty($post->user) ? $post->name : (__('Guest') . ': ' . $post->name) ?></div>
                        <?php endif; ?>
                        <span class="post-meta d-inline me-2"><?= $post->createdAt ?></span>
                        <?php if (! empty($post->editCount)): ?>
                            <div class="post-meta d-inline me-2"
                                 data-bs-toggle="tooltip"
                                 data-bs-placement="top"
                                 data-bs-html="true"
                                 data-bs-title="<?= __('Edited:') ?> <?= $post->updatedBy ?> <br> (<?= $post->updateAt ?>) [<?= $post->editCount ?>]">
                                <?= __('Edited') ?>
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php if ($post->user?->status): ?>
                        <div class="overflow-hidden text-nowrap text-dark-brown overflow-ellipsis small">
                            <span class="fw-bold"><?= $post->user?->status ?></span>
                        </div>
                    <?php endif ?>
                </div>
            </div>
            <div class="post-body last-p-no-margin pt-2">
                <?= $post->text ?>
                <?php if (! empty($post->replyText)): ?>
                    <div class="alert alert-warning mt-2 mb-n2">
                        <b><?= $post->repliedBy ?></b> <?= $post->repliedAt ?><br>
                        <?= $post->replyText ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="post-footer d-flex justify-content-between mt-2">
                <div class="overflow-hidden">
                    <?php if ($post->meta): ?>
                        <div class="post-meta d-flex">
                            <div class="user-ip me-2">
                                <a href="<?= $post->meta->searchIpUrl ?>"><?= $post->meta->ip ?></a>
                            </div>
                            <div class="useragent">
                                <span><?= $post->meta->userAgent ?></span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="d-flex">
                    <?php if ($data['can_write'] && $post->user?->id !== $user->id): ?>
                        <div class="ms-3">
                            <a href="#" onclick="reply_to_post('<?= $post->name ?>')"><?= __('Reply') ?></a>
                        </div>
                    <?php endif; ?>
                    <?php if ($post->meta?->canManage): ?>
                        <div class="dropdown ms-3">
                            <div class="cursor-pointer" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <svg class="icon text-primary">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>?1#more_horizontal"/>
                                </svg>
                            </div>
                            <div class="dropdown-menu dropdown-menu-right">
                                <?php if ($post->meta->replyUrl): ?>
                                    <a href="<?= $post->meta->replyUrl ?>" class="dropdown-item"><?= __('Reply') ?></a>
                                <?php endif; ?>
                                <a href="<?= $post->meta->editUrl ?>" class="dropdown-item"><?= __('Edit') ?></a>
                                <a href="#" data-url="<?= $post->meta->deleteUrl ?>" data-bs-toggle="modal" data-bs-target=".ajax_modal" class="dropdown-item"><?= __('Delete') ?></a>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>

    <?php if (! empty($pagination)): ?>
        <div class="mt-4"><?= $pagination ?></div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($data['can_clear']): ?>
    <div class="d-flex mt-4 pb-2">
        <button type="button" class="btn btn-danger" data-url="/guestbook/clean" data-bs-toggle="modal" data-bs-target=".ajax_modal"><?= __('Clear') ?></button>
    </div>
<?php endif ?>
<?php $this->push('scripts') ?>
<script>
    function reply_to_post(user_name)
    {
        event.preventDefault();
        $('body,html').animate({scrollTop: 100}, 500);
        editor.editing.view.focus();
        editor.model.change(writer => {
            const insertPosition = editor.model.document.selection.getFirstPosition();
            writer.insertText(user_name + ', ', {}, insertPosition);
            writer.setSelection(writer.createPositionAt(editor.model.document.getRoot(), 'end'));
        });
    }
</script>
<?php $this->stop(); ?>
