<?php $this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $title,
    ]
) ?>
<?php if (! $config['mod_guest']): ?>
    <!-- Уведомление о закрытой гостевой -->
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-danger',
            'alert'      => __('The guestbook is closed'),
        ]
    ) ?>
<?php endif; ?>
<?php if ($data['access_to_form']): ?>
    <div class="row">
        <div class="col-md-6">
            <form name="form" action="/guestbook/say" method="post" class="mt-3 ">
                <input type="hidden" name="token" value="<?= $data['token'] ?>"/>
                <?php if (! $user->isValid()): ?>
                    <div class="form-group">
                        <label for="name"><?= __('Name') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="25"
                               name="name"
                               id="name"
                               required
                               value=""
                               placeholder="<?= __('Name') ?>"
                        >
                    </div>
                <?php endif; ?>
                <div class="form-group">
                    <label for="msg"><?= __('Message') ?></label>
                    <div>
                        <?= $data['bbcode'] ?>
                    </div>
                    <textarea rows="<?= $user->config->fieldHeight ?>" name="msg" id="msg" required class="form-control"></textarea>
                    <div class="text-muted">Max: 5000</div>
                </div>

                <?php if (! $user->isValid()): ?>
                    <img alt="<?= __('Verification code') ?>" src="<?= $data['captcha'] ?>">
                    <div class="form-group">
                        <label for="code"><?= __('Symbols on the picture') ?></label>
                        <input type="text"
                               class="form-control <?= (isset($error['captcha']) ? 'is-invalid' : '') ?>"
                               maxlength="6"
                               name="code"
                               id="code"
                               autocomplete="off"
                               required
                               placeholder="<?= __('Symbols on the picture') ?>"
                        >
                        <?php if (isset($error['captcha'])): ?>
                            <div class="invalid-feedback"><?= $error['captcha'] ?></div>
                        <?php endif ?>
                        <div class="text-muted small">
                            <?= __('If you cannot see the image code, enable graphics in your browser and refresh this page') ?>
                        </div>
                    </div>
                <?php endif; ?>

                <input type="submit" class="btn btn-primary" name="submit" value="<?= __('Send') ?>"/>
            </form>
        </div>
    </div>
<?php else: ?>
    <!-- Гостевая только для зарегистрированных -->
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-danger',
            'alert'      => __('For registered users only'),
        ]
    ) ?>
<?php endif; ?>
<div class="mt-4"></div>
<!-- Отображаем сообщения -->
<?php if (empty($data['items'])): ?>
    <div class="alert alert-info"><?= __('The guestbook is empty.<br><strong>Be the first! :)</strong>') ?></div>
<?php else: ?>
    <?php foreach ($data['items'] as $item): ?>
        <div class="shadow post-item mb-2">
            <div class="post-header d-flex justify-content-between border-bottom pb-1">
                <div class="d-flex align-items-end">
                    <?php if (! empty($item['user_id'])): ?>
                        <a href="/profile/?user=<?= $item['user_id'] ?>" class="user-login mr-2"><?= $item['name'] ?></a>
                    <?php else: ?>
                        <a class="user-login mr-2"><?= (__('Guest') . ': ' . $item['name']) ?></a>
                    <?php endif; ?>
                    <span class="post-date"><?= $item['created'] ?></span>
                </div>
                <div class="post-actions">
                    <?php if ($user->rights >= 6): ?>
                        <a href="/guestbook/otvet?id=<?= $item['message_id'] ?>" class="btn btn-sm btn-secondary"><?= __('Reply') ?></a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="post-body d-flex align-items-start pt-3 pb-3">
                <div class="user-avatar mr-2 mr-md-4">
                    <div class="avatar-image rounded-circle overflow-hidden">
                        <img src="<?= $this->avatar($item['user_id']) ?>" class="img-fluid" alt=".">
                    </div>
                    <div class="user-status online shadow"></div>
                </div>
                <div class="overflow-auto flex-grow-1"><?= $item['post_text'] ?></div>
            </div>
            <?php if (! empty($item['otvet'])): ?>
                <div class="alert alert-warning mt-2 mb-2">
                    <b><?= $item['admin'] ?></b> <?= $item['reply_time'] ?><br>
                    <?= $item['reply_text'] ?>
                </div>
            <?php endif; ?>
            <?php if ($user->rights || ! empty($item['edit_count'])): ?>
                <div class="post-footer d-flex justify-content-between border-top pt-2">
                    <div class="post-user-info d-flex overflow-hidden small align-items-center">
                        <?php if ($user->rights): ?>
                            <div class="user-ip mr-2">
                                <a href="#"><?= $item['ip'] ?></a>
                            </div>
                            <div class="useragent">
                                <span>User-Agent:</span>
                                <span><?= $item['browser'] ?></span>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="text-nowrap post-actions">
                        <span class="text-muted pr-2 flex-grow-1">
                            <?php if (! empty($item['edit_count'])): ?>
                                <?= __('Edited:') ?> <?= $item['edit_who'] ?> (<?= $item['edit_time'] ?>) [<?= $item['edit_count'] ?>]
                            <?php endif; ?>
                        </span>
                        <?php if ($user->rights >= $item['rights']): ?>
                            <a href="/guestbook/edit?id=<?= $item['message_id'] ?>" class="btn btn-light btn-sm mr-1"><?= __('Edit') ?></a>
                            <a href="/guestbook/delpost?id=<?= $item['message_id'] ?>" class="btn btn-light btn-sm"><?= __('Delete') ?></a>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>

    <?php if (! empty($data['pagination'])): ?>
        <?= $data['pagination'] ?>
    <?php endif; ?>
<?php endif; ?>
<hr class="mt-4">
<?php if ($data['access_to_buttons']): ?>
    <div class="d-flex mt-4">
        <?php if ($user->rights >= 7): ?>
            <a href="/guestbook/clean" class="btn btn-danger"><?= __('Clear') ?></a>
        <?php endif; ?>
    </div>
<?php endif ?>
