<?php $this->layout('system::layout/default', [
    'title'      => _t('Reply'),
    'page_title' => _t('Reply'),
]) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-8">
        <div class="card shadow border-0 border-radius-12">
            <div class="card-body">
                <h4 class="card-title"><?= _t('Reply') ?></h4>
                <form action="/guestbook/otvet/<?= $id ?>/" method="post">
                    <input type="hidden" name="token" value="<?= $token ?>"/>
                    <p>
                        <b><?= _t('Author') ?>:</b> <?= $message['name'] ?> <br>
                        <?= $text ?>
                    <p>
                    <div class="form-group">
                        <label for="otv"><?= _t('Reply') ?></label>
                        <div><?= $bbcode ?></div>
                        <textarea rows="<?= $user->config->fieldHeight ?>" name="otv" id="otv" required class="form-control"><?= $reply_text ?></textarea>
                        <div class="text-muted">Max: 5000</div>
                    </div>
                    <div>
                        <button type="submit" name="submit" value="submit" class="btn btn-primary mr-2"><?= _t('Save') ?></button>
                        <a href="/guestbook/" class="btn btn-outline-primary"><?= _t('Back') ?></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
