<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $form_action
 * @var string $back_url
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('Do you really want to delete?') ?>
    </div>
    <div class="d-flex">
        <form action="<?= $this->e($form_action) ?>" method="post" class="me-2">
            <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
            <button type="submit" class="btn btn-danger"><?= __('Delete') ?></button>
        </form>
        <a href="<?= $this->e($back_url) ?>" class="btn btn-outline-secondary"><?= __('Cancel') ?></a>
    </div>
</div>
