<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var int $id
 * @var array<int, array{id: int, name: string, selected: bool}> $categories
 * @var string $form_action
 * @var string $back_url
 * @var bool $can_destroy
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('<h3>WARNING!</h3>There are subsections. Move them to another category.') ?>
    </div>
</div>
<div>
    <form action="<?= $this->e($form_action) ?>" method="post">
        <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
        <div class="form-group">
            <label for="category" class="h3 mt-3"><?= __('Category') ?></label>
            <select name="category" id="category" class="form-control">
                <?php foreach ($categories as $category): ?>
                    <option value="<?= $category['id'] ?>" <?= ($category['selected'] ? ' selected="selected"' : '') ?>><?= $this->e($category['name']) ?></option>
                <?php endforeach; ?>
            </select>
            <div class="text-muted">
                <?= __('All categories, topics, and files will be moved into selected category. Old category will be removed.') ?>
            </div>
        </div>
        <button type="submit" class="btn btn-danger"><?= __('Move') ?></button>
        <a href="<?= $this->e($back_url) ?>" class="btn btn-outline-secondary"><?= __('Cancel') ?></a>
    </form>
</div>
<?php if ($can_destroy): ?>
    <div class="alert alert-info mt-3">
        <h3><?= __('Complete removal') ?></h3>
        <div>
            <?= __('If you want to destroy all the information, first remove') ?>
            <a href="/admin/forum/structure?id=<?= $id ?>"><?= __('subsections') ?></a>
        </div>
    </div>
<?php endif; ?>
