<?php

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout('system::layout/default');
?>

<form method="post" class="mb-3" action="<?= $data['storeUrl'] ?>">
    <?php if (! empty($data['success'])): ?>
        <?= $this->fetch('system::app/alert', ['alert_type' => 'alert-success', 'alert' => $data['success']]) ?>
    <?php endif ?>
    <?php if (! empty($data['errors'])): ?>
        <?= $this->fetch('system::app/alert', ['alert_type' => 'alert-danger', 'alert' => $data['errors']]) ?>
    <?php endif ?>
    <?= $this->fetch(
        'system::forms/simple_form',
        [
            'fields' => $data['formFields'],
            'errors' => $data['validationErrors'],
        ]
    ); ?>
    <button type="submit" name="submit" class="btn btn-primary"><?= __('Save') ?></button>
    <a href="<?= $data['backButton'] ?>" class="btn btn-outline-secondary"><?= __('Back') ?></a>
</form>

