<?php

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout('system::layout/default');
?>

<ul class="nav bg-light mb-4 border-radius-5">
    <li class="nav-item">
        <a class="nav-link text-danger" href="<?= route('personal.profile.edit', ['id' => 1]) ?>">Edit profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Write</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Activity</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Statistic</a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Actions</a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Delete</a></li>
            <li><a class="dropdown-item" href="#">Block</a></li>
        </ul>
    </li>
</ul>

<div class="personal-profile">
    <div class="personal-profile-photo">
        <div class="profile-photo-upload-btn">
            <div class="text-center add-photo-btn">
                <div class="add-photo-icon">+</div>
                <div class="add-photo-text"><?= __('Add photo') ?></div>
            </div>
        </div>
    </div>
    <div class="profile-details ps-md-4">
        <div class="h3 fw-bold mb-2">User Name</div>
        <div class="text-secondary">Login: user_login</div>
        <div class="text-secondary">Post: Supervisor</div>
        <div class="text-secondary">Last seen: 22.12.2021 14:32:23</div>
    </div>
</div>

<div class="border-bottom mt-4 mb-4"></div>

<div class="mb-3">
    <div class="fs-4 fw-bold">General information</div>
    <div>
        <div class="profile-info-row row">
            <div class="profile-info-name col-12 col-md-3">Birthday</div>
            <div class="profile-info-value col-12 col-md-9">07.02.1987 (45 y.o.)</div>
        </div>
        <div class="profile-info-row row">
            <div class="profile-info-name col-12 col-md-3">Gender</div>
            <div class="profile-info-value col-12 col-md-9">male</div>
        </div>
    </div>
</div>

<div class="mb-3">
    <div class="fs-4 fw-bold">Contacts</div>
    <div>
        <div class="profile-info-row row">
            <div class="profile-info-name col-12 col-md-3">Phone</div>
            <div class="profile-info-value col-12 col-md-9">+7 (999) 999-99-99</div>
        </div>
        <div class="profile-info-row row">
            <div class="profile-info-name col-12 col-md-3">E-mail</div>
            <div class="profile-info-value col-12 col-md-9">
                <a href="mailto:mail@example.com">mail@example.com</a>
            </div>
        </div>
        <div class="profile-info-row row">
            <div class="profile-info-name col-12 col-md-3">Telegram</div>
            <div class="profile-info-value col-12 col-md-9">
                <a href="https://t.me/johncms_official">@johncms_official</a>
            </div>
        </div>
        <div class="profile-info-row row">
            <div class="profile-info-name col-12 col-md-3">Website</div>
            <div class="profile-info-value col-12 col-md-9">
                <a href="https://johncms.com">johncms.com</a>
            </div>
        </div>
    </div>
</div>
<div class="mb-3">
    <div class="fs-4 fw-bold">About</div>
    <div class="text-dark">
        If you need responsive nav variations, consider using a series of flexbox utilities. While more verbose, these utilities offer greater customization across responsive breakpoints. In the example below, our nav will be stacked on the lowest breakpoint, then adapt to a horizontal layout that fills the available width starting from the small breakpoint.
    </div>
</div>
