<?php
/**
 * @var $data
 */

?>

<form action="<?= $data['action_url'] ?>" method="post">
    <div class="modal-header align-items-center">
        <h4 class="modal-title">
            <?= __('Confirm the action') ?>
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span class="icon">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <input type="hidden" name="delete_token" value="<?= $data['delete_token'] ?>">
        <?php if (! empty($data['section'])): ?>
            <div><?= __('Section:') ?> <b><?= $data['section']->name ?></b></div>
        <?php endif; ?>
        <?php if (! empty($data['article'])): ?>
            <div><?= __('Article:') ?> <b><?= $data['article']->name ?></b></div>
        <?php endif; ?>
        <?= __('Do you really want to delete?') ?>
    </div>
    <div class="modal-footer">
        <button type="submit" name="delete" value="1" class="btn btn-danger"><?= __('Delete') ?></button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= __('Cancel') ?></button>
    </div>
</form>
