<?php
$this->layout('system::layout/old_default', [
    'title' => _t('Select language', 'system'),
    'homeButton' => true
])
?>
<div class="menu" style="padding-top: 16px; padding-bottom: 16px">
    <form method="post">
        <h3><?= _t('Select language', 'system') ?></h3>
        <?php foreach ($config->lng_list as $key => $val): ?>
            <div>
                <label>
                    <input type="radio" value="<?= $key ?>" name="setlng"<?= ($key == $locale ? ' checked="checked"' : '') ?>/>&#160;
                    <img src="<?= $this->asset('images/flags/' . strtolower($key) . '.png') ?>" alt="" style="margin-right: 8px; vertical-align: middle">
                    <?= $val ?>
                </label>
            </div>
        <?php endforeach ?>
        <br>
        <input type="submit" name="submit" value="<?= _t('Apply', 'system') ?>"/>
    </form>
</div>
