<?php

/**
 * @var $sender_name
 * @var $sender_email
 * @var $message_text
 * @var $admin_link
 * @var $config
 */

$this->layout('system::mail/layouts/default', ['email_title' => __('New message from the contact form')]);
?>

<p>
    <?= __('A new message has been sent through the contact form on the <a href="%s">%s</a> website', $config['homeurl'], $config['copyright']) ?>
</p>
<p>
    <?= __('Sender:') ?> <b><?= $this->e($sender_name) ?></b><br>
    <?= __('E-mail:') ?> <b><?= $this->e($sender_email) ?></b>
</p>
<p><?= nl2br($this->e($message_text)) ?></p>
<p style="text-align: center;">
    <a class="button" href="<?= $this->e($admin_link) ?>"
       style="background-color:#66615b;border-radius:4px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:18px;font-weight:bold;line-height:60px;text-align:center;text-decoration:none;width:200px;-webkit-text-size-adjust:none;">
        <?= __('Open in admin panel') ?>
    </a>
</p>
