<?php $this->layout(
    'system::layout/default',
    [
        'title'      => __('Restore password'),
        'page_title' => __('Restore password'),
    ]
) ?>

<form action="skl.php?act=sent" method="post">
    <h4><?= __('Restore password') ?></h4>
    <div class="form-group">
        <label for="nick"><?= __('Username') ?></label>
        <input type="text"
               class="form-control"
               name="nick"
               id="nick"
               required
               placeholder="<?= __('Username') ?>"
        >
    </div>
    <div class="form-group">
        <label for="email"><?= __('Your E-mail') ?></label>
        <input type="email"
               class="form-control"
               name="email"
               id="email"
               required
               placeholder="<?= __('Your E-mail') ?>"
        >
    </div>
    <img alt="<?= __('Verification code') ?>" src="<?= $captcha ?>">
    <div class="form-group">
        <label for="code"><?= __('Enter verification code') ?></label>
        <input type="text"
               class="form-control"
               maxlength="5"
               name="code"
               id="code"
               required
               placeholder="<?= __('Verification code') ?>"
        >
    </div>
    <input type="submit" name="login" value="<?= __('Continue') ?>" class="btn btn-primary"/>

    <div class="alert alert-info mt-3">
        <?= __('Password will be send to E-mail address specified in your profile.<br />WARNING !! If E-mail address has not been specified in your profile, you will not be able to recover your password.') ?>
    </div>
</form>
