<?php $this->layout('system::layout/default') ?>

<h4><?= __('Edit message') ?></h4>
<?php if (! empty($errors['csrf_token'])): ?>
    <div class="alert alert-danger"><?= implode(', ', $errors['csrf_token']) ?></div>
<?php endif ?>
<form action="/guestbook/edit?id=<?= $id ?>" method="post">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>"/>
    <p>
        <b><?= __('Author') ?>:</b> <?= $message->name ?>
    <p>
        <?= $this->fetch(
            'guestbook::ckeditor',
            [
                'label'  => __('Message'),
                'errors' => implode(', ', $errors['message'] ?? []),
                'value'  => $text,
            ]
        ) ?>
    <div>
        <button type="submit" name="submit" value="submit" class="btn btn-primary mr-2"><?= __('Save') ?></button>
        <a href="/guestbook/" class="btn btn-outline-primary"><?= __('Back') ?></a>
    </div>
</form>
<?php $this->push('scripts') ?>
<?= $this->fetch('guestbook::ckeditor') ?>
<?php $this->stop(); ?>
