<?php $this->layout('system::layout/default', [
    'title'       => _t('Registration'),
    'page_title'  => _t('Registration'),
    'breadcrumbs' => $breadcrumbs,
]) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-10">
        <div class="card shadow border-0 border-radius-12">
            <div class="card-body">
                <?= _t('Registration is temporarily closed') ?>
            </div>
        </div>
    </div>
</div>
