<?php

/**
 * @var string $confirm - Confirmation type
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => __('Login'),
        'page_title' => __('Login'),
    ]
) ?>

<?php if ($confirm === 'email'): ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-info',
            'alert'      => __('You didn\'t confirm your email address. Please check your email and follow the instructions in it.'),
        ]
    ) ?>
<?php else: ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-info',
            'alert'      => __('Sorry, but your request for registration is not considered yet. Please, be patient.'),
        ]
    ) ?>
<?php endif; ?>
