<?php $this->layout(
    'system::layout/default',
    [
        'title'      => __('Logout'),
        'page_title' => __('Logout'),
    ]
) ?>
<div class="alert alert-danger">
    <p class="h4 pb-2"><?= __('Are you sure you want to leave the site?') ?></p>
    <form method="post">
        <input type="submit" name="logout" value="<?= __('Logout') ?>" class="btn btn-danger btn-sm">
        <a class="btn btn-outline-secondary btn-sm" href="<?= $referer ?>"><?= __('Cancel') ?></a>
    </form>
</div>
