<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var array $data
 */
$this->layout('system::layout/default');
?>

<form method="post" class="mb-3" action="<?= $data['confirmUrl'] ?>">
    <div class="alert alert-warning"><?= __('Are you sure you want to leave the site?') ?></div>
    <?= $this->fetch(
        'system::forms/simple_form',
        [
            'fields' => [],
            'errors' => [],
        ]
    ); ?>
    <button type="submit" name="submit" class="btn btn-primary"><?= __('Confirm') ?></button>
    <a href="<?= route('homepage.index') ?>" class="btn btn-outline-secondary"><?= __('Cancel') ?></a>
</form>
