<?php
/**
 * @var string                     $locale
 * @var Johncms\Api\ToolsInterface $tools
 * @var Johncms\Api\UserInterface  $user
 */

/** @var \Johncms\Utility\Counters $counters */
$counters = $container->get('counters');
$notifications = $counters->notifications();
$forum_counters = $counters->forumCounters();
$guestbook_counters = $counters->guestbookCounters();
$downloads_counters = $counters->downloadsCounters();
$library_counters = $counters->libraryCounters();
$users_counters = $counters->usersCounters();
$album_counters = $counters->albumCounters();
$news_counters = $counters->news();
?>
<!DOCTYPE html>
<html lang="<?= $locale ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="Generator" content="JohnCMS, https://johncms.com">
    <meta name="keywords" content="<?= $config->meta_key ?>">
    <meta name="description" content="<?= $config->meta_desc ?>">
    <meta name="theme-color" content="#586776">
    <link rel="stylesheet" href="<?= $this->asset('css/app.css', true) ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/prism.css') ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/magnific-popup.css') ?>">
    <link rel="shortcut icon" href="<?= $this->asset('images/favicon.ico') ?>">
    <link rel="alternate" type="application/rss+xml" title="RSS News" href="<?= $config->homeurl ?>/rss/">
    <title><?= (isset($title) ? $this->e($title) . ' | ' : '') . $config->copyright ?></title>
</head>
<body>
<div class="wrapper justify-content-end d-flex" id="app">
    <div class="sidebar">
        <div class="sidebar__logo">
            <a href="/">
                <span class="logo__image">
                    <img src="<?= $this->asset('images/logo.svg') ?>" alt="logo" style="width: 70%;" class="img-fluid">
                </span>
            </a>
        </div>
        <div class="sidebar__wrapper">
            <!-- Пользователь -->
            <div class="sidebar__user">
                <a class="nav-link user__link" href="#" data-toggle="dropdown" aria-expanded="false">
                    <?= ($user->id ? $user->name : _t('Guest', 'system')) ?>
                    <span>
                        <svg class="icon icon-chevron-bottom">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
                        </svg>
                    </span>
                </a>
                <div class="dropdown-menu">
                    <?php if ($user->isValid()): ?>
                        <a class="dropdown-item" href="/profile/?act=office"><?= _t('Personal', 'system') ?></a>
                    <?php else: ?>
                        <a class="dropdown-item" href="/login/"><?= _t('Login', 'system') ?></a>
                        <a class="dropdown-item" href="/registration/"><?= _t('Registration', 'system') ?></a>
                    <?php endif ?>
                </div>
            </div>

            <?php if ($user->isValid()): ?>
                <!-- Группа кнопок -->
                <div class="sidebar__buttons btn-group">
                    <div class="group_item">
                        <a href="/notifications/" title="<?= _t('Notifications', 'system') ?>">
                            <svg class="icon icon_messages">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#messages"/>
                            </svg>
                            <?php if (! empty($notifications['all'])): ?>
                                <span class="badge badge-danger badge-pill"><?= $notifications['all'] ?></span>
                            <?php endif ?>
                        </a>
                    </div>
                    <div class="group_item">
                        <a href="/profile/">
                            <svg class="icon icon_add">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
                            </svg>
                        </a>
                    </div>
                    <div class="group_item">
                        <a href="/profile/?act=settings">
                            <svg class="icon icon_search">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#settings"/>
                            </svg>
                        </a>
                    </div>
                </div>
            <?php else: ?>
                <div class="border-bottom"></div>
            <?php endif ?>

            <!-- Меню -->
            <ul class="nav nav__vertical">
                <li>
                    <a href="/news/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#book"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('News archive', 'system') ?></span>
                        <?php if ($news_counters['total'] > 0): ?>
                            <span class="badge badge-pill <?= ($news_counters['new'] > 0 ? 'badge-danger' : 'badge-secondary') ?>">
                                    <?= $tools->formatNumber($news_counters['total']) ?>
                                    <?= ($news_counters['new'] > 0 ? '/ +' . $tools->formatNumber($news_counters['new']) : '') ?>
                                </span>
                        <?php endif ?>
                    </a>
                </li>
                <?php if ($config->mod_forum || $user->rights >= 7): ?>
                    <li>
                        <a href="/forum/">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                            </svg>
                            <span class="flex-grow-1">Форум</span>
                            <span class="badge badge-pill <?= ($forum_counters['new_messages'] > 0 ? 'badge-danger' : 'badge-secondary') ?>">
                                <?= $tools->formatNumber($forum_counters['topics']) ?> / <?= $tools->formatNumber($forum_counters['messages']) ?>
                                <?= ($forum_counters['new_messages'] > 0 ? '/ +' . $tools->formatNumber($forum_counters['new_messages']) : '') ?>
                            </span>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($config->mod_guest || $user->rights >= 7): ?>
                    <li>
                        <a href="/guestbook/">
                            <svg class="icon guest-book-icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chat"/>
                            </svg>
                            <span class="flex-grow-1"><?= _t('Guestbook', 'system') ?></span>
                            <?php if ($guestbook_counters['guestbook'] > 0 || $guestbook_counters['admin_club'] > 0): ?>
                                <span class="badge badge-pill badge-secondary">
                                    <?= $tools->formatNumber($guestbook_counters['guestbook']) ?>
                                    <?= $guestbook_counters['admin_club'] > 0 ? ' / ' . $tools->formatNumber($guestbook_counters['admin_club']) : '' ?>
                                </span>
                            <?php endif ?>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($config->mod_down || $user->rights >= 7): ?>
                    <li>
                        <a href="/downloads/">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#download"/>
                            </svg>
                            <span class="flex-grow-1"><?= _t('Downloads', 'system') ?></span>
                            <?php if ($downloads_counters['total'] > 0): ?>
                                <span class="badge badge-pill <?= ($downloads_counters['new'] > 0 ? 'badge-danger' : 'badge-secondary') ?>">
                                    <?= $tools->formatNumber($downloads_counters['total']) ?>
                                    <?= ($downloads_counters['new'] > 0 ? '/ +' . $tools->formatNumber($downloads_counters['new']) : '') ?>
                                </span>
                            <?php endif ?>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($config->mod_lib || $user->rights >= 7): ?>
                    <li>
                        <a href="/library/">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#text"/>
                            </svg>
                            <span class="flex-grow-1"><?= _t('Library', 'system') ?></span>
                            <?php if ($library_counters['total'] > 0): ?>
                                <span class="badge badge-pill <?= ($library_counters['new'] > 0 ? 'badge-danger' : 'badge-secondary') ?>">
                                    <?= $tools->formatNumber($library_counters['total']) ?>
                                    <?= ($library_counters['new'] > 0 ? '/ +' . $tools->formatNumber($library_counters['new']) : '') ?>
                                </span>
                            <?php endif ?>
                        </a>
                    </li>
                <?php endif ?>
                <li>
                    <a href="/users/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#users"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Users', 'system') ?></span>
                        <?php if ($users_counters['total'] > 0): ?>
                            <span class="badge badge-pill <?= ($users_counters['new'] > 0 ? 'badge-danger' : 'badge-secondary') ?>">
                                <?= $tools->formatNumber($users_counters['total']) ?>
                                <?= ($users_counters['new'] > 0 ? '/ +' . $tools->formatNumber($users_counters['new']) : '') ?>
                            </span>
                        <?php endif ?>
                    </a>
                </li>
                <li>
                    <a href="/album/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#picasa"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Photo Albums', 'system') ?></span>
                        <?php if ($album_counters['photo'] > 0): ?>
                            <span class="badge badge-pill <?= ($album_counters['new'] > 0 ? 'badge-danger' : 'badge-secondary') ?>">
                                <?= $tools->formatNumber($album_counters['album']) ?> / <?= $tools->formatNumber($album_counters['photo']) ?>
                                <?= ($album_counters['new'] > 0 ? '/ +' . $tools->formatNumber($album_counters['new']) : '') ?>
                            </span>
                        <?php endif ?>
                    </a>
                </li>
                <li>
                    <a href="/help/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#info"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Information, FAQ', 'system') ?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="content-container content-container-padding">
        <nav class="navbar navbar-expand-lg top_nav fixed-top border-bottom shadow">
            <div class="container-fluid">
                <div class="navbar-wrapper d-flex w-100 justify-content-between">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <div>
                        <?php if ($user->isValid()): ?>
                            <a href="/notifications/" class="icon_with_badge mr-2">
                                <svg class="icon icon_messages">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#messages"/>
                                </svg>
                                <?php if (! empty($notifications['all'])): ?>
                                    <span class="badge badge-danger badge-pill"><?= $notifications['all'] ?></span>
                                <?php endif ?>
                            </a>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <?php if (! empty($page_title)): ?>
                <h1 class="mb-0"><?= $this->e($page_title) ?></h1>
            <?php endif; ?>
            <?php if (! empty($breadcrumbs)): ?>
                <?php $this->insert('system::app/breadcrumbs', ['breadcrumbs' => $breadcrumbs]); ?>
            <?php endif; ?>

            <?= $this->section('content') ?>
        </div>
    </div>
</div>
<script src="<?= $this->asset('js/app.js', true) ?>"></script>
</body>
</html>
