<?php
/**
 * @var string                     $locale
 * @var Johncms\Api\ToolsInterface $tools
 * @var Johncms\Api\UserInterface  $user
 */
?>
<!DOCTYPE html>
<html lang="<?= $locale ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="Generator" content="JohnCMS, https://johncms.com">
    <meta name="keywords" content="<?= $config->meta_key ?>">
    <meta name="description" content="<?= $config->meta_desc ?>">
    <meta name="theme-color" content="#586776">
    <link rel="stylesheet" href="<?= $this->asset('css/app.css', true) ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/prism.css') ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/magnific-popup.css') ?>">
    <link rel="shortcut icon" href="<?= $this->asset('images/favicon.ico') ?>">
    <link rel="alternate" type="application/rss+xml" title="RSS News" href="<?= $config->homeurl ?>/rss/">
    <title><?= (isset($title) ? $this->e($title) . ' | ' : '') . $config->copyright ?></title>
</head>
<body>
<div class="wrapper justify-content-end d-flex" id="app">
    <div class="sidebar">
        <div class="sidebar__logo">
            <a href="#">
                <span class="logo__image">
                    <img src="<?= $this->asset('images/logo.gif') ?>" alt="logo" style="width: 170px;" class="img-fluid">
                </span>
            </a>
        </div>
        <div class="sidebar__wrapper">
            <!-- Пользователь -->
            <div class="sidebar__user">
                <a class="nav-link user__link"
                   href="#"
                   data-toggle="dropdown"
                   aria-expanded="false">
                    Алексей Иванов
                    <span>
                        <svg class="icon icon-chevron-bottom">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
                        </svg>
                    </span>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Изменить профиль</a>
                    <a class="dropdown-item" href="#">Настройки</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Выход</a>
                </div>
            </div>

            <!-- Группа кнопок -->
            <div class="sidebar__buttons btn-group">
                <div class="group_item">
                    <a href="#">
                        <svg class="icon icon_messages">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#messages"/>
                        </svg>
                        <span class="badge badge-danger badge-pill">3</span>
                    </a>
                </div>
                <div class="group_item">
                    <a href="">
                        <svg class="icon icon_add">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
                        </svg>
                    </a>
                </div>
                <div class="group_item">
                    <a href="">
                        <svg class="icon icon_search">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#settings"/>
                        </svg>
                    </a>
                </div>
            </div>

            <!-- Меню -->
            <ul class="nav nav__vertical">
                <li>
                    <a href="/news/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#book"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('News archive', 'system') ?></span>
                    </a>
                </li>
                <?php if ($config->mod_forum || $user->rights >= 7): ?>
                    <li>
                        <a href="/forum/">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                            </svg>
                            <span class="flex-grow-1">Форум</span>
                            <span class="badge badge-danger badge-pill">15</span>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($config->mod_guest || $user->rights >= 7): ?>
                    <li>
                        <a href="/guestbook/">
                            <svg class="icon guest-book-icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chat"/>
                            </svg>
                            <span class="flex-grow-1"><?= _t('Guestbook', 'system') ?></span>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($config->mod_down || $user->rights >= 7): ?>
                    <li>
                        <a href="/downloads/">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#download"/>
                            </svg>
                            <span class="flex-grow-1"><?= _t('Downloads', 'system') ?></span>
                        </a>
                    </li>
                <?php endif ?>
                <?php if ($config->mod_lib || $user->rights >= 7): ?>
                    <li>
                        <a href="/library/">
                            <svg class="icon">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#text"/>
                            </svg>
                            <span class="flex-grow-1"><?= _t('Library', 'system') ?></span>
                        </a>
                    </li>
                <?php endif ?>
                <li>
                    <a href="/users/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#users"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Users', 'system') ?></span>
                    </a>
                </li>
                <li>
                    <a href="/album/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#picasa"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Photo Albums', 'system') ?></span>
                    </a>
                </li>
                <li>
                    <a href="/help/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#info"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Information, FAQ', 'system') ?></span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="content-container content-container-padding">
        <nav class="navbar navbar-expand-lg top_nav fixed-top border-bottom shadow">
            <div class="container-fluid">
                <div class="navbar-wrapper d-flex w-100 justify-content-between">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <div>
                        <a href="#" class="icon_with_badge mr-2">
                            <svg class="icon icon_messages"><use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#messages"/></svg>
                            <span class="badge badge-danger badge-pill">3</span>
                        </a>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <?= $this->section('content') ?>
        </div>
    </div>
</div>
<script src="<?= $this->asset('js/app.js', true) ?>"></script>
</body>
</html>