<?php
/**
 * @var string                     $locale
 * @var Johncms\Api\ToolsInterface $tools
 */
?>
<!DOCTYPE html>
<html lang="<?= $locale ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="Generator" content="JohnCMS, https://johncms.com">
    <meta name="keywords" content="<?= $config->meta_key ?>">
    <meta name="description" content="<?= $config->meta_desc ?>">
    <meta name="theme-color" content="#5d687c">
    <link rel="stylesheet" href="<?= $config->homeurl ?>/themes/default/assets/css/old.css">
    <link rel="shortcut icon" href="<?= $config->homeurl ?>/themes/default/assets/images/favicon.ico">
    <link rel="alternate" type="application/rss+xml" title="RSS | Новости ресурса" href="<?= $config->homeurl ?>/rss/">
    <title><?= (isset($title) ? $this->e($title) . ' | ' : '') . $config->copyright ?></title>
</head>
<body>
<!-- Логотип и переключатель языков -->
<table style="width: 100%;" class="logo">
    <tr>
        <td valign="bottom">
            <a href="<?= $config->homeurl ?>"><img src="<?= $config->homeurl ?>/themes/default/assets/images/logo.gif" alt="<?= $this->e($config->copyright) ?>" class="icon"/></a>
        </td>
        <?php if (count($config->lng_list) > 1): ?>
            <td align="right">
                <a href="<?= $config->homeurl ?>/language/"><strong><?= strtoupper($locale) ?></strong></a>&#160;
                <a href="<?= $config->homeurl ?>/language/"><?= $tools->getFlag($locale) ?></a>
            </td>
        <?php endif ?>
    </tr>
</table>

<!-- Верхнее меню -->
<?php $this->insert('system::app/old_topmenu', ['homeButton' => $homeButton]) ?>

<div class="maintxt">
    <!-- Уведомления -->
    <!--    --><?php //$this->insert('system::app/old/notifications') ?>

    <!-- Основная информация -->
    <?= $this->section('content') ?>
</div>

<div class="fmenu">
    <!-- Счетчик посетителей онлайн -->
    <img src="<?= $config->homeurl ?>/themes/default/assets/images/old_menu_online.png" class="icon">
    <a href="<?= $config->homeurl ?>/users/?act=online"><?= $container->get('counters')->online() ?></a>
</div>
<div style="text-align:center">
    <p><?= $this->e($config->copyright) ?></p>
    <!-- Внешние счетчики -->
    <!--    --><?php //$this->insert('system::app/old/counters') ?>
    <div>
        <small>&copy; <a href="https://johncms.com">JohnCMS</a></small>
    </div>
</div>
</body>
</html>
