<?php
/**
 * @var string                     $locale
 * @var Johncms\Api\ToolsInterface $tools
 */
?>
<!DOCTYPE html>
<html lang="<?= $locale ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="Generator" content="JohnCMS, https://johncms.com">
    <meta name="keywords" content="<?= $config->meta_key ?>">
    <meta name="description" content="<?= $config->meta_desc ?>">
    <meta name="theme-color" content="#586776">
    <link rel="stylesheet" href="<?= $this->asset('css/old.css', true) ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/prism.css') ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/magnific-popup.css') ?>">
    <link rel="shortcut icon" href="<?= $this->asset('images/favicon.ico') ?>">
    <link rel="alternate" type="application/rss+xml" title="RSS News" href="<?= $config->homeurl ?>/rss/">
    <title><?= (isset($title) ? $this->e($title) . ' | ' : '') . $config->copyright ?></title>
</head>
<body>

<!-- Логотип и переключатель языков -->
<table style="width: 100%;" class="logo">
    <tr>
        <td valign="bottom">
            <a href="<?= $config->homeurl ?>">
                <img src="<?= $this->asset('images/logo.gif') ?>" alt="<?= $this->e($config->copyright) ?>" class="icon"/>
            </a>
        </td>
        <?php if (count($config->lng_list) > 1): ?>
            <td style="text-align: right">
                <a href="<?= $config->homeurl ?>/language/"><strong><?= strtoupper($locale) ?></strong></a>&#160;
                <a href="<?= $config->homeurl ?>/language/">
                    <img src="<?= $this->asset('images/flags/' . strtolower($locale) . '.png') ?>" alt="" style="margin-right: 8px; vertical-align: middle">
                </a>
            </td>
        <?php endif ?>
    </tr>
</table>

<!-- Верхнее меню -->
<div class="header">
    <?= _t('Hi', 'system') ?>,
    <?= ($user->id ? '<b>' . $user->name . '</b>!' : _t('Guest', 'system') . '!') ?>
</div>
<div class="tmn">
    <?php if (isset($homeButton)): ?>
        <a href="<?= $config->homeurl ?>">
            <img src="<?= $this->asset('images/old_menu_home.png') ?>" class="icon">
            <?= _t('Home', 'system') ?>
        </a>
        <br>
    <?php endif ?>
    <?php if ($user->isValid()): ?>
        <a href="<?= $config->homeurl ?>/profile/?act=office">
            <img src="<?= $this->asset('images/old_menu_cabinet.png') ?>" class="icon">
            <?= _t('Personal', 'system') ?>
        </a>
    <?php else: ?>
        <a href="<?= $config->homeurl ?>/login/">
            <img src="<?= $this->asset('images/old_menu_login.png') ?>" class="icon">
            <?= _t('Login', 'system') ?>
        </a>
    <?php endif ?>
</div>

<div class="maintxt">
    <!-- Уведомления -->
    <?php $this->insert('system::app/old_notifications') ?>

    <!-- Основная информация -->
    <?= $this->section('content') ?>
</div>

<div class="fmenu">
    <!-- Счетчик посетителей онлайн -->
    <img src="<?= $this->asset('images/old_menu_online.png') ?>" alt="" class="icon">
    <a href="<?= $config->homeurl ?>/users/?act=online"><?= $container->get('counters')->online() ?></a>
</div>
<div style="text-align:center">
    <p><?= $this->e($config->copyright) ?></p>
    <!-- Внешние счетчики -->
    <?php $this->insert('system::app/old_counters') ?>
    <div>
        <small>&copy; <a href="https://johncms.com">JohnCMS</a></small>
    </div>
</div>
<script src="<?= $this->asset('js/jquery-3.4.1.min.js') ?>"></script>
<script src="<?= $this->asset('js/jquery.magnific-popup.js') ?>"></script>
<script src="<?= $this->asset('js/prism.js') ?>"></script>
<script src="<?= $this->asset('js/scripts.js') ?>"></script>
</body>
</html>
