<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
$form_data = $data['form_data'] ?? [];
?>

<div class="row">
    <div class="col-md-6">
        <div class="card shadow border-0">
            <div class="card-body">
                <form name="file_edit_form" action="<?= $data['action_url'] ?>" method="post" enctype="multipart/form-data">
                    <?php if (! empty($data['error_message'])): ?>
                        <?= $this->fetch(
                            'system::app/alert',
                            [
                                'alert_type' => 'alert-danger border-0',
                                'alert'      => $data['error_message'],
                            ]
                        ) ?>
                    <?php endif; ?>
                    <div class="form-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="file" name="imagefile" aria-describedby="file_label" required>
                            <label class="custom-file-label" for="file"><?= _t('Choose file') ?></label>
                        </div>
                        <div class="text-muted mb-3 small">
                            <?= sprintf(_t('Allowed format image JPG, JPEG, PNG, GIF<br>File size should not exceed %d kb.'), $config['flsz']) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description"><?= _t('Description') ?></label>
                        <textarea id="description" name="description" class="form-control" rows="<?= $user->config->fieldHeight ?>"></textarea>
                    </div>
                    <div class="mt-3">
                        <button type="submit" name="submit" value="1" class="btn btn-primary"><?= _t('Save') ?></button>
                        <a href="<?= $data['back_url'] ?>" class="btn btn-secondary"><?= _t('Cancel') ?></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
