<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout('system::layout/default');
?>

<form name="file_edit_form" action="<?= $this->e($data['action_url']) ?>" method="post">
    <div class="mb-3">
        <img src="<?= $this->e($data['image_url']) ?>" alt=".">
    </div>

    <div class="form-group">
        <label for="description"><?= __('Description') ?></label>
        <textarea id="description" name="description" class="form-control" rows="<?= $user->config->fieldHeight ?>"><?= $this->e($data['description']) ?></textarea>
    </div>
    <div class="mt-3">
        <button type="submit" name="submit" value="1" class="btn btn-primary"><?= __('Save') ?></button>
        <a href="<?= $this->e($data['back_url']) ?>" class="btn btn-secondary"><?= __('Cancel') ?></a>
    </div>
</form>
