<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?php if (! $config->mod_down): ?>
    <div class="alert alert-danger border-0 shadow">
        <?= _t('Downloads are closed') ?>
    </div>
<?php endif; ?>
<div class="row">
    <div class="col-md-6">
        <div class="list-group">
            <a href="?act=top" class="list-group-item d-flex justify-content-between align-items-center">
                <?= _t('New Photos') ?>
                <span class="badge badge-light badge-pill"><?= $data['new'] ?></span>
            </a>
            <a href="?act=top&amp;mod=last_comm" class="list-group-item d-flex justify-content-between align-items-center">
                <?= _t('New Comments') ?>
            </a>
        </div>

        <h3 class="mt-3"><?= _t('Albums') ?></h3>

        <div class="list-group">
            <a href="?act=users&amp;mod=boys" class="list-group-item d-flex justify-content-between align-items-center">
                <?= _t('Guys') ?>
                <span class="badge badge-light badge-pill"><?= $data['men'] ?></span>
            </a>
            <a href="?act=users&amp;mod=girls" class="list-group-item d-flex justify-content-between align-items-center">
                <?= _t('Girls') ?>
                <span class="badge badge-light badge-pill"><?= $data['women'] ?></span>
            </a>
            <?php if ($user->isValid()): ?>
                <a href="?act=list" class="list-group-item d-flex justify-content-between align-items-center">
                    <?= _t('My Album') ?>
                </a>
            <?php endif; ?>
        </div>

        <h3 class="mt-3"><?= _t('Rating') ?></h3>

        <div class="list-group">
            <a href="?act=top&amp;mod=votes" class="list-group-item"><?= _t('Top Votes') ?></a>
            <a href="?act=top&amp;mod=downloads" class="list-group-item"><?= _t('Top Downloads') ?></a>
            <a href="?act=top&amp;mod=views" class="list-group-item"><?= _t('Top Views') ?></a>
            <a href="?act=top&amp;mod=comments" class="list-group-item"><?= _t('Top Comments') ?></a>
            <a href="?act=top&amp;mod=trash" class="list-group-item"><?= _t('Top Worst') ?></a>
        </div>
    </div>
</div>
