<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var array $filters
 * @var array $users
 * @var int $total
 * @var int $per_page
 * @var string $pagination
 */

// title / page_title are provided globally via Render::addData() in the controller.
$this->layout('system::layout/default');
?>

<div class="btn-group mb-3" role="group">
    <?php foreach ($filters as $filter): ?>
        <a href="<?= $this->e($filter['url']) ?>" class="btn btn-outline-secondary <?= ($filter['active'] ? 'active' : '') ?>"><?= $this->e($filter['name']) ?></a>
    <?php endforeach; ?>
</div>

<?php if (empty($users)): ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-info',
            'alert'      => __('The list is empty'),
        ]
    ) ?>
<?php endif; ?>

<?php foreach ($users as $user_row): ?>
    <?= $this->fetch('album::user_row', ['item' => $user_row]) ?>
<?php endforeach; ?>

<div class="mt-3">
    <?php if ($total > $per_page): ?>
        <?= $pagination ?>
    <?php endif; ?>
    <?php if ($total > 0): ?>
        <div><?= __('Total:') ?> <?= $total ?></div>
    <?php endif; ?>
</div>
