<?php

declare(strict_types=1);

namespace Tests\Unit\Validator;

use Gettext\Translator;
use Gettext\TranslatorFunctions;
use Johncms\Validator\Translation\GettextTranslator;
use PHPUnit\Framework\TestCase;

final class GettextTranslatorTest extends TestCase
{
    protected function setUp(): void
    {
        TranslatorFunctions::register(new Translator());
    }

    public function testAnUntranslatedMessageIsReturnedAsIs(): void
    {
        self::assertSame('You have a ban', (new GettextTranslator())->trans('You have a ban'));
    }

    /**
     * The point of keeping the msgids of the previous engine: twenty catalogs already translate
     * them, and the migration must not spend a single new string.
     */
    public function testATranslatedMessageComesFromTheSystemDomain(): void
    {
        $this->givenTranslation('You have a ban', 'У вас бан');

        self::assertSame('У вас бан', (new GettextTranslator())->trans('You have a ban'));
    }

    /**
     * Symfony names the bound of a Length violation {{ limit }}, while the msgid of this project
     * names it %min% or %max% — both spellings are filled in, so the message reaches the page
     * with a number in it rather than with a placeholder.
     */
    public function testTheLimitOfAConstraintFillsBothPlaceholderSpellings(): void
    {
        $translator = new GettextTranslator();

        self::assertSame(
            'The input is less than 4 characters long',
            $translator->trans('The input is less than %min% characters long', ['{{ limit }}' => 4])
        );
        self::assertSame(
            'The input is more than 16 characters long',
            $translator->trans('The input is more than %max% characters long', ['{{ limit }}' => 16])
        );
    }

    /**
     * A runtime parameter a rule of ours sets itself, such as the remaining antiflood delay.
     */
    public function testARuntimeParameterIsSubstituted(): void
    {
        self::assertSame(
            'You cannot add the message so often. Please, wait 7 seconds.',
            (new GettextTranslator())->trans(
                'You cannot add the message so often. Please, wait %value% seconds.',
                ['%value%' => 7]
            )
        );
    }

    public function testTheSymfonySpellingOfAParameterWorksToo(): void
    {
        self::assertSame(
            'The security code is not correct: 42',
            (new GettextTranslator())->trans('The security code is not correct: {{ value }}', ['{{ value }}' => 42])
        );
    }

    private function givenTranslation(string $original, string $translation): void
    {
        // The dictionary format the runtime translator reads: the same shape the .lng.php files
        // generated by `composer translate` have.
        $translator = new Translator();
        $translator->addTranslations([
            'domain'   => 'system',
            // Keyed by context first, the empty one being the default.
            'messages' => ['' => [$original => $translation]],
        ]);

        TranslatorFunctions::register($translator);
    }
}
