<?php
/**
 * @var $title
 * @var $page_title
 * @var $file_attached
 * @var $back_url
 */

$this->layout('system::layout/default', [
    'title'      => $title,
    'page_title' => $page_title,
]);
?>

<?php if ($file_attached): ?>
    <div class="alert alert-success">
        <?= _t('File attached'); ?>
    </div>
    <div class="mt-3">
        <a href="/forum/?act=addfile&id=<?= $id ?>" class="btn btn-primary"><?= _t('Add more') ?></a>
        <a href="<?= $back_url ?>" class="btn btn-secondary"><?= _t('Back to topic') ?></a>
    </div>
<?php else: ?>
    <div class="row">
        <div class="col-md-6">
            <form name="new_topic" action="/forum/?act=addfile&amp;id=<?= $id ?>" method="post" enctype="multipart/form-data">
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="fail" name="fail" aria-describedby="file_label" required>
                        <label class="custom-file-label" for="fail"><?= _t('Choose file') ?></label>
                    </div>
                </div>
                <div class="text-muted mb-3 small">
                    <?= _t('Max. Size') ?>: <?= $config['flsz'] ?> kb.
                </div>
                <div>
                    <button type="submit" name="submit" value="1" class="btn btn-primary"><?= _t('Upload') ?></button>
                    <a href="<?= $back_url ?>" class="btn btn-secondary"><?= _t('Back to topic') ?></a>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>
