<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $file_attached
 * @var $back_url
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>
<form action="/forum/?act=search&amp;mod=reset" method="post">
    <div class="alert alert-danger">
        <?= __('Do you really want to clear the search history?') ?>
    </div>
    <div>
        <button type="submit" name="submit" value="1" class="btn btn-primary"><?= __('Clear') ?></button>
        <a href="<?= $back_url ?>" class="btn btn-secondary"><?= __('Cancel') ?></a>
    </div>
</form>
