<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $file_attached
 * @var $back_url
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="row">
    <div class="col-md-6">
        <form action="/forum/?act=search&amp;mod=reset" method="post">
            <div class="alert alert-danger">
                <?= _t('Do you really want to clear the search history?') ?>
            </div>
            <div>
                <button type="submit" name="submit" value="1" class="btn btn-primary"><?= _t('Clear') ?></button>
                <a href="<?= $back_url ?>" class="btn btn-secondary"><?= _t('Cancel') ?></a>
            </div>
        </form>
    </div>
</div>
