<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $posts
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-danger">
    <?php if ($posts == 1): ?>
        <div class="font-weight-bold">
            <?= __('WARNING!<br>This is last post of topic. By deleting this post topic will be deleted (or hidden) too') ?>
        </div>
    <?php endif; ?>
    <div class="pb-2">
        <?= __('Do you really want to delete?') ?>
    </div>
    <div>
        <a href="/forum/?act=editpost&amp;do=delete&amp;id=<?= $id ?>" class="mr-2 btn btn-danger btn-sm"><?= __('Delete') ?></a>
        <?php if ($user->rights == 9): ?>
            <a href="/forum/?act=editpost&amp;do=delete&amp;hide&amp;id=<?= $id ?>" class="mr-2 btn btn-primary btn-sm"><?= __('Hide') ?></a>
        <?php endif; ?>
        <a href="<?= $back_url ?>"><?= __('Cancel') ?></a>
    </div>
    <div class="mt-2 text-muted small">
        <?= __('After deleting, one point will be subtracted from the counter of forum posts') ?>
    </div>
</div>
