<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $posts
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('Do you really want to delete?') ?>
    </div>
    <div>
        <form action="/forum/?act=editpost&amp;do=deletefile&amp;fid=<?= $fid ?>&amp;id=<?= $id ?>" method="post">
            <button type="submit" name="delfile" value="1" class="btn btn-danger btn-sm"><?= __('Delete') ?></button>
            <a href="<?= $back_url ?>" class="btn btn-outline-secondary btn-sm"><?= __('Cancel') ?></a>
        </form>
    </div>
    <div class="mt-2 text-muted small">
        <?= __('After deleting, one point will be subtracted from the counter of forum posts') ?>
    </div>
</div>
