<?php
/**
 * @var $title
 * @var $page_title
 * @var $delete_url
 * @var $back_url
 */

$this->layout('system::layout/default', [
    'title'      => $title,
    'page_title' => $page_title,
]);
?>

<div class="row">
    <div class="col-md-6">
        <div class="alert alert-danger">
            <div class="pb-2">
                <?= _t('Do you really want to delete the answer?') ?>
            </div>
            <div>
                <a href="<?= $delete_url ?>" class="btn btn-danger btn-sm mr-2"><?= _t('Delete') ?></a>
                <a href="<?= $back_url ?>"><?= _t('Cancel') ?></a>
            </div>
        </div>
    </div>
</div>
