<?php
/**
 * @var $title
 * @var $page_title
 * @var $file_attached
 * @var $back_url
 */

$this->layout('system::layout/default', [
    'title'      => $title,
    'page_title' => $page_title,
]);
?>

<div class="row">
    <div class="col-md-6">
        <form action="/forum/?act=deltema&amp;id=<?= $id ?>" method="post">
            <div class="alert alert-danger">
                <div class="pb-2">
                    <?= _t('Do you really want to delete?') ?>
                </div>
                <div>
                    <div class="custom-control custom-radio">
                        <input type="radio" id="hide_topic" name="del" checked="checked" value="1" class="custom-control-input">
                        <label class="custom-control-label" for="hide_topic"><?= _t('Hide') ?></label>
                    </div>
                    <?php if ($user->rights == 9): ?>
                        <div class="custom-control custom-radio">
                            <input type="radio" id="del_topic" name="del" value="2" class="custom-control-input">
                            <label class="custom-control-label" for="del_topic"><?= _t('Delete') ?></label>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <div>
                <button type="submit" name="submit" value="1" class="btn btn-primary"><?= _t('Perform') ?></button>
                <a href="<?= $back_url ?>" class="btn btn-secondary"><?= _t('Cancel') ?></a>
            </div>
        </form>
    </div>
</div>
