<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $posts
 * @var $csrf_token
 * @var $can_hard_delete
 * @var $delete_action
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-danger">
    <?php if ($posts == 1): ?>
        <div class="fw-bold">
            <?= __('WARNING!<br>This is last post of topic. By deleting this post topic will be deleted (or hidden) too') ?>
        </div>
    <?php endif; ?>
    <div class="pb-2">
        <?= __('Do you really want to delete?') ?>
    </div>
    <div>
        <form action="<?= $delete_action ?>" method="post" class="d-inline">
            <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
            <button type="submit" name="action" value="delete" class="me-2 btn btn-danger btn-sm"><?= __('Delete') ?></button>
            <?php if ($can_hard_delete): ?>
                <button type="submit" name="action" value="hide" class="me-2 btn btn-primary btn-sm"><?= __('Hide') ?></button>
            <?php endif; ?>
            <a href="<?= $back_url ?>"><?= __('Cancel') ?></a>
        </form>
    </div>
    <div class="mt-2 text-muted small">
        <?= __('After deleting, one point will be subtracted from the counter of forum posts') ?>
    </div>
</div>
