<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $files
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>
<?php if (! empty($new_count)): ?>
    <div class="border-top border-bottom mb-3">
        <div class="py-3">
            <a href="#"><?= _t('New Files') ?></a>
            <span class="badge badge-pill badge-danger"><?= $new_count ?></span>
        </div>
    </div>
<?php endif; ?>

<?php if (empty($files)): ?>
    <div class="alert alert-info">
        <?= _t('The list is empty') ?>
    </div>
<?php endif; ?>

<div>
    <?php foreach ($files as $file): ?>
        <div class="shadow post-item mb-2<?= $file['del'] ? ' deleted-post' : '' ?>">
            <div class="post-header d-flex justify-content-between border-bottom pb-1">
                <div class="d-flex align-items-end">
                    <?php if (! empty($file['user_profile_link'])): ?>
                        <a href="<?= $file['user_profile_link'] ?>" class="user-login mr-2"><?= $file['user_name'] ?></a>
                    <?php else: ?>
                        <a class="user-login mr-2"><?= $file['user_name'] ?></a>
                    <?php endif; ?>
                    <span class="post-date"><?= $file['post_time'] ?></span>
                </div>
                <div class="post-actions">
                    <?php if (! empty($file['post_url'])): ?>
                        <a href="<?= $file['post_url'] ?>" class="btn btn-sm btn-secondary"><?= _t('To message') ?></a>
                    <?php endif; ?>
                    <?php if (! empty($file['topic_url'])): ?>
                        <a href="<?= $file['topic_url'] ?>" class="btn btn-sm btn-secondary"><?= _t('To topic') ?></a>
                    <?php endif; ?>
                </div>
            </div>
            <div class="post-body d-flex align-items-start pt-3 pb-3">
                <div class="overflow-auto flex-grow-1"><?= $file['post_text'] ?></div>
            </div>
            <div class="border-top pt-1 pb-1">
                <div class="d-flex flex-wrap pt-2">
                    <div class="attached-file pr-3 d-flex flex-column justify-content-between">
                        <div class="h-100 d-flex justify-content-center align-items-center">
                            <?php if (! empty($file['file_preview'])): ?>
                                <a href="<?= $file['file_url'] ?>" class="image-preview" data-source="<?= $file['file_url'] ?>" title="<?= $file['filename'] ?>">
                                    <img src="<?= $file['file_preview'] ?>" class="img-thumbnail thumb-limit-height" alt="<?= $file['filename'] ?>">
                                </a>
                            <?php else: ?>
                                <a href="<?= $file['file_url'] ?>">
                                    <svg class="icon attachment-icon">
                                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#file"/>
                                    </svg>
                                </a>
                            <?php endif; ?>
                        </div>
                        <div class="pt-1">
                            <div class="text-muted small d-flex flex-wrap justify-content-center">
                                <div class="text-nowrap pr-1">
                                    <svg class="icon downloads-icon">
                                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#download"/>
                                    </svg>
                                    <?= $file['dlcount'] ?>
                                </div>
                                <div>(<?= $file['file_size'] ?>&nbsp;kb)</div>
                            </div>
                            <div class="file-name">
                                <a href="<?= $file['file_url'] ?>" title="<?= $file['filename'] ?>"><?= $file['filename'] ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

<div class="mb-3">
    <div><?= _t('Total') ?>: <?= $total ?></div>
    <!-- Page switching -->
    <?php if ($total > $user->config->kmess): ?>
        <div class="mt-1"><?= $pagination ?></div>
    <?php endif ?>
</div>

<?php if (! empty($back_url)): ?>
    <div class="mb-3">
        <a href="<?= $back_url ?>"><?= $back_url_name ?></a><br>
        <a href="/forum/"><?= _t('Forum') ?></a>
    </div>
<?php endif; ?>
