<?php
/**
 * @var $title
 * @var $page_title
 * @var $sections
 * @var $online
 * @var $files_count
 */

$this->layout('system::layout/default', [
    'title'      => $title,
    'page_title' => $page_title,
]);
?>

<div class="border-top border-bottom d-flex mb-3 pt-2 pb-2 align-items-center">
    <div class="d-flex align-items-center">
        <?= $unread_links ?>
        <!--a href="#"><?= _t('Files') ?></a> <span class="badge badge-pill badge-danger">99</span-->
    </div>
    <div class="pr-3">
        <a href="?act=new&amp;do=period"><?= _t('Show for Period', 'system') ?></a>
    </div>
    <div class="d-flex align-items-center">
        <a href="?act=files" class="pr-2"><?= _t('Files') ?></a><span class="badge badge-pill badge-success"><?= $files_count ?></span>
    </div>
    <div class="ml-auto">
        <form class="form-inline search-in-nav mb-0" action="?act=search">
            <div class="input-with-inner-btn">
                <input class="form-control pr-5 border-radius-12" name="search" type="search" placeholder="Поиск">
                <button class="btn icon-button" type="submit" name="submit" value="s">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#search"/>
                    </svg>
                </button>
            </div>
        </form>
    </div>
</div>

<?php foreach ($sections as $section): ?>
    <div class="shadow border-radius-12 forum-section post-item">
        <div class="section-header" data-toggle="collapse" data-target="#subsections" aria-expanded="false" aria-controls="subsections">
            <div class="d-flex align-items-center">
                <a href="<?= $section['url'] ?>" class="text-dark-brown"><?= $section['name'] ?></a>
                <span class="badge badge-pill badge-danger ml-3"><?= $section['cnt'] ?></span>
            </div>
            <div class="toggle d-flex align-items-center pr-2">
                <svg class="icon icon-chevron-bottom text-dark-brown">
                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
                </svg>
            </div>
        </div>
        <?php if (! empty($section['subsections'])): ?>
            <div class="collapse subsections" id="subsections">
                <div class="pt-2 pb-2">
                    <?php foreach ($section['subsections'] as $subsection): ?>
                        <span class="pr-2">&raquo;</span><a href="<?= $subsection['url'] ?>" class="text-dark-brown"><?= $subsection['name'] ?></a><br>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="small pt-2 text-muted"><?= $section['description'] ?></div>
    </div>
<?php endforeach; ?>

<div class="border-top d-flex mt-4 pt-3 pb-3 align-items-center">
    <div class="pr-3 d-flex align-items-center">
        <?php if ($user->isValid()): ?>
            <a href="?act=who" class="pr-1"><?= _t('Who in Forum') ?></a>
        <?php else: ?>
            <?= _t('Who in Forum') ?>
        <?php endif; ?>
        <span class="badge badge-pill badge-secondary"><?= $online['online_u'] . '&#160;/&#160;' . $online['online_g'] ?></span>
    </div>
    <div>
        <a href="../help/?act=forum"><?= _t('Forum rules') ?></a>
    </div>
</div>
