<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $form_action
 * @var $csrf_token
 * @var int[] $ids
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('Do you really want to delete?') ?>
    </div>
    <div>
        <form action="<?= $form_action ?>" method="post" class="d-inline">
            <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
            <input type="hidden" name="confirm" value="1">
            <?php foreach ($ids as $id): ?>
                <input type="hidden" name="ids[]" value="<?= $id ?>">
            <?php endforeach; ?>
            <button type="submit" class="me-2 btn btn-danger btn-sm"><?= __('Delete') ?></button>
            <a href="<?= $back_url ?>"><?= __('Cancel') ?></a>
        </form>
    </div>
</div>
