<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $restore_action
 * @var $csrf_token
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-info">
    <div class="pb-2">
        <?= __('Do you really want to restore this post?') ?>
    </div>
    <div>
        <form action="<?= $restore_action ?>" method="post">
            <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
            <button type="submit" name="submit" value="1" class="btn btn-primary btn-sm"><?= __('Restore') ?></button>
            <a href="<?= $back_url ?>" class="btn btn-outline-secondary btn-sm"><?= __('Cancel') ?></a>
        </form>
    </div>
</div>
