<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $sections
 * @var $online
 * @var $files_count
 * @var $unread_count
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?= $this->insert(
    'forum::header',
    [
        'unread_count' => $unread_count,
        'files_count'  => $files_count,
        'files_url'    => '/forum/?act=files&c=' . $id,
        'files_name'   => _t('Section Files'),
    ]
) ?>

<?php if (empty($sections)): ?>
    <?= $this->insert(
        'system::app/alert',
        [
            'alert_type' => 'alert-info',
            'alert'      => _t('There are no sections in this category'),
        ]
    ) ?>
<?php endif; ?>

<?php foreach ($sections as $section): ?>
    <div class="shadow border-radius-12 forum-section post-item mb-2">
        <div class="section-header <?= (empty($section['description']) ? 'border-0 pb-0' : '') ?>">
            <div class="d-flex align-items-center">
                <a href="<?= $section['url'] ?>" class="text-dark-brown"><?= $section['name'] ?></a>
                <span class="badge badge-pill badge-light border ml-3"><?= $section['children_count'] ?></span>
            </div>
        </div>
        <?php if (! empty($section['description'])): ?>
            <div class="small pt-2 text-muted"><?= $section['description'] ?></div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<div class="mb-n3 pt-1"><?= _t('Total') ?>: <?= $total ?></div>

<?= $this->insert(
    'forum::footer',
    [
        'online'   => $online,
        'who_url'  => '/forum/?act=who',
        'who_name' => _t('Who in Forum'),
    ]
) ?>
