<?php
/**
 * @var $title
 * @var $page_title
 * @var $sections
 * @var $online
 * @var $files_count
 * @var $unread_count
 */

$this->layout('system::layout/default', [
    'title'      => $title,
    'page_title' => $page_title,
]);
?>
<div class="border-top border-bottom d-flex mb-3 pt-2 pb-2 align-items-center">
    <div class="mr-auto d-flex pt-2 pb-2">
        <?php if ($user->isValid()): ?>
            <div class="d-flex align-items-center pr-2">
                <a href="?act=new" class="pr-2">
                    <span class="d-none d-sm-inline"><?= _t('Unread', 'system') ?></span>
                    <span class="icon_with_badge mr-sm-3">
                        <svg class="icon d-sm-none"><use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/></svg>
                        <span class="badge badge-pill badge-danger"><?= $unread_count ?></span>
                    </span>
                </a>
            </div>
            <div class="pr-3">
                <a href="?act=new&amp;do=period">
                    <span class="d-none d-sm-inline"><?= _t('Show for Period', 'system') ?></span>
                    <svg class="icon d-sm-none">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#calendar"/>
                    </svg>
                </a>
            </div>
        <?php else: ?>
            <div class="pr-3">
                <a href="?act=new">
                    <span class="d-none d-sm-inline"><?= _t('Last activity', 'system') ?></span>
                    <svg class="icon d-sm-none">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#calendar"/>
                    </svg>
                </a>
            </div>
        <?php endif; ?>
        <div class="d-flex align-items-center">
            <a href="?act=files" class="pr-2">
                <span class="d-none d-sm-inline"><?= _t('Category Files') ?></span>
                <span class="icon_with_badge mr-sm-3">
                    <svg class="icon d-sm-none"><use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#download"/></svg>
                    <span class="badge badge-pill badge-success"><?= $files_count ?></span>
                </span>
            </a>
        </div>
    </div>
    <form class="form-inline search-in-nav mb-0" action="?act=search">
        <div class="input-with-inner-btn">
            <input class="form-control pr-5 border-radius-12" name="search" type="search" placeholder="<?= _t('Search') ?>">
            <button class="btn icon-button" type="submit" name="submit" value="s">
                <svg class="icon">
                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#search"/>
                </svg>
            </button>
        </div>
    </form>
</div>

<?php if (empty($topics)): ?>
    <?= $this->insert('system::app/alert', [
        'alert_type' => 'alert-info',
        'alert'      => _t('No topics in this section'),
    ]) ?>
<?php endif; ?>
<?php if ($create_access): ?>
    <div class="mb-3">
        <form action="?act=nt&amp;id=<?= $id ?>" method="post">
            <button type="submit" class="btn btn-primary"><?= _t('New Topic') ?></button>
        </form>
    </div>
<?php endif; ?>

<?php foreach ($topics as $topic): ?>
    <div class="shadow border-radius-12 forum-section post-item mb-3">
        <div class="section-header">
            <div class="d-flex align-items-center">
                <a href="<?= $topic['url'] ?>" class="text-dark-brown"><?= $topic['name'] ?></a>
                <span class="badge badge-pill badge-danger ml-3"><?= $topic['show_posts_count'] ?></span>
            </div>
        </div>
        <div class="small pt-2 text-muted"><?= _t('Last post author') ?>: <?= $topic['show_last_author'] ?>, <?= _t('Last post') ?>: <?= $topic['show_last_post_date'] ?></div>
    </div>
<?php endforeach; ?>

<div><?= _t('Total') ?>: <?= $total ?></div>
<!-- Page switching -->
<?php if ($total > $user->config->kmess): ?>
    <div class="mt-1"><?= $pagination ?></div>
<?php endif ?>

<div class="border-top d-flex mt-2 pt-3 pb-3 align-items-center">
    <div class="pr-3 d-flex align-items-center">
        <?php if ($user->isValid()): ?>
            <a href="?act=who" class="pr-1"><?= _t('Who in Forum') ?></a>
        <?php else: ?>
            <span class="pr-1"><?= _t('Who in Forum') ?></span>
        <?php endif; ?>
        <span class="badge badge-pill badge-secondary"><?= $online['online_u'] . '&#160;/&#160;' . $online['online_g'] ?></span>
    </div>
    <div>
        <a href="/help/?act=forum"><?= _t('Forum rules') ?></a>
    </div>
</div>
