<?php
/**
 * @var $title
 * @var $page_title
 * @var $sections
 * @var $online
 * @var $files_count
 * @var $unread_count
 * @var $create_access
 */

$this->layout('system::layout/default', [
    'title'      => $title,
    'page_title' => $page_title,
]);
?>

<?= $this->insert('forum::header', [
    'unread_count' => $unread_count,
    'files_count'  => $files_count,
    'files_url'    => '/forum/?act=files&s=' . $id,
    'files_name'   => _t('Category Files'),
]) ?>

<?php if (empty($topics)): ?>
    <?= $this->insert('system::app/alert', [
        'alert_type' => 'alert-info',
        'alert'      => _t('No topics in this section'),
    ]) ?>
<?php endif; ?>
<?php if ($create_access): ?>
    <div class="mb-3">
        <form action="?act=nt&amp;id=<?= $id ?>" method="post">
            <button type="submit" class="btn btn-primary"><?= _t('New Topic') ?></button>
        </form>
    </div>
<?php endif; ?>

<?php foreach ($topics as $topic): ?>
    <div class="shadow border-radius-12 forum-section post-item mb-2<?= $topic['deleted'] ? ' deleted-post' : '' ?><?= $topic['closed'] ? ' closed-topic' : '' ?>">
        <div class="section-header">
            <div class="d-flex align-items-center">
                <?php if ($topic['has_icons']): ?>
                    <div class="topic-icons mr-1 d-flex align-items-center">
                        <?php if ($topic['pinned']): ?>
                            <div class="mr-1" title="<?= _t('Pinned topic') ?>">
                                <svg class="icon">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#pin"/>
                                </svg>
                            </div>
                        <?php endif; ?>
                        <?php if ($topic['has_poll']): ?>
                            <div class="mr-1" title="<?= _t('Topic has poll') ?>">
                                <svg class="icon">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#bar-chart"/>
                                </svg>
                            </div>
                        <?php endif; ?>
                        <?php if ($topic['closed']): ?>
                            <div class="mr-1" title="<?= _t('Closed topic') ?>">
                                <svg class="icon">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#lock"/>
                                </svg>
                            </div>
                        <?php endif; ?>
                        <?php if ($topic['deleted']): ?>
                            <div class="mr-1" title="<?= _t('Deleted topic') ?>">
                                <svg class="icon">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#x"/>
                                </svg>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <a href="<?= $topic['url'] ?>" class="text-dark-brown"><?= $topic['name'] ?></a>
                <span class="badge badge-pill badge-light border ml-3"><?= $topic['show_posts_count'] ?></span>
            </div>
        </div>
        <div class="small pt-2 text-muted">
            <?= _t('Author') ?>: <?= $topic['user_name'] ?>,
            <?= _t('Last post') ?>: <?= $topic['show_last_post_date'] ?>, <?= $topic['show_last_author'] ?>
        </div>
    </div>
<?php endforeach; ?>

<div><?= _t('Total') ?>: <?= $total ?></div>
<!-- Page switching -->
<?php if ($total > $user->config->kmess): ?>
    <div class="mt-1"><?= $pagination ?></div>
<?php endif ?>

<?= $this->insert('forum::footer', [
    'online'   => $online,
    'who_url'  => '/forum/?act=who',
    'who_name' => _t('Who in Forum'),
]) ?>

