<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $action_url
 * @var $delete_token
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('Do you really want to delete?') ?>
    </div>
    <div>
        <form action="<?= $action_url ?>" method="post">
            <input type="hidden" name="delete_token" value="<?= $delete_token ?>">
            <button type="submit" name="delete" value="1" class="btn btn-danger btn-sm"><?= __('Delete') ?></button>
            <a href="<?= $back_url ?>" class="btn btn-outline-secondary btn-sm"><?= __('Cancel') ?></a>
        </form>
    </div>
</div>
