<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $action_url
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('Are you sure you want to move the file?') ?>
    </div>
    <div>
        <a href="<?= $action_url ?>" class="btn btn-danger btn-sm"><?= __('Move file') ?></a>
        <a href="<?= $back_url ?>" class="btn btn-outline-secondary btn-sm"><?= __('Cancel') ?></a>
    </div>
</div>
