<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $files
 * @var $buttons
 * @var $urls
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?php if (! $config['mod_down']): ?>
    <div class="alert alert-danger border-0 shadow">
        <?= __('Downloads are closed') ?>
    </div>
<?php endif; ?>

<?php if (empty($users)): ?>
    <div class="alert alert-info"><?= __('List is empty') ?></div>
<?php endif; ?>

<?php foreach ($users as $list_user): ?>
    <?= $this->fetch('downloads::user_row', ['item' => $list_user]) ?>
<?php endforeach; ?>

<div class="mt-3">
    <a href="<?= $urls['downloads'] ?>"><?= __('Downloads') ?></a>
</div>
