<?php
/**
 * @var string $message
 * @var string $max_length
 * @var string $action_url
 * @var string $code
 * @var string $bb_codes
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title ?? $title,
    ]
);
?>

<div class="row">
    <div class="col-md-6">
        <div class="alert alert-danger">
            <div class="pb-2">
                <?= _t('Do you really want to delete?', 'system') ?>
            </div>
            <div>
                <a href="<?= $data['delete_url'] ?>" class="btn btn-danger btn-sm"><?= _t('Delete', 'system') ?></a>
                <a href="<?= $data['clear_url'] ?>" class="btn btn-danger btn-sm"><?= _t('Clear', 'system') ?></a>
                <a href="<?= $data['back_url'] ?>" class="btn btn-primary btn-sm"><?= _t('Cancel', 'system') ?></a>
            </div>
        </div>
    </div>
</div>
