<?php $this->layout('install::layout'); ?>

<h4 class="mb-3">Добро пожаловать в мастер установки JohnCMS.</h4>

<p>
    В процессе установки будет выполнена базовая проверка хостинга на соответствие требованиям CMS. <br>
    Если на этапе установки возникли ошибки и вы не знаете как их решить, вы можете обратиться за помощью на
    <a href="https://johncms.com/forum/" class="text-underline" rel="nofollow" target="_blank">наш форум.</a>
</p>

<h4 class="mb-3">Выберите язык</h4>

<form action="/install/?step=2" method="post" class="mb-3">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3">
        <?php foreach ($data['lng_list'] as $key => $val): ?>
            <div class="col">
                <div class="custom-control custom-radio mb-2">
                    <input type="radio" id="lang_<?= $key ?>" name="lang" class="custom-control-input" value="<?= $key ?>" <?= ($key == $locale ? ' checked="checked"' : '') ?>>
                    <label class="custom-control-label" for="lang_<?= $key ?>">
                        <img src="<?= $this->asset('images/flags/' . strtolower($key) . '.png') ?>" alt=".">
                        <?= $val['name'] ?>
                    </label>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <div class="mt-3">
        <button type="submit" name="submit" value="submit" class="btn btn-primary">Продолжить</button>
    </div>
</form>

<?php $this->push('scripts') ?>
<script>
    $(document).on('change', 'input[name=lang]', function () {
        document.location.href = '/install/?set_locale=' + $(this).val();
    })
</script>
<?php $this->stop(); ?>
