<?php $this->layout('install::layout'); ?>
<p>
    Поздравляем!<br>
    Установка JohnCMS <?= CMS_VERSION ?> завершена успешно.<br>
</p>
<div class="alert alert-danger d-inline-block">
    <b>ВНИМАНИЕ!</b>
    <div>Теперь необходимо удалить папку <b>/install/</b></div>
</div>
<p>
    Если вам потребуется помощь, вы можете обратиться на наш <a href="https://johncms.com/forum/" class="text-underline">форум</a><br>
    Так же при необходимости Вы можете ознакомиться с <a href="https://johncms.com/documentation/" class="text-underline">документацией</a>
</p>
<p>
    <a href="/" class="btn btn-primary">Перейти на сайт</a>
</p>
