<?php $this->layout('install::layout'); ?>

<h4 class="mb-2 mt-3 font-weight-bold">Проверка расширений</h4>
<div>
    <?php foreach ($data['check_extensions'] as $extension): ?>
        <div class="row border-bottom py-2">
            <div class="col-9 col-md-8 font-weight-bold"><?= $extension['name'] ?></div>
            <div class="col-3 col-md-4 font-weight-bold <?= $extension['error'] ? 'text-danger' : 'text-success' ?>">
                <?= $extension['value'] ?>
            </div>
            <?php if ($extension['error']): ?>
                <div class="col-12 text-muted mt-1">
                    <?= $extension['description'] ?>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach ?>
</div>

<h4 class="mb-2 mt-4 font-weight-bold">Проверка прав доступа (chmod)</h4>
<?php if (empty($data['folder_right_errors'])): ?>
    <div class="alert alert-success">Всё в порядке</div>
<?php else: ?>
    <div class="alert alert-danger">
        <?php foreach ($data['folder_right_errors'] as $folder): ?>
            <div class="font-weight-bold"><?= $folder ?></div>
        <?php endforeach; ?>
    </div>
    <div>
        Для указанных директорий необходимо установить права разрешающие запись (777).
    </div>
<?php endif; ?>

<div class="mt-4 mb-2">
    <?php if ($data['next_step_disabled']): ?>
        <button type="button" class="btn btn-primary" disabled>Продолжить</button>
    <?php else: ?>
        <a href="/install/?step=3" class="btn btn-primary">Продолжить</a>
    <?php endif; ?>
</div>
