<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $this Template
 * @var $title
 * @var $page_title
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);

use Mobicms\Render\Template\Template; ?>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped">
            <tr>
                <td class="text-right">[php]...[/php]</td>
                <td><?= _t('PHP code') ?></td>
            </tr>
            <tr>
                <td class="text-right">[url=http://site_url]<span style="color:blue"><?= _t('Link name') ?></span>[/url]</td>
                <td><a href="#"><?= _t('URL Link') ?></a></td>
            </tr>
            <tr>
                <td class="text-right">[b]...[/b]</td>
                <td><b><?= _t('Bold') ?></b></td>
            </tr>
            <tr>
                <td class="text-right">[i]...[/i]</td>
                <td><i><?= _t('Italic') ?></i></td>
            </tr>
            <tr>
                <td class="text-right">[u]...[/u]</td>
                <td><u><?= _t('Underline') ?></u></td>
            </tr>
            <tr>
                <td class="text-right">[s]...[/s]</td>
                <td><strike><?= _t('Strike') ?></strike></td>
            </tr>
            <tr>
                <td class="text-right">[red]...[/red]</td>
                <td><span style="color:red"><?= _t('Red') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[green]...[/green]</td>
                <td><span style="color:green"><?= _t('Green') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[blue]...[/blue]</td>
                <td><span style="color:blue"><?= _t('Blue') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[color=]...[/color]</td>
                <td><?= _t('Text Color') ?></td>
            </tr>
            <tr>
                <td class="text-right">[bg=][/bg]</td>
                <td><?= _t('Background Color') ?></td>
            </tr>
            <tr>
                <td class="text-right">[c]...[/c]</td>
                <td><span class="quote"><?= _t('Quote') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[*]...[/*]</td>
                <td><span class="bblist"><?= _t('Bulleted list') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[spoiler=<?= _t('Title') ?>]<?= _t('Text') ?>[/spoiler]</td>
                <td><?= _t('Spoiler') ?></td>
            </tr>
        </table>
    </div>
</div>

<div class="mt-3">
    <a href="<?= $this->e($_SESSION['ref']) ?>"><?= _t('Back') ?></a>
</div>
