<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var Mobicms\Render\Template\Template $this
 * @var $title
 * @var $page_title
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>
<div class="row">
    <div class="col-md-6">
        <table class="table table-striped">
            <tr>
                <td class="text-right">[php]...[/php]</td>
                <td><?= __('PHP code') ?></td>
            </tr>
            <tr>
                <td class="text-right">[url=http://site_url]<span style="color:blue"><?= __('Link name') ?></span>[/url]</td>
                <td><a href="#"><?= __('URL Link') ?></a></td>
            </tr>
            <tr>
                <td class="text-right">[b]...[/b]</td>
                <td><b><?= __('Bold') ?></b></td>
            </tr>
            <tr>
                <td class="text-right">[i]...[/i]</td>
                <td><i><?= __('Italic') ?></i></td>
            </tr>
            <tr>
                <td class="text-right">[u]...[/u]</td>
                <td><u><?= __('Underline') ?></u></td>
            </tr>
            <tr>
                <td class="text-right">[s]...[/s]</td>
                <td><strike><?= __('Strike') ?></strike></td>
            </tr>
            <tr>
                <td class="text-right">[red]...[/red]</td>
                <td><span style="color:red"><?= __('Red') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[green]...[/green]</td>
                <td><span style="color:green"><?= __('Green') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[blue]...[/blue]</td>
                <td><span style="color:blue"><?= __('Blue') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[color=]...[/color]</td>
                <td><?= __('Text Color') ?></td>
            </tr>
            <tr>
                <td class="text-right">[bg=][/bg]</td>
                <td><?= __('Background Color') ?></td>
            </tr>
            <tr>
                <td class="text-right">[c]...[/c]</td>
                <td><span class="quote"><?= __('Quote') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[*]...[/*]</td>
                <td><span class="bblist"><?= __('Bulleted list') ?></span></td>
            </tr>
            <tr>
                <td class="text-right">[spoiler=<?= __('Title') ?>]<?= __('Text') ?>[/spoiler]</td>
                <td><?= __('Spoiler') ?></td>
            </tr>
        </table>
    </div>
</div>

<div class="mt-3">
    <a href="<?= $this->e($_SESSION['ref']) ?>"><?= __('Back') ?></a>
</div>
