<?php $this->layout('system::layout/old', ['title' => _t('Information, FAQ'), 'homeButton' => true]) ?>
<div class="phdr"><strong><?= _t('Information, FAQ') ?></strong></div>
<div class="menu"><a href="?act=forum"><?= _t('Forum rules') ?></a></div>
<div class="menu"><a href="?act=tags"><?= _t('bbCode Tags') ?></a></div>
<div class="menu"><a href="?act=avatars"><?= _t('Avatars') ?></a></div>
<div class="menu"><a href="?act=smilies"><?= _t('Smilies') ?></a></div>
<div class="phdr"><a href="<?= $_SESSION['ref'] ?>"><?= _t('Back') ?></a></div>
