<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var Mobicms\Render\Template\Template $this
 * @var $title
 * @var $page_title
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>
<div class="row">
    <div class="col-md-6">
        <div class="list-group">
            <a href="?act=forum" class="list-group-item"><?= __('Forum rules') ?></a>
            <a href="?act=tags" class="list-group-item"><?= __('bbCode Tags') ?></a>
            <a href="?act=avatars" class="list-group-item"><?= __('Avatars') ?></a>
            <a href="?act=smilies" class="list-group-item"><?= __('Smilies') ?></a>
        </div>
        <div class="mt-3">
            <a href="<?= $this->e($_SESSION['ref']) ?>"><?= __('Back') ?></a>
        </div>
    </div>
</div>
