<?php $this->layout('system::layout/old_default', ['title' => _t('Community'), 'homeButton' => true]) ?>
<div class="phdr"><strong><?= _t('Community') ?></strong></div>
<div class="gmenu padding">
    <form action="?act=search" method="post">
        <label>
            <strong><?= _t('Look for the User') ?></strong><br>
            <input type="text" name="search">
            <input type="submit" value="<?= _t('Search') ?>" name="submit"><br>
            <small><?= _t('The search is performed by Nickname and are case-insensitive.') ?></small>
        </label>
    </form>
</div>
<div class="menu padding">
    <img src="<?= $this->asset('images/old/contacts.png') ?>" alt="">&nbsp;
    <a href="?act=users"><?= _t('Users') ?></a> (<?= $usersCount ?>)<br>
    <img src="<?= $this->asset('images/old/users.png') ?>" alt="">&nbsp;
    <a href="?act=administration"><?= _t('Administration') ?></a> (<?= $adminCount ?>)<br>
    <?php if ($birthDays): ?>
        <img src="<?= $this->asset('images/old/award.png') ?>" alt="">&nbsp;
        <a href="?act=birthdays"><?= _t('Birthdays') ?></a> (<?= $birthDays ?>)<br>
    <?php endif ?>
    <img src="<?= $this->asset('images/old/photo.gif') ?>" alt="">&nbsp;
    <a href="../album/"><?= _t('Photo Albums') ?></a> (<?= $albumCount ?>)<br>
    <img src="<?= $this->asset('images/old/rate.gif') ?>" alt="">&nbsp;
    <a href="?act=top"><?= _t('Top Activity') ?></a> (<?= $albumCount ?>)
</div>
