<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $label
 * @var string $value
 * @var string $errors
 * @var string $locale
 * @var string $id
 * @var string $name
 */

if (isset($load_scripts) && $load_scripts !== false) {
    if ($locale !== 'en') {
        try {
            echo '<script src="' . $this->asset('ckeditor5/translations/' . $locale . '.js', true) . '"></script>';
        } catch (Exception $exception) {
        }
    }
    ?>
    <script src="<?= $this->asset('ckeditor5/ckeditor.js', true) ?>"></script>
    <?php
}
?>

<div class="vue_app">
    <ckeditor-input-component
        :class="'p-no-margin'"
        upload_url=""
        name="<?= $this->e($name) ?>"
        language="<?= $this->e($locale) ?>"
        errors="<?= $this->e($errors) ?>"
        id="<?= $this->e($id) ?>"
        label="<?= $this->e($label) ?>"
        value="<?= $this->e($value) ?>"
    ></ckeditor-input-component>
</div>
