<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $message
 * @var string $name
 * @var string $form_action
 * @var string $back_url
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<div class="alert alert-warning shadow border-0">
    <?= $this->e($message) ?> «<?= $this->e($name) ?>»
</div>

<form action="<?= $this->e($form_action) ?>" method="post">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
    <button type="submit" class="btn btn-danger"><?= __('Delete') ?></button>
    <a href="<?= $this->e($back_url) ?>" class="btn btn-secondary"><?= __('Cancel') ?></a>
</form>
