<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

declare(strict_types=1);

namespace Johncms\Modules;

use RuntimeException;

/**
 * Reads and writes config/autoload/modules.local.php — what this site has installed and what it
 * has switched off.
 *
 * A file rather than a table, because the list is needed before the container is compiled and
 * long before a database connection exists: the container loads the services of every enabled
 * module, and the router their routes. It is also the thing an administrator locked out by a
 * broken module can fix over FTP.
 *
 * The file is generated. It is read by the config loader as well — it lies among the other
 * autoload files — but this class does not go through it: the registry has to work at a point in
 * the boot where the configuration may not have been assembled yet.
 */
final class ModuleStateStore
{
    /** @var array<string, ModuleStateRecord>|null */
    private ?array $records = null;

    public function __construct(
        private readonly string $file = CONFIG_PATH . 'autoload' . DS . 'modules.local.php',
    ) {
    }

    /**
     * @return array<string, ModuleStateRecord> Keyed by the key of the module.
     */
    public function all(): array
    {
        if ($this->records !== null) {
            return $this->records;
        }

        if (! is_file($this->file)) {
            return $this->records = [];
        }

        /** @psalm-suppress UnresolvableInclude */
        $config = require $this->file;
        $state = is_array($config) ? ($config['modules']['state'] ?? null) : null;

        if (! is_array($state)) {
            return $this->records = [];
        }

        $records = [];
        foreach ($state as $key => $values) {
            if (! is_string($key) || ! is_array($values)) {
                continue;
            }

            $records[$key] = new ModuleStateRecord(
                key: $key,
                alias: is_string($values['alias'] ?? null) ? $values['alias'] : str_replace('/', '.', $key),
                installed: (bool) ($values['installed'] ?? true),
                enabled: (bool) ($values['enabled'] ?? true),
                version: is_string($values['version'] ?? null) ? $values['version'] : null,
                installedAt: is_int($values['installed_at'] ?? null) ? $values['installed_at'] : null,
                // Absent in every file written before unfinished installations were recorded, and
                // in every file of a site where none ever failed.
                installing: (bool) ($values['installing'] ?? false),
            );
        }

        ksort($records);

        return $this->records = $records;
    }

    /**
     * Reads the file again next time. The registry has a store of its own — it is built before the
     * container exists — so when something else writes the state, this one is holding what the
     * file said a moment ago.
     */
    public function forget(): void
    {
        $this->records = null;
    }

    public function find(string $key): ?ModuleStateRecord
    {
        return $this->all()[$key] ?? null;
    }

    /**
     * Writes the whole file at once, through a temporary file in the same directory: a half
     * written state file is a site that loads half of its modules.
     *
     * @param array<string, ModuleStateRecord> $records
     */
    public function save(array $records): void
    {
        ksort($records);

        $lines = [];
        foreach ($records as $record) {
            $lines[] = sprintf('            %s => %s,', $this->value($record->key), $this->export($record));
        }

        $contents = <<<'PHP'
            <?php

            /**
             * The modules this site has installed, and which of them are switched off.
             *
             * Generated by the CMS — "php system/bin/console module:sync" rewrites it. Editing it by
             * hand is allowed and is the way back into a site a module has taken down, but nothing
             * here is remembered anywhere else: a module removed from this file is a module the site
             * no longer loads.
             */

            declare(strict_types=1);

            return [
                'modules' => [
                    'state' => [
            PHP;

        $contents .= "\n" . implode("\n", $lines) . "\n        ],\n    ],\n];\n";

        $directory = dirname($this->file);
        $temporary = tempnam($directory, 'modules-state-');

        if ($temporary === false || file_put_contents($temporary, $contents) === false) {
            throw new RuntimeException(sprintf('Cannot write the module state to "%s".', $this->file));
        }

        chmod($temporary, 0o644);

        if (! rename($temporary, $this->file)) {
            unlink($temporary);
            throw new RuntimeException(sprintf('Cannot replace "%s" with the new module state.', $this->file));
        }

        $this->records = null;
    }

    private function export(ModuleStateRecord $record): string
    {
        $pairs = [];
        foreach ($record->toArray() as $field => $value) {
            $pairs[] = sprintf("'%s' => %s", $field, $this->value($value));
        }

        return '[' . implode(', ', $pairs) . ']';
    }

    /**
     * var_export() writes NULL in capitals, which no coding standard of this project would accept
     * in a file it generates.
     */
    private function value(string|int|bool|null $value): string
    {
        return $value === null ? 'null' : var_export($value, true);
    }
}
