<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var array $data
 * @var array $config
 * @noinspection PhpUnhandledExceptionInspection
 */

$this->layout('system::layout/default');
?>
<form method="post" class="mb-3 mw-750px" action="<?= $data['storeUrl'] ?>" enctype="multipart/form-data">
    <?= $this->fetch(
        'system::forms/simple_form',
        [
            'fields' => $data['formFields'],
            'errors' => $data['validationErrors'],
        ]
    ); ?>
    <div class="mt-3">
        <button type="submit" name="submit" class="btn btn-primary"><?= __('Create') ?></button>
        <a href="<?= $data['backUrl'] ?>" class="btn btn-outline-secondary"><?= __('Back') ?></a>
    </div>
</form>
