<?php
/**
 * @var string $locale
 * @var Johncms\Api\UserInterface $user
 */

?>
<!DOCTYPE html>
<html lang="<?= $locale ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="Generator" content="JohnCMS, https://johncms.com">
    <meta name="keywords" content="<?= $config->meta_key ?>">
    <meta name="description" content="<?= $config->meta_desc ?>">
    <meta name="theme-color" content="#586776">
    <link rel="stylesheet" href="<?= $this->asset('css/app.css', true) ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/magnific-popup.css') ?>">
    <link rel="shortcut icon" href="<?= $this->asset('images/favicon.ico') ?>">
    <link rel="alternate" type="application/rss+xml" title="RSS News" href="<?= $config->homeurl ?>/rss/">
    <title><?= (isset($title) ? $this->e($title) . ' | ' : '') . $config->copyright ?></title>
</head>
<body>
<div class="wrapper justify-content-end d-flex" id="app">
    <div class="sidebar shadow">
        <?php $this->insert('system::app/sidebar') ?>
    </div>
    <div class="content-container content-container-padding">
        <nav class="navbar navbar-expand-lg top_nav fixed-top border-bottom shadow">
            <div class="container-fluid">
                <div class="navbar-wrapper d-flex w-100 justify-content-between">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <div>
                        <?php if ($user->isValid()): ?>
                            <a href="/notifications/" class="icon_with_badge mr-2">
                                <svg class="icon icon_messages">
                                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#messages"/>
                                </svg>
                                <?php if (! empty($notifications['all'])): ?>
                                    <span class="badge badge-danger badge-pill"><?= $notifications['all'] ?></span>
                                <?php endif ?>
                            </a>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <?php if (! empty($page_title)): ?>
                <h1 class="mb-0"><?= $this->e($page_title) ?></h1>
            <?php endif; ?>
            <?php $this->insert('system::app/breadcrumbs'); ?>

            <?= $this->section('content') ?>
        </div>
    </div>
</div>
<div class="modal fade ajax_modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>
<script src="<?= $this->asset('js/app.js', true) ?>"></script>
</body>
</html>
