<?php
/**
 * @var Mobicms\Render\Template\Template $this
 * @var Johncms\Forms\Inputs\Select $field
 */

?>
<div class="form-group">
    <label for="gender"><?= $field->label ?></label>
    <select id="<?= $field->id ?>" name="<?= $field->name ?>" class="form-control <?= (isset($errors[$field->name]) ? 'is-invalid' : '') ?>">
        <?php foreach ($field->options as $option): ?>
            <option value="<?= $option['value'] ?>" <?= $option['value'] === $field->value ? 'selected' : '' ?>><?= $option['name'] ?></option>
        <?php endforeach; ?>
    </select>
    <?php if (isset($errors[$field->name])): ?>
        <div class="invalid-feedback"><?= implode('<br>', $errors[$field->name]) ?></div>
    <?php endif ?>
</div>
