<?php
/**
 * @var Mobicms\Render\Template\Template $this
 * @var Johncms\Forms\Inputs\AbstractInput[] $fields
 * @var array $errors
 * @var string $csrf_token
 * @noinspection PhpUnhandledExceptionInspection
 */

echo '<input type="hidden" name="csrf_token" value="' . $csrf_token . '">';

if (! empty($fields)) {
    foreach ($fields as $field) {
        switch ($field->type) {
            case 'text':
            case 'password':
                echo $this->fetch('system::forms/input_text', ['field' => $field, 'errors' => $errors]);
                break;
            case 'hidden':
                echo $this->fetch('system::forms/input_hidden', ['field' => $field, 'errors' => $errors]);
                break;
            case 'select':
                echo $this->fetch('system::forms/select', ['field' => $field, 'errors' => $errors]);
                break;
            case 'textarea':
                echo $this->fetch('system::forms/textarea', ['field' => $field, 'errors' => $errors]);
                break;
            case 'captcha':
                echo $this->fetch('system::forms/captcha', ['field' => $field, 'errors' => $errors]);
                break;
        }
    }
}
