<?php
$this->layout('system::layout/old', ['title' => _t('Admin Panel'), 'homeButton' => true]);
$cls = ['rmenu', 'menu', 'gmenu', 'menu'];
?>
<div class="phdr"><a href="./"><strong><?= _t('Admin Panel') ?></strong></a> | <?= _t('Permissions') ?></div>
<?php if ($errorMsg): ?>
    <div class="alarm padding">ERROR: Can not write file `system.local.php`</div>
<?php endif ?>
<?php if ($confirmation): ?>
    <div class="menu padding"><?= _t('Settings are saved successfully') ?></div>
<?php endif ?>
<form method="post" action="?act=access">
    <!-- Управление доступом к Форуму -->
    <div class="<?= $cls[$conf['mod_forum']] ?> padding">
        <h3><?= _t('Forum') ?></h3>
        <div style="font-size: x-small">
            <label>
                <input type="radio" value="2" name="forum"<?= ($conf['mod_forum'] == 2 ? ' checked="checked"' : '') ?>>
                <?= _t('Access is allowed') ?>
            </label><br>
            <label>
                <input type="radio" value="1" name="forum"<?= ($conf['mod_forum'] == 1 ? ' checked="checked"' : '') ?>>
                <?= _t('Only for authorized') ?>
            </label><br>
            <label>
                <input type="radio" value="3" name="forum"<?= ($conf['mod_forum'] == 3 ? ' checked="checked"' : '') ?>>
                <?= _t('Read only') ?>
            </label><br>
            <label>
                <input type="radio" value="0" name="forum"<?= (! $conf['mod_forum'] ? ' checked="checked"' : '') ?>>
                <?= _t('Access denied') ?>
            </label>
        </div>
    </div>
    <!-- Управление доступом к Гостевой -->
    <div class="padding <?= $cls[$conf['mod_guest']] ?>">
        <h3><?= _t('Guestbook') ?></h3>
        <div style="font-size: x-small">
            <label>
                <input type="radio" value="2" name="guest"<?= ($conf['mod_guest'] == 2 ? ' checked="checked"' : '') ?>>
                <?= _t('Access is allowed') ?>
            </label><br>
            <label>
                <input type="radio" value="1" name="guest"<?= ($conf['mod_guest'] == 1 ? ' checked="checked"' : '') ?>>
                <?= _t('Only for authorized') ?>
            </label><br>
            <label>
                <input type="radio" value="0" name="guest"<?= (! $conf['mod_guest'] ? ' checked="checked"' : '') ?>>
                <?= _t('Access denied') ?>
            </label>
        </div>
    </div>
    <!-- Управление доступом к Библиотеке -->
    <div class="padding <?= $cls[$conf['mod_lib']] ?>">
        <h3><?= _t('Library') ?></h3>
        <div style="font-size: x-small">
            <label>
                <input type="radio" value="2" name="lib"<?= ($conf['mod_lib'] == 2 ? ' checked="checked"' : '') ?>>
                <?= _t('Access is allowed') ?>
            </label><br>
            <label>
                <input type="radio" value="1" name="lib"<?= ($conf['mod_lib'] == 1 ? ' checked="checked"' : '') ?>>
                <?= _t('Only for authorized') ?>
            </label><br>
            <label>
                <input type="radio" value="0" name="lib"<?= (! $conf['mod_lib'] ? ' checked="checked"' : '') ?>>
                <?= _t('Access denied') ?>
            </label><br>
            <label>
                <input name="libcomm" type="checkbox"
                       value="1"<?= ($conf['mod_lib_comm'] ? ' checked="checked"' : '') ?>>
                <?= _t('Comments') ?>
            </label>
        </div>
    </div>
    <!-- Управление доступом к Загрузкам -->
    <div class="padding <?= $cls[$conf['mod_down']] ?>">
        <h3><?= _t('Downloads') ?></h3>
        <div style="font-size: x-small">
            <label>
                <input type="radio" value="2" name="down"<?= ($conf['mod_down'] == 2 ? ' checked="checked"' : '') ?>>
                <?= _t('Access is allowed') ?>
            </label><br>
            <label>
                <input type="radio" value="1" name="down"<?= ($conf['mod_down'] == 1 ? ' checked="checked"' : '') ?>>
                <?= _t('Only for authorized') ?>
            </label><br>
            <label>
                <input type="radio" value="0" name="down"<?= (! $conf['mod_down'] ? ' checked="checked"' : '') ?>>
                <?= _t('Access denied') ?>
            </label><br>
            <label>
                <input name="downcomm" type="checkbox"
                       value="1"<?= ($conf['mod_down_comm'] ? ' checked="checked"' : '') ?>>
                <?= _t('Comments') ?>
            </label>
        </div>
    </div>
    <!-- Управление доступом к Активу сайта (списки юзеров и т.д.) -->
    <div class="padding <?= $cls[$conf['active'] + 1] ?>">
        <h3><?= _t('Community') ?></h3>
        <div style="font-size: x-small">
            <label>
                <input type="radio" value="1" name="active"<?= ($conf['active'] == 1 ? ' checked="checked"' : '') ?>>
                <?= _t('Access is allowed') ?>
            </label><br>
            <label>
                <input type="radio" value="0" name="active"<?= (! $conf['active'] ? ' checked="checked"' : '') ?>>
                <?= _t('Only for authorized') ?>
            </label>
        </div>
    </div>
    <!-- Управление доступом к Регистрации -->
    <div class="<?= $cls[$conf['mod_reg']] ?> padding">
        <h3><?= _t('Registration') ?></h3>
        <div style="font-size: x-small">
            <label>
                <input type="radio" value="2" name="reg"<?= ($conf['mod_reg'] == 2 ? ' checked="checked"' : '') ?>>
                <?= _t('Access is allowed') ?>
            </label><br>
            <label>
                <input type="radio" value="1" name="reg"<?= ($conf['mod_reg'] == 1 ? ' checked="checked"' : '') ?>>
                <?= _t('With moderation') ?>
            </label><br>
            <label>
                <input type="radio" value="0" name="reg"<?= (! $conf['mod_reg'] ? ' checked="checked"' : '') ?>>
                <?= _t('Access denied') ?>
            </label>
        </div>
    </div>
    <div class="bmenu padding">
        <div style="margin-bottom: 6px; font-size: x-small">
            <?= _t('Administrators always have access to all closed modules and comments') ?>
        </div>
        <input type="submit" name="submit" id="button" value="<?= _t('Save') ?>"/>
    </div>
</form>
