<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var \Johncms\Modules\Admin\Application\DTO\StaffListDTO $data
 */

$this->layout('system::layout/default');
?>

<?php if (empty($data->groups)): ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-info',
            'alert'      => __('The list is empty'),
        ]
    ) ?>
<?php endif; ?>

<?php foreach ($data->groups as $group): ?>
    <h2><?= $this->e($group->name) ?></h2>
    <?php foreach ($group->items as $item): ?>
        <?= $this->fetch('admin::user_row', ['item' => $item]) ?>
    <?php endforeach; ?>
<?php endforeach; ?>

<div class="mt-4">
    <?php if ($data->total > 0): ?>
        <div><?= __('Total:') ?> <?= $data->total ?></div>
    <?php endif; ?>
</div>
<div>
    <a href="/admin"><?= __('Back') ?></a>
</div>
