<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $title,
    ]
);
?>

<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-12 col-md-8 col-lg-7 col-xl-7">
        <div class="card shadow border-0">
            <form action="?mod=amnesty" method="post">
                <div class="card-body">
                    <div class="custom-control custom-radio">
                        <input type="radio" id="term1" name="term" value="0" class="custom-control-input" checked>
                        <label class="custom-control-label" for="term1"><?= __('Unban all') ?></label>
                    </div>
                    <div class="custom-control custom-radio">
                        <input type="radio" id="term2" name="term" value="1" class="custom-control-input">
                        <label class="custom-control-label" for="term2"><?= __('Clear Ban database') ?></label>
                    </div>

                    <div class="alert alert-info mt-3">
                        <?= __('&quot;Unban All&quot; - terminating all active bans<br>&quot;Clear Database&quot; - terminates all bans and clears an offenses history') ?>
                    </div>

                    <div class="mt-3">
                        <input type="submit" name="submit" value="<?= __('Save') ?>" class="btn btn-primary"/>
                        <a href="?act=office" class="btn btn-secondary"><?= __('Cancel') ?></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
