<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $form_action
 * @var string $back_url
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('WARNING!!!<br>Before continuing make sure that all the files have been identified in the scanning mode distribution reliable and contain no unauthorized modifications.') ?>
    </div>
</div>
<div class="text-muted mb-3 alert alert-info">
    <?= __('This procedure creates a list of all script files to your site, calculates the checksums and writes to the database, for later comparison.') ?>
</div>
<div>
    <form action="<?= $this->e($form_action) ?>" method="post">
        <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
        <button type="submit" class="btn btn-danger"><?= __('Create snapshot') ?></button>
        <a href="<?= $this->e($back_url) ?>" class="btn btn-outline-secondary"><?= __('Cancel') ?></a>
    </form>
</div>
