<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var array<string, int> $set_af
 * @var string $form_action
 * @var string|null $error_message
 * @var string|null $success_message
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>
<?php if (! empty($error_message)): ?>
    <div class="alert alert-danger shadow border-0"><?= $this->e($error_message) ?></div>
<?php endif ?>
<?php if (! empty($success_message)): ?>
    <div class="alert alert-success shadow border-0"><?= $this->e($success_message) ?></div>
<?php endif ?>
<form action="<?= $this->e($form_action) ?>" method="post">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
    <h3><?= __('Operation mode') ?></h3>

    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" name="mode" value="3" id="mode3" <?= $set_af['mode'] === 3 ? 'checked' : '' ?>>
        <label class="custom-control-label" for="mode3"><?= __('Day') ?></label>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" name="mode" value="4" id="mode4" <?= $set_af['mode'] === 4 ? 'checked' : '' ?>>
        <label class="custom-control-label" for="mode4"><?= __('Night') ?></label>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" name="mode" value="2" id="mode2" <?= $set_af['mode'] === 2 ? 'checked' : '' ?>>
        <label class="custom-control-label" for="mode2"><?= __('Day / Night') ?></label>
        <div class="text-muted small"><?= __('Automatic change from day to night mode, according to specified time set') ?></div>
    </div>
    <div class="custom-control custom-radio">
        <input type="radio" class="custom-control-input" name="mode" value="1" id="mode1" <?= $set_af['mode'] === 1 ? 'checked' : '' ?>>
        <label class="custom-control-label" for="mode1"><?= __('Adaptive') ?></label>
        <div class="text-muted small"><?= __('If one of administration is online (on the site), the system work in &quot;day&quot; mode, if administration is offline, it switch to &quot;night&quot;') ?></div>
    </div>

    <h3 class="mt-3"><?= __('Time limit') ?></h3>
    <div class="form-group">
        <label for="day"><?= __('Day') ?></label>
        <input type="text" name="day" class="form-control" id="day" value="<?= $set_af['day'] ?>">
    </div>
    <div class="form-group">
        <label for="night"><?= __('Night') ?></label>
        <input type="text" name="night" class="form-control" id="night" value="<?= $set_af['night'] ?>">
    </div>
    <h3 class="mt-3"><?= __('Day mode') ?></h3>
    <div class="form-group">
        <label for="dayfrom"><?= __('Beginning of day') ?></label>
        <input type="text" name="dayfrom" class="form-control" id="dayfrom" value="<?= $set_af['dayfrom'] ?>">
    </div>
    <div class="form-group">
        <label for="dayto"><?= __('End of day') ?></label>
        <input type="text" name="dayto" class="form-control" id="dayto" value="<?= $set_af['dayto'] ?>">
    </div>
    <div class="mt-3">
        <input type="submit" name="submit" value="<?= __('Save') ?>" class="btn btn-primary"/>
        <a href="/admin/" class="btn btn-secondary"><?= __('Cancel') ?></a>
    </div>
</form>
