<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['sec_menu' => ['antispy' => true]]));
?>

<h3><?= __('Scan mode') ?></h3>
<div class="list-group">
    <a href="?mod=snapscan" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h4 class="mb-1 font-weight-bold"><?= __('Snapshot scan') ?></h4>
        </div>
        <p class="mb-1"><?= __('Compare the list of files and checksums with pre-made way. Allows you to identify unknow files, and unauthorized changes.') ?></p>
    </a>
    <a href="?mod=snap" class="list-group-item list-group-item-action">
        <div class="d-flex w-100 justify-content-between">
            <h4 class="mb-1 font-weight-bold"><?= __('Create snapshot') ?></h4>
        </div>
        <p class="mb-1"><?= __('Takes a snapshot of all script files from the site calculates their checksums and stored in the database.') ?></p>
    </a>
</div>
