<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $form_action
 * @var string $name
 * @var string $counter_1
 * @var string $counter_2
 * @var int $mode
 * @var bool $require_cookie_consent
 * @var bool $enabled
 * @var int|null $id
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-12 col-md-8 col-lg-7 col-xl-7">
        <div class="card shadow border-0">
            <form action="<?= $this->e($form_action) ?>" method="post">
                <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
                <div class="card-body">
                    <h3 class="mb-0"><?= __('Title') ?></h3>
                    <div><?= $this->e($name) ?></div>

                    <h3 class="mb-0 mt-2"><?= __('Option 1') ?></h3>
                    <div><?= $counter_1 ?></div>

                    <h3 class="mb-0 mt-2"><?= __('Option 2') ?></h3>
                    <div class="mb-2"><?= $counter_2 ?></div>

                    <input type="hidden" value="<?= $this->e($name) ?>" name="name">
                    <input type="hidden" value="<?= $this->e($counter_1) ?>" name="link1">
                    <input type="hidden" value="<?= $this->e($counter_2) ?>" name="link2">
                    <input type="hidden" value="<?= $mode ?>" name="mode">
                    <?php if ($enabled): ?>
                        <input type="hidden" value="1" name="switch">
                    <?php endif; ?>
                    <?php if ($require_cookie_consent): ?>
                        <input type="hidden" value="1" name="require_cookie_consent">
                    <?php endif; ?>
                    <?php if (! empty($id)): ?>
                        <input type="hidden" value="<?= $id ?>" name="id">
                    <?php endif; ?>

                    <div class="alert alert-info">
                        <?= __('If the counter are displayed correctly and without errors, click &quot;Save&quot;.<br>Otherwise, click back button and correct errors.') ?>
                    </div>

                    <div class="mt-3">
                        <input type="submit" value="<?= __('Save') ?>" class="btn btn-danger"/>
                        <a href="/admin/counters" class="btn btn-secondary"><?= __('Cancel') ?></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
