<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $form_action
 * @var string|null $error_message
 * @var string|null $success_message
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>
<?php if (! empty($error_message)): ?>
    <div class="alert alert-danger shadow border-0"><?= $this->e($error_message) ?></div>
<?php endif ?>
<?php if (! empty($success_message)): ?>
    <div class="alert alert-success shadow border-0"><?= $this->e($success_message) ?></div>
<?php endif ?>

<div class="alert alert-info">
    <?= __('Rebuild the smilies cache after adding or removing smilies in the assets/emoticons directory') ?>
</div>

<form method="post" action="<?= $this->e($form_action) ?>">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
    <input type="submit" value="<?= __('Update cache') ?>" class="btn btn-primary">
    <a href="/admin/" class="btn btn-secondary"><?= __('Cancel') ?></a>
</form>
