<?php

/**
 * @var bool $confirmation
 * @var array $sysconf
 * @var array $themelist
 */
$this->layout('system::layout/default', ['title' => __('Admin Panel'), 'page_title' => 'Главная страница']);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['sys_menu' => ['settings' => true]]));
$homepage_config = di('config')['homepage'];
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['module_menu' => ['homepage' => true]]));
?>

<div style="max-width: 640px">
    <?php if ($confirmation): ?>
        <div class="alert alert-success shadow" role="alert">
            <?= __('Settings are saved successfully') ?>
        </div>
    <?php endif ?>
<form method="post">
        <fieldset>
            <legend>Настройки главной страницы</legend>
            <div class="form-group">
                <label for="last_themes">Сколько выводить активных тем</label>
                <input type="text" id="last_themes" name="last_themes" class="form-control  col-sm-2" value="<?= (int) ($homepage_config['last_themes']) ?>"/>
            </div>
            <div class="form-group">
                <label for="last_files">Сколько выводить новых файлов</label>
                <input type="text" id="last_files" name="last_files" class="form-control  col-sm-2" value="<?= (int) ($homepage_config['last_files']) ?>"/>
            </div>
            <div class="form-group">
                <label for="last_lib">Сколько выводить свежих статей</label>
                <input type="text" id="last_lib" name="last_lib" class="form-control  col-sm-2" value="<?= (int) ($homepage_config['last_lib']) ?>"/>
            </div>
        </fieldset>
        <input type="submit" class="btn btn-primary btn-lg mt-4 mb-2" name="submit" value="<?= __('Save') ?>"/>
    </form>
    <p>
        Что бы убрать вывод не нужного модуля укажите в его форме 0
    </p>
</div>