<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $form_action
 * @var string $mode_name
 * @var string $mode_value
 * @var string $ban_type_label
 * @var string $ban_url
 * @var string $reason_display
 * @var int $ip1
 * @var int $ip2
 * @var int $term
 * @var string $url
 * @var string $reason
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<form action="<?= $this->e($form_action) ?>" method="post">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
    <h3 class="mb-0"><?= __('Ban mode') ?></h3>
    <div><?= $this->e($mode_name) ?> - <b><?= $this->e($mode_value) ?></b></div>

    <h3 class="mb-0 mt-2"><?= __('Ban type') ?></h3>
    <div><?= $this->e($ban_type_label) ?></div>
    <?php if (! empty($ban_url)): ?>
        <div><?= __('Redirect URL:') ?> <?= $this->e($ban_url) ?></div>
    <?php endif; ?>
    <h3 class="mb-0 mt-2"><?= __('Reason') ?></h3>
    <div class="mb-2"><?= $this->e($reason_display) ?></div>

    <input type="hidden" value="<?= $ip1 ?>" name="ip1">
    <input type="hidden" value="<?= $ip2 ?>" name="ip2">
    <input type="hidden" value="<?= $term ?>" name="term">
    <input type="hidden" value="<?= $this->e($url) ?>" name="url">
    <input type="hidden" value="<?= $this->e($reason) ?>" name="reason">

    <div class="alert alert-info">
        <?= __('Please, check up correctness of the input data') ?>
    </div>

    <div class="mt-3">
        <input type="submit" value="<?= __('Add Ban') ?>" class="btn btn-danger"/>
        <a href="/admin/ip-bans" class="btn btn-secondary"><?= __('Cancel') ?></a>
    </div>
</form>
