<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var string $ips
 * @var string $ban_type
 * @var string $link
 * @var string $reason
 * @var string $who
 * @var string $display_date
 * @var string $display_time
 * @var string $delete_url
 * @var string $back_url
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>

<div class="row">
    <div class="col-md-6">
        <div class="card border-0 shadow">
            <div class="card-body">
                <h3 class="mb-3"><?= $this->e($ips) ?></h3>
                <div>
                    <span class="text-muted"><?= __('Ban type:') ?></span> <b><?= $this->e($ban_type) ?></b>
                </div>
                <?php if (! empty($link)): ?>
                    <div>
                        <span class="text-muted"><?= __('Redirect to:') ?></span> <?= $this->e($link) ?>
                    </div>
                <?php endif; ?>
                <div>
                    <span class="text-muted"><?= __('Reason:') ?></span> <?= $this->e($reason) ?>
                </div>
                <div>
                    <span class="text-muted"><?= __('Banned by:') ?></span> <?= $this->e($who) ?>
                </div>
                <div>
                    <span class="text-muted"><?= __('Date:') ?></span> <?= $this->e($display_date) ?>
                </div>
                <div>
                    <span class="text-muted"><?= __('Time:') ?></span> <?= $this->e($display_time) ?>
                </div>
                <div class="mt-3">
                    <form action="<?= $this->e($delete_url) ?>" method="post">
                        <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
                        <button type="submit" class="btn btn-danger"><?= __('Delete Ban') ?></button>
                    </form>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <a href="<?= $this->e($back_url) ?>"><?= __('Back') ?></a>
        </div>
    </div>
</div>
