<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['sec_menu' => ['ipban' => true]]));
?>

<div class="row">
    <div class="col-md-6">
        <div class="card border-0 shadow">
            <div class="card-body">
                <h3 class="mb-3"><?= $data['ban_info']['ips'] ?></h3>
                <div>
                    <span class="text-muted"><?= __('Ban type:') ?></span> <b><?= $data['ban_info']['ban_type'] ?></b>
                </div>
                <?php if (! empty($data['ban_info']['link'])): ?>
                    <div>
                        <span class="text-muted"><?= __('Redirect to:') ?></span> <?= $data['ban_info']['link'] ?>
                    </div>
                <?php endif; ?>
                <div>
                    <span class="text-muted"><?= __('Reason:') ?></span> <?= $data['ban_info']['reason'] ?>
                </div>
                <div>
                    <span class="text-muted"><?= __('Banned by:') ?></span> <?= $data['ban_info']['who'] ?>
                </div>
                <div>
                    <span class="text-muted"><?= __('Date:') ?></span> <?= $data['ban_info']['display_date'] ?>
                </div>
                <div>
                    <span class="text-muted"><?= __('Time:') ?></span> <?= $data['ban_info']['display_time'] ?>
                </div>
                <div class="mt-3">
                    <a href="<?= $data['delete_url'] ?>" class="btn btn-danger"><?= __('Delete Ban') ?></a>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <a href="/admin/ipban/"><?= __('Back') ?></a>
        </div>

    </div>
</div>
