<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $title,
    ]
);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['sec_menu' => ['ipban' => true]]));
?>

<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-12 col-md-8 col-lg-7 col-xl-7">
        <div class="card shadow border-0">
            <form action="?mod=detail" method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label for="ip"><?= __('IP address') ?></label>
                        <input type="text" name="ip" class="form-control" id="ip" placeholder="<?= __('IP address') ?>">
                    </div>
                    <div class="alert alert-info">
                        <?= __('Enter a single address, mask and range are not allowed') ?>
                    </div>
                    <div class="mt-3">
                        <input type="submit" name="submit" value="<?= __('Search') ?>" class="btn btn-primary"/>
                        <a href="/admin/ipban/" class="btn btn-secondary"><?= __('Cancel') ?></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
