<?php

/**
 * @var bool $confirmation
 * @var array $sysconf
 * @var array $themelist
 */
$this->layout('system::layout/default', ['title' => _t('Admin Panel'), 'page_title' => _t('System Settings')]);
$this->sectionReplace('sidebar-menu', $this->fetch('admin::sidebar-admin-menu', ['showSystemMenu' => true]));
?>

<div style="max-width: 640px">
    <?php if ($confirmation): ?>
        <div class="alert alert-success shadow" role="alert">
            <?= _t('Settings are saved successfully') ?>
        </div>
    <?php endif ?>

    <form method="post">
        <fieldset>
            <legend><?= _t('Common Settings') ?></legend>
            <div class="form-group">
                <label for="homeurl"><?= _t('Web site address without the slash at the end') ?></label>
                <input type="text" id="homeurl" name="homeurl" class="form-control" value="<?= $this->e($sysconf['homeurl']) ?>"/>
            </div>
            <div class="form-group">
                <label for="copyright"><?= _t('Site copyright') ?></label>
                <input type="text" id="copyright" name="copyright" class="form-control" value="<?= $this->e($sysconf['copyright']) ?>"/>
            </div>
            <div class="form-group">
                <label for="madm"><?= _t('Site Email') ?></label>
                <input type="text" id="madm" name="madm" maxlength="50" class="form-control" value="<?= $this->e($sysconf['email']) ?>"/>
            </div>
            <div class="form-group">
                <label for="flsz"><?= _t('Max. file size') ?> (kb)</label>
                <input type="text" id="flsz" name="flsz" class="form-control  col-sm-2" value="<?= (int) ($sysconf['flsz']) ?>"/>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gz" name="gz" value="1" <?= ($sysconf['gzip'] ? 'checked="checked"' : '') ?>>
                <label class="form-check-label" for="gz"><?= _t('Gzip compression') ?></label>
            </div>
        </fieldset>
        <fieldset class="mt-3">
            <legend><?= _t('Time shift') ?></legend>
            <div class="form-group">
                <label for="timeshift">+ - 12 Hour</label>
                <input type="text" id="timeshift" name="timeshift" class="form-control  col-sm-2" value="<?= (int) ($sysconf['timeshift']) ?>"/>
            </div>
            <div class="form-group">
                <span style="font-weight:bold; background-color:#C0FFC0"> <?= date('H:i', time() + $sysconf['timeshift'] * 3600) ?> </span>&nbsp;<?= _t('System Time') ?><br>
                <span style="font-weight:bold; background-color:#FFC0C0"> <?= date('H:i') ?> </span>&nbsp;UTC
            </div>
        </fieldset>
        <fieldset class="mt-3">
            <legend><?= _t('META tags') ?></legend>
            <div class="form-group">
                <label for="meta_key"><?= _t('Keywords') ?></label>
                <textarea rows="<?= $user->config->fieldHeight ?>" id="meta_key" name="meta_key" class="form-control"><?= $this->e($sysconf['meta_key']) ?></textarea>
            </div>
            <div class="form-group">
                <label for="meta_desc"><?= _t('Description') ?></label>
                <textarea rows="<?= $user->config->fieldHeight ?>" id="meta_desc" name="meta_desc" class="form-control"><?= $this->e($sysconf['meta_desc']) ?></textarea>
            </div>
        </fieldset>
        <fieldset class="mt-3">
            <legend><?= _t('Themes') ?></legend>
            <select id="skindef" name="skindef" class="form-control">
                <?php foreach ($themelist as $theme): ?>
                    <option <?= ($sysconf['skindef'] == $theme ? ' selected="selected"' : '') ?>><?= $theme ?></option>
                <?php endforeach ?>
            </select>
        </fieldset>
        <input type="submit" class="btn btn-primary btn-lg mt-4 mb-2" name="submit" value="<?= _t('Save') ?>"/>
    </form>
</div>
