<?php
/**
 * @var int $bantotal
 * @var int $countadm
 * @var int $countusers
 * @var string $locale
 * @var int $regtotal
 * @var Johncms\System\Utility\Tools $tools
 * @var Johncms\System\Users\User $user
 */

/** @var \Johncms\Utility\Counters $counters */
$counters = $container->get('counters');
$forum_counters = $counters->forumCounters();
$guestbook_counters = $counters->guestbookCounters();
$downloads_counters = $counters->downloadsCounters();
$library_counters = $counters->libraryCounters();
$users_counters = $counters->usersCounters();
$album_counters = $counters->albumCounters();
$news_counters = $counters->news();
$showUsers = isset($showUsersMenu) ? ' show' : '';
$showModules = isset($showModulesMenu) ? ' show' : '';
$showSystem = isset($showSystemMenu) ? ' show' : '';
$showSecurity = isset($showSecurityMenu) ? ' show' : '';
?>
<div style="background-color: #bd0719; height: 5px">&nbsp;</div>

<div class="accordion flex-grow-1" id="accordionAdmin">
    <!-- Users Button -->
    <a class="nav-link user__link" href="#" data-toggle="collapse" data-target="#collapseUsers" aria-expanded="false">
        <div class="nav__vertical pt-2 pb-2 text-danger">
            <svg class="icon">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#users"/>
            </svg>
            <span class="flex-grow-1"><?= _t('Users') ?></span>
            <?php if ($regtotal): ?>
                <div class="badge badge-danger badge-pill ml-2">+&nbsp;<?= $regtotal ?></div>
            <?php endif ?>
        </div>
        <div>
            <svg class="icon icon-chevron-bottom">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
            </svg>
        </div>
    </a>
    <!-- Users Slider -->
    <div id="collapseUsers" class="collapse<?= $showUsers ?>" data-parent="#accordionAdmin">
        <div class="border-bottom"></div>
        <ul class="nav nav__vertical" style="background-color: rgba(230, 230, 230, 0.2)">
            <li>
                <a href="<?= $config->homeurl ?>/admin/search_ip/">
                    <svg class="icon text-info">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#search"/>
                    </svg>
                    <span class="flex-grow-1 text-info"><?= _t('Search') ?></span>
                </a>
            </li>
            <?php if ($regtotal): ?>
                <li>
                    <a href="<?= $config->homeurl ?>/admin/reg/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#help-circle"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('On registration') ?></span>
                        <span class="badge badge-pill badge-danger"><?= $tools->formatNumber($regtotal) ?></span>
                    </a>
                </li>
            <?php endif ?>
            <li>
                <a href="<?= $config->homeurl ?>/admin/userlist/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#users"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Users') ?></span>
                    <span class="badge badge-pill badge-light"><?= $tools->formatNumber($countusers) ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/adminlist/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Administration') ?></span>
                    <span class="badge badge-pill badge-light"><?= $tools->formatNumber($countadm) ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/ban_panel/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#slash"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Ban Panel') ?></span>
                    <span class="badge badge-pill badge-light"><?= $tools->formatNumber($bantotal) ?></span>
                </a>
            </li>
            <?php if ($user->rights === 9): ?>
                <li>
                    <a href="<?= $config->homeurl ?>/admin/usr_clean/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#database"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Database cleanup') ?></span>
                    </a>
                </li>
                <li>
                    <a href="<?= $config->homeurl ?>/admin/antiflood/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#bell-off"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Antiflood') ?></span>
                    </a>
                </li>
                <li>
                    <a href="<?= $config->homeurl ?>/admin/karma/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Karma') ?></span>
                    </a>
                </li>
            <?php endif ?>
        </ul>
    </div>
    <div class="border-bottom"></div>

    <!-- Modules Button -->
    <a class="nav-link user__link" href="#" data-toggle="collapse" data-target="#collapseModules" aria-expanded="false">
        <div class="nav__vertical pt-2 pb-2 text-danger">
            <svg class="icon">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#shopping-cart"/>
            </svg>
            <span class="flex-grow-1"><?= _t('Modules') ?></span>
        </div>
        <div>
            <svg class="icon icon-chevron-bottom">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
            </svg>
        </div>
    </a>
    <!-- Modules Slider -->
    <div id="collapseModules" class="collapse<?= $showModules ?>" data-parent="#accordionAdmin">
        <div class="border-bottom"></div>
        <ul class="nav nav__vertical" style="background-color: rgba(230, 230, 230, 0.2)">
            <li>
                <a href="<?= $config->homeurl ?>/admin/forum/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Forum') ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/news/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#book"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('News') ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/ads/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#shopping-cart"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Advertisement') ?></span>
                </a>
            </li>
            <?php if ($user->rights == 9): ?>
                <li>
                    <a href="<?= $config->homeurl ?>/admin/counters/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#pie-chart"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Counters') ?></span>
                    </a>
                </li>
            <?php endif ?>
        </ul>
    </div>
    <div class="border-bottom"></div>

    <!-- System Button -->
    <a class="nav-link user__link" href="#" data-toggle="collapse" data-target="#collapseSystem" aria-expanded="false">
        <div class="nav__vertical pt-2 pb-2 text-danger">
            <svg class="icon">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#settings"/>
            </svg>
            <span class="flex-grow-1"><?= _t('System') ?></span>
        </div>
        <div>
            <svg class="icon icon-chevron-bottom">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
            </svg>
        </div>
    </a>
    <!-- System Slider -->
    <div id="collapseSystem" class="collapse<?= $showSystem ?>" data-parent="#accordionAdmin">
        <div class="border-bottom"></div>
        <ul class="nav nav__vertical" style="background-color: rgba(230, 230, 230, 0.2)">
            <li>
                <a href="<?= $config->homeurl ?>/admin/settings/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#settings"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('System Settings') ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/smilies/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#smile"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Update Smilies') ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/languages/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Language Settings') ?></span>
                </a>
            </li>
        </ul>
    </div>
    <div class="border-bottom"></div>

    <!-- Security Button -->
    <a class="nav-link user__link" href="#" data-toggle="collapse" data-target="#collapseSecurity" aria-expanded="false">
        <div class="nav__vertical pt-2 pb-2 text-danger">
            <svg class="icon">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#shield"/>
            </svg>
            <span class="flex-grow-1"><?= _t('Security') ?></span>
        </div>
        <div>
            <svg class="icon icon-chevron-bottom">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
            </svg>
        </div>
    </a>
    <!-- Security Slider -->
    <div id="collapseSecurity" class="collapse<?= $showSecurity ?>" data-parent="#accordionAdmin">
        <div class="border-bottom"></div>
        <ul class="nav nav__vertical" style="background-color: rgba(230, 230, 230, 0.2)">
            <li>
                <a href="<?= $config->homeurl ?>/admin/antispy/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#check"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Anti-Spyware') ?></span>
                </a>
            </li>
            <li>
                <a href="<?= $config->homeurl ?>/admin/ipban/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#slash"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Ban by IP') ?></span>
                </a>
            </li>
        </ul>
    </div>
    <div class="border-bottom"></div>
</div>

<!-- Footer -->
<div class="sidebar__footer">
    <div>
        <a href="/online/">
            <svg class="icon sidebar_online">
                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
            </svg>
            <?= $container->get('counters')->online() ?>
        </a>
    </div>

    <?php if (count($config->lng_list) > 1): ?>
        <div class="mt-1">
            <button class="btn btn-link pl-0" data-url="/language/" data-toggle="modal" data-target=".ajax_modal">
                <img src="<?= $this->asset('images/flags/' . strtolower($locale) . '.png') ?>" alt="<?= $locale ?>">
                <?= $config['lng_list'][$locale] ?>
            </button>
        </div>
    <?php endif ?>
</div>
