<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var int $total
 * @var string $form_action
 * @var string|null $error_message
 * @var string|null $success_message
 * @var string $csrf_token
 */

$this->layout('system::layout/default');
?>
<?php if (! empty($error_message)): ?>
    <div class="alert alert-danger shadow border-0"><?= $this->e($error_message) ?></div>
<?php endif ?>
<?php if (! empty($success_message)): ?>
    <div class="alert alert-success shadow border-0"><?= $this->e($success_message) ?></div>
<?php endif ?>

<div class="alert alert-danger">
    <div class="pb-2">
        <?= __('This category includes profiles, recorded more than 6 months ago, with the date of last visit for more than 5 months ago and with zero activity.<br>Can safely remove them.') ?>
        <div>
            <?= __('Total') ?>: <b><?= $total ?></b>
        </div>
    </div>
    <div>
        <form action="<?= $this->e($form_action) ?>" method="post">
            <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
            <button type="submit" class="btn btn-danger" <?= $total > 0 ? '' : 'disabled' ?>><?= __('Delete') ?></button>
            <a href="/admin/" class="btn btn-outline-secondary"><?= __('Cancel') ?></a>
        </form>
    </div>
</div>
