<?php $this->layout(
    'system::layout/default',
    [
        'title'      => __('Clear news'),
        'page_title' => __('Clear news'),
    ]
) ?>

<div>
    <h4><?= __('Clear news') ?></h4>
    <form action="/news/clean/" method="post">
        <p><?= __('Clearing parameters') ?></p>
        <div class="custom-control custom-radio">
            <input type="radio" id="month" name="cl" value="0" class="custom-control-input">
            <label class="custom-control-label" for="month"><?= __('Older than 1 month') ?></label>
        </div>
        <div class="custom-control custom-radio">
            <input type="radio" id="week" name="cl" value="1" class="custom-control-input">
            <label class="custom-control-label" for="week"><?= __('Older than 1 week') ?></label>
        </div>
        <div class="custom-control custom-radio">
            <input type="radio" id="all" name="cl" value="2" class="custom-control-input">
            <label class="custom-control-label" for="all"><?= __('Clear all') ?></label>
        </div>
        <div class="mt-3">
            <button type="submit" class="btn btn-primary"><?= __('Clear') ?></button>
            <a href="/news/" class="btn btn-outline-primary ml-2"><?= __('Cancel') ?></a>
        </div>
    </form>
</div>
