<?php $this->layout('system::layout/default', [
    'title'      => _t('News'),
    'page_title' => _t('News'),
]) ?>
<?php if ($user->rights >= 6): ?>
    <p>
        <a href="add" class="btn btn-primary mr-2"><?= _t('Add') ?></a>
        <a href="clean" class="btn btn-danger"><?= _t('Clear') ?></a>
    </p>
<?php endif ?>
<!-- Listing News -->
<?php foreach ($list() as $news): ?>
    <div class="card mb-3 shadow border-0">
        <div class="card-body">
            <h3 class="card-title"><?= $this->e($news['name']) ?></h3>
            <p class="card-text"><?= $news['text'] ?></p>
            <p class="card-text">
                <small class="text-muted"><?= _t('Author') ?>: <?= $news['avt'] ?> (<?= $tools->displayDate($news['time']) ?>)</small>
            </p>
            <?php if (! empty($news['kom']) || $user->rights >= 6): ?>
                <div class="border-top pt-3 d-flex justify-content-between">
                    <div>
                        <?php if (! empty($news['kom'])): ?>
                            <!-- Forum discussion -->
                            <a href="/forum/?type=topic&id=<?= $news['kom'] ?>">
                                <?= _t('Discuss in Forum') ?> (<?= $news['kom_count'] ?>)
                            </a>
                        <?php endif ?>
                    </div>
                    <?php if ($user->rights >= 6): ?>
                        <!-- Buttons for deleting and changing news -->
                        <div>
                            <a href="/news/edit?id=<?= $news['id'] ?>" class="btn btn-primary btn-sm"><?= _t('Edit') ?></a>
                            <a href="/news/del?id=<?= $news['id'] ?>" class="btn btn-danger btn-sm"><?= _t('Delete') ?></a>
                        </div>
                    <?php endif ?>
                </div>
            <?php endif ?>
        </div>
    </div>
<?php endforeach ?>
<div class="pt-2 pb-2"><?= _t('Total') ?>:&#160;<?= $total ?></div>
<!-- Page switching -->
<?php if ($total > $user->config->kmess): ?>
    <div><?= $pagination ?></div>
<?php endif ?>

