<?php

/**
 * @var Mobicms\Render\Template\Template $this
 * @var array $data
 */

$this->layout('system::layout/default');

?>

<div class="row">
    <div class="col-md-6">
        <form method="post" class="mb-3" action="<?= $data['storeUrl'] ?>">
            <?php if (! empty($data['authError'])): ?>
                <?= $this->fetch('system::app/alert', ['alert_type' => 'alert-danger', 'alert' => $data['authError']]) ?>
            <?php endif ?>

            <?= $this->fetch(
                'system::forms/simple_form',
                [
                    'fields' => $data['formFields'],
                    'errors' => $data['validationErrors'],
                ]
            ); ?>
            <div class="mt-3">
                <button type="submit" name="submit" class="btn btn-primary me-1"><?= __('Add') ?></button>
                <a href="<?= route('admin.modules') ?>" class="btn btn-outline-secondary"><?= __('Back') ?></a>
            </div>
        </form>
    </div>
</div>



