<?php
/**
 * @var string $label
 * @var string $value
 * @var string $errors
 * @var string $locale
 * @var string $name
 * @var string $upload_url
 */

if ($locale !== 'en') {
    try {
        echo '<script src="' . $this->asset('ckeditor5/translations/' . $locale . '.js', true) . '"></script>';
    } catch (Exception $exception) {
    }
}
?>
<script src="<?= $this->asset('ckeditor5/ckeditor.js', true) ?>"></script>
<div class="vue_app">
    <ckeditor-input-component
        upload_url="<?= $this->e($upload_url ?? '') ?>"
        name="<?= $name ?>"
        language="<?= $locale ?>"
        errors="<?= $errors ?>"
        id="<?= $name ?>"
        label="<?= $label ?>"
        value="<?= $this->e($value) ?>"
        :allow_upload="<?= (! isset($allow_upload) || $allow_upload ? 'true' : 'false'); ?>"
    ></ckeditor-input-component>
</div>
