<?php
/**
 * @var string $locale
 * @var Johncms\Api\ToolsInterface $tools
 * @var Johncms\Api\UserInterface $user
 */

/** @var \Johncms\Utility\Counters $counters */
$counters = $container->get('counters');
$notifications = $counters->notifications();
$forum_counters = $counters->forumCounters();
$guestbook_counters = $counters->guestbookCounters();
$downloads_counters = $counters->downloadsCounters();
$library_counters = $counters->libraryCounters();
$users_counters = $counters->usersCounters();
$album_counters = $counters->albumCounters();
$news_counters = $counters->news();
$user_avatar = $user->getAvatar();
?>
<div class="sidebar__logo">
    <a href="/">
        <span class="logo__image"><img src="<?= $this->asset('images/logo.svg') ?>" alt="logo" style="width: 70%;" class="img-fluid"></span>
    </a>
</div>
<div class="sidebar__wrapper d-flex flex-column">
    <!-- Пользователь -->
    <div class="accordion sidebar__user" id="accordion">
        <div class="border-bottom"></div>
        <a class="nav-link user__link" href="#" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false">
            <div class="sidebar_user_avatar d-flex align-items-center">
                <div class="position-relative">
                    <?php if (! empty($notifications['all'])): ?>
                        <div class="sidebar__notifications badge badge-danger badge-pill"><?= $notifications['all'] ?></div>
                    <?php endif ?>
                    <div class="user_photo border rounded-circle mr-2 overflow-hidden">
                        <?php if (! empty($user_avatar)): ?>
                            <img src="<?= $user_avatar ?>" class="img-fluid" alt=".">
                        <?php else: ?>
                            <img src="<?= $this->asset('icons/user.svg') ?>" class="img-fluid" alt=".">
                        <?php endif; ?>
                    </div>
                </div>
                <div>
                    <?= ($user->id ? $user->name : _t('Guest', 'system')) ?>
                </div>
            </div>
            <div>
                <svg class="icon icon-chevron-bottom">
                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chevron-bottom"/>
                </svg>
            </div>
        </a>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <ul class="nav nav__vertical pl-2 pt-0">
                <!-- Выпадающее меню для пользователей -->
                <?php if ($user->isValid()): ?>
                    <li>
                        <a href="/notifications/">
                            <svg class="icon text-info">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#messages"/>
                            </svg>
                            <span class="flex-grow-1 text-info"><?= _t('Notifications', 'system') ?></span>
                            <?php if (! empty($notifications['all'])): ?>
                                <span class="badge badge-danger badge-pill"><?= $notifications['all'] ?></span>
                                </span>
                            <?php endif ?>
                        </a>
                    </li>
                    <li>
                        <a href="/profile/?act=office">
                            <svg class="icon text-info">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
                            </svg>
                            <span class="flex-grow-1 text-info"><?= _t('Personal', 'system') ?></span>
                        </a>
                    </li>
                <?php else: ?>
                    <!-- Выпадающее меню для гостей -->
                    <li>
                        <a href="/registration/">
                            <svg class="icon text-info">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#users"/>
                            </svg>
                            <span class="flex-grow-1 text-info"><?= _t('Registration', 'system') ?></span>
                            <?php if (! empty($notifications['all'])): ?>
                                <span class="badge badge-danger badge-pill"><?= $notifications['all'] ?></span>
                                </span>
                            <?php endif ?>
                        </a>
                    </li>
                    <li>
                        <a href="/login/">
                            <svg class="icon text-info">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
                            </svg>
                            <span class="flex-grow-1 text-info"><?= _t('Login', 'system') ?></span>
                        </a>
                    </li>
                <?php endif ?>
            </ul>
        </div>
        <div class="border-bottom"></div>
    </div>


    <!-- Меню -->
    <div class="flex-grow-1">
        <ul class="nav nav__vertical" style="background-color: rgba(235,235,235,0.3)">
            <li>
                <a href="/news/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#book"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('News archive', 'system') ?></span>
                    <?php if ($news_counters['total'] > 0): ?>
                        <span class="badge badge-pill <?= ($news_counters['new'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                            <?= $tools->formatNumber($news_counters['total']) ?>
                            <?= ($news_counters['new'] > 0 ? '/ +' . $tools->formatNumber($news_counters['new']) : '') ?>
                        </span>
                    <?php endif ?>
                </a>
            </li>
            <?php if ($config->mod_forum || $user->rights >= 7): ?>
                <li>
                    <a href="/forum/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Forum', 'system') ?></span>
                        <span class="badge badge-pill <?= ($forum_counters['new_messages'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                            <?= $tools->formatNumber($forum_counters['topics']) ?> / <?= $tools->formatNumber($forum_counters['messages']) ?>
                            <?= ($forum_counters['new_messages'] > 0 ? '/ +' . $tools->formatNumber($forum_counters['new_messages']) : '') ?>
                        </span>
                    </a>
                </li>
            <?php endif ?>
            <?php if ($config->mod_guest || $user->rights >= 7): ?>
                <li>
                    <a href="/guestbook/ga">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#chat"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Guestbook', 'system') ?></span>
                        <?php if ($guestbook_counters['guestbook'] > 0): ?>
                            <span class="badge badge-pill badge-light">
                                <?= $tools->formatNumber($guestbook_counters['guestbook']) ?>
                            </span>
                        <?php endif ?>
                    </a>
                </li>
            <?php endif ?>
            <?php if ($config->mod_down || $user->rights >= 7): ?>
                <li>
                    <a href="/downloads/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#download"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Downloads', 'system') ?></span>
                        <?php if ($downloads_counters['total'] > 0): ?>
                            <span class="badge badge-pill <?= ($downloads_counters['new'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                                <?= $tools->formatNumber($downloads_counters['total']) ?>
                                <?= ($downloads_counters['new'] > 0 ? '/ +' . $tools->formatNumber($downloads_counters['new']) : '') ?>
                            </span>
                        <?php endif ?>
                    </a>
                </li>
            <?php endif ?>
            <?php if ($config->mod_lib || $user->rights >= 7): ?>
                <li>
                    <a href="/library/">
                        <svg class="icon">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#text"/>
                        </svg>
                        <span class="flex-grow-1"><?= _t('Library', 'system') ?></span>
                        <?php if ($library_counters['total'] > 0): ?>
                            <span class="badge badge-pill <?= ($library_counters['new'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                                <?= $tools->formatNumber($library_counters['total']) ?>
                                <?= ($library_counters['new'] > 0 ? '/ +' . $tools->formatNumber($library_counters['new']) : '') ?>
                            </span>
                        <?php endif ?>
                    </a>
                </li>
            <?php endif ?>
            <li>
                <a href="/community/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#users"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Users', 'system') ?></span>
                    <?php if ($users_counters['total'] > 0): ?>
                        <span class="badge badge-pill <?= ($users_counters['new'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                            <?= $tools->formatNumber($users_counters['total']) ?>
                            <?= ($users_counters['new'] > 0 ? '/ +' . $tools->formatNumber($users_counters['new']) : '') ?>
                        </span>
                    <?php endif ?>
                </a>
            </li>
            <li>
                <a href="/album/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#picasa"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Photo Albums', 'system') ?></span>
                    <?php if ($album_counters['photo'] > 0): ?>
                        <span class="badge badge-pill <?= ($album_counters['new'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                            <?= $tools->formatNumber($album_counters['album']) ?> / <?= $tools->formatNumber($album_counters['photo']) ?>
                            <?= ($album_counters['new'] > 0 ? '/ +' . $tools->formatNumber($album_counters['new']) : '') ?>
                        </span>
                    <?php endif ?>
                </a>
            </li>
            <li>
                <a href="/help/">
                    <svg class="icon">
                        <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#info"/>
                    </svg>
                    <span class="flex-grow-1"><?= _t('Information, FAQ', 'system') ?></span>
                </a>
            </li>
            <?php if ($user->rights >= 1): ?>
                <?php if ($user->rights >= 7): ?>
                    <li>
                        <div class="border-bottom mt-3 mb-3"></div>
                        <a href="/admin/">
                            <svg class="icon text-danger">
                                <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#settings"/>
                            </svg>
                            <span class="flex-grow-1 text-danger"><?= _t('Admin Panel', 'system') ?></span>
                        </a>
                    </li>
                <?php endif ?>
                <li>
                    <a href="/guestbook/ga?do=set">
                        <svg class="icon text-danger">
                            <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#forum"/>
                        </svg>
                        <span class="flex-grow-1 text-danger"><?= _t('Admin Chat', 'system') ?></span>
                        <?php if ($guestbook_counters['admin_club'] > 0): ?>
                            <span class="badge badge-pill badge-danger">
                                <?= $tools->formatNumber($guestbook_counters['admin_club']) ?>
                            </span>
                        <?php endif ?>
                    </a>
                </li>
            <?php endif ?>
        </ul>
        <div class="border-bottom"></div>
    </div>
    <div class="sidebar__footer">
        <div>
            <a href="/online/">
                <svg class="icon sidebar_online">
                    <use xlink:href="<?= $this->asset('icons/sprite.svg') ?>#user"/>
                </svg>
                <?= $container->get('counters')->online() ?>
            </a>
        </div>

        <?php if (count($config->lng_list) > 1): ?>
            <div class="mt-1">
                <button class="btn btn-link pl-0" data-url="/language/" data-toggle="modal" data-target=".ajax_modal">
                    <img src="<?= $this->asset('images/flags/' . strtolower($locale) . '.png') ?>" alt="<?= $locale ?>">
                    <?= $config['lng_list'][$locale] ?>
                </button>
            </div>
        <?php endif ?>
    </div>
</div>
