<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var string $title
 * @var string $page_title
 * @var \Johncms\Modules\Profile\Application\DTO\AccountDTO $account
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<h3><?= __('My Pages') ?></h3>

<div class="list-group with_counters">
    <div class="list-group-item">
        <a href="/profile/<?= $account->userId ?>" class="link"><?= __('Profile') ?></a>
    </div>
    <div class="list-group-item">
        <a href="/profile/<?= $account->userId ?>/statistics/" class="link"><?= __('Statistics') ?></a>
    </div>
    <div class="list-group-item">
        <a href="/album/user/<?= $account->userId ?>" class="link"><?= __('Photo Album') ?></a>
        <span class="counter badge text-bg-light rounded-pill"><?= $account->totalPhoto ?></span>
    </div>
    <div class="list-group-item">
        <a href="/profile/<?= $account->userId ?>/guestbook" class="link"><?= __('Guestbook') ?></a>
        <span class="counter badge text-bg-light rounded-pill"><?= $account->guestbookCount ?></span>
    </div>
</div>

<h3 class="mt-3"><?= __('My Mailbox') ?></h3>

<div class="list-group with_counters">
    <div class="list-group-item">
        <a href="/mail/incoming" class="link"><?= __('Received') ?></a>
        <span class="counter badge rounded-pill <?= ($account->newMessages > 0 ? 'bg-danger' : 'text-bg-light') ?>">
                    <?= $account->inbox ?>
                    <?= ($account->newMessages > 0 ? ' / +' . $account->newMessages : '') ?>
                </span>
    </div>
    <div class="list-group-item">
        <a href="/mail/outgoing" class="link"><?= __('Sent') ?></a>
        <span class="counter badge rounded-pill <?= ($account->unreadSent > 0 ? 'bg-danger' : 'text-bg-light') ?>">
                    <?= $account->outbox ?>
                    <?= ($account->unreadSent > 0 ? ' / +' . $account->unreadSent : '') ?>
                </span>
    </div>
    <div class="list-group-item">
        <a href="/mail/files" class="link"><?= __('Files') ?></a>
        <span class="counter badge rounded-pill text-bg-light"><?= $account->files ?></span>
    </div>
</div>

<h3 class="mt-3"><?= __('Contacts') ?></h3>

<div class="list-group with_counters">
    <div class="list-group-item">
        <a href="/mail/contacts" class="link"><?= __('Contacts') ?></a>
        <span class="counter badge rounded-pill text-bg-light"><?= $account->contacts ?></span>
    </div>
    <div class="list-group-item">
        <a href="/mail/blocklist" class="link"><?= __('Blocked') ?></a>
        <span class="counter badge rounded-pill text-bg-light"><?= $account->blockedContacts ?></span>
    </div>
</div>

<h3 class="mt-3"><?= __('Settings') ?></h3>

<div class="list-group">
    <a href="/profile/<?= $account->userId ?>/edit" class="list-group-item"><?= __('Edit Profile') ?></a>
    <a href="/profile/<?= $account->userId ?>/password" class="list-group-item"><?= __('Change Password') ?></a>
    <a href="/profile/settings" class="list-group-item"><?= __('System Settings') ?></a>
</div>
