<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $item
 */

?>

<div class="user-row card shadow border-0 mb-2">
    <div class="card-body">
        <div class="text-muted mb-2"><?= $item['display_date'] ?></div>
        <?= $item['text'] ?>
    </div>
    <div class="footer"></div>
</div>
