<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?php if (! empty($data['filters'])): ?>
    <div class="btn-group mb-3" role="group">
        <?php foreach ($data['filters'] as $filter): ?>
            <a href="<?= $filter['url'] ?>" class="btn btn-outline-secondary <?= ($filter['active'] ? 'active' : '') ?>"><?= $filter['name'] ?></a>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<?php if (empty($data['items'])): ?>
    <?= $this->fetch(
        'system::app/alert',
        [
            'alert_type' => 'alert-info',
            'alert'      => _t('The list is empty'),
        ]
    ) ?>
<?php endif; ?>

<?php foreach ($data['items'] as $item): ?>
    <div class="shadow post-item mb-2">
        <div class="post-header d-flex justify-content-between pb-1">
            <div class="d-flex align-items-center">
                <div class="badge <?= ($item['type'] > 0 ? 'badge-success' : 'badge-danger') ?> mr-2">
                    <?= ($item['type'] > 0 ? '+' : '-') ?><?= $item['points'] ?>
                </div>
                <?php if ($item['user_id'] > 0): ?>
                    <a href="/profile/?user=<?= $item['user_id'] ?>" class="user-login mr-2"><?= $item['name'] ?></a>
                <?php else: ?>
                    <b class="user-login mr-2"><?= $item['name'] ?></b>
                <?php endif; ?>
                <span class="post-date"><?= $item['display_date'] ?></span>
            </div>
        </div>
        <?php if (! empty($item['text'])): ?>
            <div class="post-body d-flex align-items-start pt-3 pb-3 border-top">
                <?= $item['text'] ?>
            </div>
        <?php endif; ?>
        <?php if (! empty($item['delete_url'])): ?>
            <div class="post-footer d-flex justify-content-between border-top pt-2">
                <div class="post-user-info d-flex overflow-hidden small align-items-center"></div>
                <div class="text-nowrap post-actions">
                    <span class="text-muted pr-2 flex-grow-1"></span>
                    <a href="<?= $item['delete_url'] ?>" class="btn btn-light btn-sm">Удалить</a>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<?php if (! empty($data['reset_url'])): ?>
    <div class="mt-4">
        <a href="<?= $data['reset_url'] ?>" class="btn btn-danger btn-sm"><?= _t('Reset Karma') ?></a>
    </div>
<?php endif; ?>

<?php if ($data['total'] > $user->config->kmess): ?>
    <div class="mt-4">
        <?= $data['pagination'] ?>
    </div>
<?php endif; ?>

<?php if ($data['total'] > 0): ?>
    <div><?= _t('Total:') ?> <?= $data['total'] ?></div>
<?php endif; ?>

<div>
    <a href="<?= $data['back_url'] ?>"><?= _t('Back') ?></a>
</div>
