<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $item
 */

?>

<div class="post-item border-bottom mb-2 pb-2">
    <div class="post-header d-flex justify-content-between pb-1">
        <div class="d-flex align-items-end">
            <a href="<?= $this->e($item['topic_url']) ?>" class="user-login me-2"><?= $this->e($item['topic_name']) ?></a>
            <span class="post-date"><?= $this->e($item['display_date']) ?></span>
        </div>
        <div class="post-actions"></div>
    </div>
    <div>
        <div>
            <div><?= $this->e($item['text']) ?></div>
            <div>
                <a href="<?= $this->e($item['message_url']) ?>"><?= __('To message') ?> &gt;&gt;</a>
            </div>
        </div>
        <div>
            <a href="<?= $this->e($item['category_url']) ?>"><?= $this->e($item['category_name']) ?></a> /
            <a href="<?= $this->e($item['section_url']) ?>"><?= $this->e($item['section_name']) ?></a>
        </div>
    </div>
</div>
