<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);

$counters = $data['counters'] ?? [];
?>
<div class="row">
    <div class="col-md-6">
        <h3><?= __('My Pages') ?></h3>

        <div class="list-group">
            <a href="./" class="list-group-item"><?= __('Profile') ?></a>
            <a href="?act=stat" class="list-group-item"><?= __('Statistics') ?></a>
            <a href="/album/?act=list" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Photo Album') ?>
                <span class="badge badge-light badge-pill"><?= $counters['total_photo'] ?></span>
            </a>
            <a href="?act=guestbook" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Guestbook') ?>
                <span class="badge badge-light badge-pill"><?= $user->comm_count ?></span>
            </a>
        </div>

        <h3 class="mt-3"><?= __('My Mailbox') ?></h3>

        <div class="list-group">
            <a href="/mail/?act=input" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Received') ?>
                <span class="badge badge-pill <?= ($counters['new_messages'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                    <?= $counters['inbox'] ?>
                    <?= ($counters['new_messages'] > 0 ? ' / +' . $counters['new_messages'] : '') ?>
                </span>
            </a>
            <a href="/mail/?act=output" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Sent') ?>
                <span class="badge badge-pill <?= ($counters['unread_sent'] > 0 ? 'badge-danger' : 'badge-light') ?>">
                    <?= $counters['outbox'] ?>
                    <?= ($counters['unread_sent'] > 0 ? ' / +' . $counters['unread_sent'] : '') ?>
                </span>
            </a>
            <a href="/mail/?act=files" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Files') ?>
                <span class="badge badge-pill badge-light"><?= $counters['files'] ?></span>
            </a>
        </div>

        <h3 class="mt-3"><?= __('Contacts') ?></h3>

        <div class="list-group">
            <a href="/mail/" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Contacts') ?>
                <span class="badge badge-pill badge-light"><?= $counters['contacts'] ?></span>
            </a>
            <a href="/mail/?act=ignor" class="list-group-item d-flex justify-content-between align-items-center">
                <?= __('Blocked') ?>
                <span class="badge badge-pill badge-light"><?= $counters['blocked_contacts'] ?></span>
            </a>
        </div>

        <h3 class="mt-3"><?= __('Settings') ?></h3>

        <div class="list-group">
            <a href="?act=edit" class="list-group-item"><?= __('Edit Profile') ?></a>
            <a href="?act=password" class="list-group-item"><?= __('Change Password') ?></a>
            <a href="?act=settings" class="list-group-item"><?= __('System Settings') ?></a>
        </div>
    </div>
</div>
