<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $data
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $title,
    ]
);

?>

<form action="<?= $data['form_action'] ?>" method="post">
    <?php if ($data['show_old_password_field']): ?>
        <div class="form-group">
            <label for="oldpass"><?= __('Enter old password') ?></label>
            <input type="password"
                   class="form-control"
                   name="oldpass"
                   id="oldpass"
                   value=""
                   placeholder="<?= __('Enter old password') ?>"
            >
        </div>
    <?php endif; ?>

    <div class="form-group">
        <label for="newpass"><?= __('Enter new password') ?></label>
        <input type="password"
               class="form-control"
               name="newpass"
               id="newpass"
               value=""
               placeholder="<?= __('Enter new password') ?>"
        >
    </div>
    <div class="form-group">
        <label for="newconf"><?= __('Repeat password') ?></label>
        <input type="password"
               class="form-control"
               name="newconf"
               id="newconf"
               value=""
               placeholder="<?= __('Repeat password') ?>"
        >
    </div>

    <input type="submit" name="submit" value="<?= __('Save') ?>" class="btn btn-primary"/>
    <a href="<?= $data['back_url'] ?>" class="btn btn-secondary"><?= __('Cancel') ?></a>
</form>
