<?php $this->layout('system::layout/default', [
    'title'       => _t('Restore password', 'system'),
    'page_title'  => _t('Restore password', 'system'),
    'breadcrumbs' => $breadcrumbs,
]) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-7">
        <div class="card shadow border-0 border-radius-12">
            <form action="skl.php?act=sent" method="post">
                <div class="card-body">
                    <h4 class="card-title"><?= _t('Restore password', 'system') ?></h4>
                    <div class="form-group">
                        <label for="nick"><?= _t('Username') ?></label>
                        <input type="text"
                               class="form-control"
                               name="nick"
                               id="nick"
                               required
                               placeholder="<?= _t('Username') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="email"><?= _t('Your E-mail') ?></label>
                        <input type="email"
                               class="form-control"
                               name="email"
                               id="email"
                               required
                               placeholder="<?= _t('Your E-mail') ?>"
                        >
                    </div>
                    <img alt="<?= _t('Verification code') ?>" src="<?= $captcha ?>">
                    <div class="form-group">
                        <label for="code"><?= _t('Enter verification code', 'system') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="5"
                               name="code"
                               id="code"
                               required
                               placeholder="<?= _t('Verification code') ?>"
                        >
                    </div>
                    <input type="submit" name="login" value="<?= _t('Continue', 'system') ?>" class="btn btn-primary"/>

                    <div class="alert alert-info mt-3">
                        <?= _t('Password will be send to E-mail address specified in your profile.<br />WARNING !! If E-mail address has not been specified in your profile, you will not be able to recover your password.') ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
