<?php

/**
 * @var string $form_action
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => __('Restore password'),
        'page_title' => __('Restore password'),
    ]
) ?>

<form action="<?= $this->e($form_action) ?>" method="post">
    <div class="alert alert-info">
        <?= __('A new password will be generated and sent to the E-mail address specified in your profile.') ?>
    </div>
    <input type="submit" value="<?= __('Continue') ?>" class="btn btn-primary"/>
</form>
