<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var string $title
 * @var string $page_title
 * @var \Johncms\Users\User $profile_user
 * @var \Johncms\Users\User $user
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<h3><?= __('Statistic') ?></h3>

<ul>
    <?php if ($user->rights >= 7): ?>
        <li>
            <?php if (! $profile_user['preg'] && empty($profile_user['regadm'])): ?>
                <?= __('Pending confirmation') ?>
            <?php elseif (! empty($profile_user['preg']) && ! empty($profile_user['regadm'])): ?>
                <?= __('Registration confirmed') ?>: <?= $this->e($profile_user['regadm']) ?>
            <?php else: ?>
                <?= __('Free registration') ?>
            <?php endif; ?>
        </li>
    <?php endif; ?>
    <li>
        <?= __('Registered') ?>: <?= date('d.m.Y', (int) $profile_user['datereg']) ?>
    </li>
    <?php if (! empty($profile_user['last_visit'])): ?>
        <li>
            <?= __('Last visit') ?>: <?= $this->e($profile_user['last_visit']) ?>
        </li>
    <?php endif; ?>
</ul>

<h3><?= __('Activity') ?></h3>
<ul>
    <li><span class="gray"><?= __('Forum') ?>:</span> <a href="/profile/<?= $profile_user['id'] ?>/activity"><?= $profile_user['postforum'] ?></a></li>
    <li><span class="gray"><?= __('Guestbook') ?>:</span> <a href="/profile/<?= $profile_user['id'] ?>/activity/comments"><?= $profile_user['postguest'] ?></a></li>
    <li><span class="gray"><?= __('Comments') ?>:</span> <?= $profile_user['komm'] ?></li>
</ul>

<div class="mt-2">
    <a href="/profile/<?= $profile_user['id'] ?>"><?= __('Back') ?></a>
</div>
