<?php $this->layout('system::layout/default') ?>

<?php if (! empty($data['errors'])): ?>
    <div>
        <?= $this->fetch(
            'system::app/alert',
            [
                'alert_type' => 'alert-danger',
                'alert'      => $data['errors'],
            ]
        ) ?>
    </div>
<?php endif ?>

<h4 class="card-title"><?= $page_title ?></h4>
<form action="<?= $data['action_url'] ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="active" value="0">
        <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" name="active" value="1" id="active" <?= $data['fields']['active'] ? 'checked' : '' ?>>
            <label class="custom-control-label" for="active"><?= __('Active') ?></label>
        </div>
    </div>
    <div class="form-group">
        <label for="name"><?= __('Article name') ?></label>
        <input type="text"
               class="form-control"
               maxlength="255"
               name="name"
               id="name"
               required
               value="<?= $data['fields']['name'] ?>"
               placeholder="<?= __('Article name') ?>"
        >
    </div>
    <div class="form-group">
        <label for="page_title"><?= __('Page title') ?></label>
        <input type="text"
               class="form-control"
               maxlength="255"
               name="page_title"
               id="page_title"
               required
               value="<?= $data['fields']['page_title'] ?>"
               placeholder="<?= __('Page title') ?>"
        >
    </div>
    <div class="form-group">
        <label for="date_active_from"><?= __('Active from') ?></label>
        <input type="text"
               class="form-control flatpickr_time"
               name="active_from"
               id="active_from"
               required
               value="<?= $data['fields']['active_from'] ?>"
               placeholder="<?= __('Active from') ?>"
        >
    </div>
    <div class="form-group">
        <label for="date_active_to"><?= __('Active to') ?></label>
        <input type="text"
               class="form-control flatpickr_time"
               name="active_to"
               id="active_to"
               required
               value="<?= $data['fields']['active_to'] ?>"
               placeholder="<?= __('Active to') ?>"
        >
    </div>
    <div class="form-group">
        <label for="code"><?= __('Article code') ?></label>
        <input type="text"
               class="form-control"
               maxlength="255"
               name="code"
               id="code"
               value="<?= $data['fields']['code'] ?>"
               placeholder="<?= __('Article code') ?>"
        >
        <div class="small text-muted"><?= __('Leave it empty for automatic generation') ?></div>
    </div>
    <div class="form-group">
        <label for="keywords"><?= __('Keywords') ?></label>
        <input type="text"
               class="form-control"
               maxlength="255"
               name="keywords"
               id="keywords"
               value="<?= $data['fields']['keywords'] ?>"
               placeholder="<?= __('Keywords') ?>"
        >
    </div>
    <div class="form-group">
        <label for="description"><?= __('Description') ?></label>
        <input type="text"
               class="form-control"
               maxlength="255"
               name="description"
               id="description"
               value="<?= $data['fields']['description'] ?>"
               placeholder="<?= __('Description') ?>"
        >
    </div>
    <div class="form-group">
        <label for="tags"><?= __('Tags') ?></label>
        <input type="text"
               class="form-control"
               maxlength="255"
               name="tags"
               id="tags"
               value="<?= $data['fields']['tags'] ?>"
               placeholder="<?= __('Tags') ?>"
        >
        <div class="small text-muted"><?= __('Enter words or phrases separated by commas') ?></div>
    </div>
    <?= $this->fetch(
        'news::admin/ckeditor',
        [
            'label'        => __('Preview text'),
            'errors'       => implode(', ', $data['errors']['preview_text'] ?? []),
            'value'        => $this->e($data['fields']['preview_text']),
            'id'           => 'preview_text',
            'name'         => 'preview_text',
            'load_scripts' => true,
        ]
    ) ?>

    <?= $this->fetch(
        'news::admin/ckeditor',
        [
            'label'  => __('Text'),
            'errors' => implode(', ', $data['errors']['text'] ?? []),
            'value'  => $this->e($data['fields']['text']),
            'id'     => 'text',
            'name'   => 'text',
        ]
    ) ?>
    <div>
        <button type="submit" class="btn btn-primary"><?= __('Save') ?></button>
        <a href="<?= $data['back_url'] ?>" class="btn btn-outline-primary ml-2"><?= __('Back') ?></a>
    </div>
</form>
