<?php
/**
 * @var $section
 * @var int $sectionLevel
 * @var string $name
 * @var int $currentSection
 */

?>
<div class="form-check">
    <input class="form-check-input"
           type="radio"
           name="<?= $name ?>"
           id="<?= $name . $section['id'] ?>"
           value="<?= $section['id'] ?>"
        <?= ($currentSection === $section['id'] ? 'checked' : '') ?>
        <?= ($section['section_type'] !== 1 ? 'disabled' : '') ?>
    >
    <label class="form-check-label" for="<?= $name . $section['id'] ?>"><?= $section['name'] ?></label>
</div>
<?php if (! empty($section['children'])): ?>
    <div class="ps-4 pb-2 border-start">
        <?php foreach ($section['children'] as $section): ?>
            <?= $this->fetch('forum::parts/radio_input', [
                'section'        => $section,
                'sectionLevel'   => ($sectionLevel + 1),
                'name'           => $name,
                'currentSection' => $currentSection,
            ]) ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>



