<?php

/**
 * @var $csrf_token
 * @var $actionUrl
 * @var $canHide
 * @var $backUrl
 * @var $countMessages
 */

$this->layout('system::layout/default');
?>

<div class="alert alert-danger">
    <?php if ($countMessages === 1): ?>
        <div class="fw-bold">
            <?= __('WARNING!<br>This is last post of topic. By deleting this post topic will be deleted (or hidden) too') ?>
        </div>
    <?php endif; ?>
    <form action="<?= $actionUrl ?>" method="post">
        <div class="pb-2">
            <?= __('Do you really want to delete?') ?>
        </div>
        <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
        <button type="submit" name="type" value="delete" class="me-2 btn btn-danger btn-sm"><?= __('Delete') ?></button>
        <?php if ($canHide): ?>
            <button type="submit" name="type" value="hide" class="me-2 btn btn-primary btn-sm"><?= __('Hide') ?></button>
        <?php endif; ?>
    </form>
</div>
<div class="mt-2">
    <a href="<?= $backUrl ?>"><?= __('Cancel') ?></a>
</div>
<div class="mt-2 text-muted small">
    <?= __('After deleting, one point will be subtracted from the counter of forum posts') ?>
</div>
