<?php

/**
 * @var $back_url
 * @var $data
 */

$this->layout('system::layout/default');
?>

<form name="new_topic" action="<?= $data['storeUrl'] ?>" method="post">
    <?php if (! empty($data['errors'])): ?>
        <?= $this->fetch('system::app/alert', ['alert_type' => 'alert-danger', 'alert' => $data['errors']]) ?>
    <?php endif ?>
    <?= $this->fetch(
        'system::forms/simple_form',
        [
            'fields' => $data['formFields'],
            'errors' => $data['validationErrors'],
        ]
    ); ?>
    <button type="submit" class="btn btn-primary"><?= __('Write') ?></button>
    <div class="mt-3">
        <a href="<?= $back_url ?>"><?= __('Back') ?></a>
    </div>
</form>

<div class="mt-2">
    <a href="/help/?act=smileys"><?= __('Smilies') ?></a>
</div>
