<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $back_url
 * @var $msg
 * @var $form_action
 * @var $is_new_message
 * @var $add_file
 * @var $topicName
 * @var $bbcode
 * @var $csrf_token
 */

$this->layout('system::layout/default');
?>

<form name="message_form" action="<?= $form_action ?>" method="post">
    <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
    <div class="h4"><?= __('Topic') ?>: <?= $topicName ?></div>
    <div class="form-group">
        <label for="msg"><?= __('Message') ?></label>
        <div><?= $bbcode ?></div>
        <textarea name="msg" id="msg" required class="form-control"><?= $msg ?></textarea>
    </div>
    <div class="form-check mt-2 mb-3">
        <input type="checkbox" class="form-check-input" name="addfiles" value="1" id="addfiles" <?= $add_file ? 'checked="checked"' : '' ?>>
        <label class="form-check-label" for="addfiles"><?= __('Add File') ?></label>
    </div>
    <div>
        <button type="submit" name="submit" value="1" class="btn btn-primary"><?= __('Write') ?></button>
    </div>
    <div class="mt-3">
        <a href="/help/?act=smileys" class="pe-2"><?= __('Smilies') ?></a> <a href="<?= $back_url ?>"><?= __('Back') ?></a>
    </div>
</form>
