<?php $this->layout(
    'system::layout/default',
    [
        'title'      => __('Login'),
        'page_title' => __('Login'),
    ]
) ?>

<form method="post">
    <img alt="<?= __('Verification code') ?>" src="<?= $captcha ?>">
    <div class="form-group">
        <label for="code"><?= __('Enter verification code') ?></label>
        <input type="text"
               class="form-control"
               maxlength="5"
               name="code"
               id="code"
               required
               placeholder="<?= __('Verification code') ?>"
        >
    </div>
    <input type="hidden" name="n" value="<?= $this->e($user_login) ?>"/>
    <input type="hidden" name="p" value="<?= $this->e($user_pass) ?>"/>
    <input type="submit" name="login" value="<?= __('Continue') ?>" class="btn btn-primary"/>
</form>
