<?php $this->layout('system::layout/default', [
    'title'      => __('Login'),
    'page_title' => __('Login'),
]) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-5">
        <div class="card shadow border-0 border-radius-12">
            <form method="post">
                <div class="card-body">
                    <img alt="<?= __('Verification code') ?>" src="<?= $captcha ?>">
                    <div class="form-group">
                        <label for="code"><?= __('Enter verification code') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="5"
                               name="code"
                               id="code"
                               required
                               placeholder="<?= __('Verification code') ?>"
                        >
                    </div>
                    <?php if ($id): ?>
                        <input type="hidden" name="id" value="<?= $id ?>"/>
                    <?php endif ?>
                    <input type="hidden" name="n" value="<?= $user_login ?>"/>
                    <input type="hidden" name="p" value="<?= $user_pass ?>"/>
                    <input type="hidden" name="mem" value="<?= $remember ?>"/>
                    <input type="submit" name="login" value="<?= __('Continue') ?>" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    </div>
</div>
