<?php $this->layout(
    'system::layout/default',
    [
        'title'      => d__('system', 'Login'),
        'page_title' => d__('system', 'Login'),
    ]
) ?>
<div class="row">
    <div class="m-sm-auto m-md-auto m-lg-0 col-sm-8 col-md-8 col-lg-7 col-xl-5">
        <div class="card shadow border-0 border-radius-12">
            <form method="post">
                <div class="card-body">
                    <h4 class="card-title"><?= d__('system', 'Authorization') ?></h4>
                    <?php if (! empty($error)): ?>
                        <?= $this->fetch('system::app/alert', ['alert_type' => 'alert-danger', 'alert' => $error]) ?>
                    <?php endif ?>
                    <div class="form-group">
                        <label for="login"><?= d__('system', 'Username') ?></label>
                        <input type="text"
                               class="form-control"
                               maxlength="20"
                               name="n"
                               id="login"
                               required
                               value="<?= $this->e($user_login) ?>"
                               placeholder="<?= d__('system', 'Username') ?>"
                        >
                    </div>
                    <div class="form-group">
                        <label for="password"><?= d__('system', 'Password') ?></label>
                        <input
                            type="password"
                            class="form-control"
                            name="p"
                            maxlength="20"
                            id="password"
                            required
                            placeholder="<?= d__('system', 'Password') ?>"
                        >
                    </div>
                    <button type="submit" name="login" value="1" class="btn btn-fill btn-primary"><?= d__('system', 'Login') ?></button>
                    <a href="/profile/skl.php?continue" class="btn btn-link"><?= d__('system', 'Forgot password?') ?></a>
                    <div class="mt-3">
                        <a href="/registration" class="mr-2"><?= d__('system', 'Registration') ?></a>
                    </div>
                </div>
            </form>
        </div> <!-- end card -->
    </div>
</div>
