<?php $this->layout('system::layout/default', [
    'title'      => __('Logout'),
    'page_title' => __('Logout'),
]) ?>
<div class="card shadow border-0 border-radius-12">
    <div class="card-body">
        <p class="h3 pb-2"><?= __('Are you sure you want to leave the site?') ?></p>
        <form method="post">
            <input type="submit" name="logout" value="<?= __('Logout') ?>" class="btn btn-danger"/>
            <a class="btn btn-link" href="<?= $referer ?>"><?= __('Cancel') ?></a>
        </form>
    </div>
</div>
