<?php $this->layout('system::layout/default', [
    'title'      => d__('system', 'Logout'),
    'page_title' => d__('system', 'Logout'),
]) ?>
<div class="card shadow border-0 border-radius-12">
    <div class="card-body">
        <p class="h3 pb-2"><?= d__('system', 'Are you sure you want to leave the site?') ?></p>
        <form method="post">
            <input type="submit" name="logout" value="<?= d__('system', 'Logout') ?>" class="btn btn-danger"/>
            <a class="btn btn-link" href="<?= $referer ?>"><?= d__('system', 'Cancel') ?></a>
        </form>
    </div>
</div>
