<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var array $files
 * @var int $total_files
 * @var string $pagination
 * @var array $urls
 * @var \Johncms\Users\User $user
 */

$this->layout('system::layout/default');
?>

<?php if (empty($files)): ?>
    <div class="alert alert-info"><?= __('List is empty') ?></div>
<?php endif; ?>

<?php foreach ($files as $file): ?>
    <?= $this->fetch('downloads::file_row', ['file' => $file]) ?>
<?php endforeach; ?>

<?php if ($total_files): ?>
    <div>
        <div><?= __('Total') ?>: <?= $total_files ?></div>
        <?php if ($total_files > $user->config->kmess): ?>
            <div class="mt-1"><?= $pagination ?></div>
        <?php endif ?>
    </div>
<?php endif; ?>

<div class="mt-2">
    <a href="<?= $urls['downloads'] ?>"><?= __('Downloads') ?></a>
</div>
