<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $urls
 * @var $action_url
 * @var $extensions
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<form name="file_upload_form" action="<?= $action_url ?>" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="new_file"><?= __('Save as') ?></label>
        <input type="text" class="form-control" id="new_file" placeholder="Galaxy on Fire 2 - Supernova"
               name="new_file" value="" maxlength="100" required>
        <div class="text-muted small"><?= __('max. 100 characters') ?></div>
    </div>

    <div class="form-group">
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="screen" name="screen" aria-describedby="screen">
            <label class="custom-file-label" for="screen"><?= __('Choose screenshot') ?></label>
        </div>
    </div>

    <div class="form-group">
        <label for="desc"><?= __('Description') ?></label>
        <div><?= $bbcode ?></div>
        <textarea placeholder="Describe yourself here..." id="desc" class="form-control" maxlength="65000" name="opis" cols="24" rows="4"></textarea>
    </div>

    <div class="form-group">
    <label for="price"><?= __('Price') ?></label>
        <input type="number" class="form-control" id="price" placeholder="0"
               name="price" value="" maxlength="3" required>
        <div class="text-muted small"><?= __('max. 10 characters') ?></div>
    </div>
	
	<div class="form-group">
        <label for="vendor"><?= __('Vendor') ?></label>
        <input type="text" class="form-control" id="vendor" placeholder="Fishlabs"
               name="vendor" value="" maxlength="30" required>
        <div class="text-muted small"><?= __('max. 30 characters') ?></div>
    </div>
	
	<div class="form-group">
        <label for="tag"><?= __('Tags') ?></label>
        <input type="text" class="form-control" id="tag" placeholder="java, RPG, simulator, fly,"
               name="tag" value="" maxlength="90" required>
        <div class="text-muted small"><?= __('max. 90 characters') ?></div>
    </div>

    <div class="form-group">
        <label for="text"><?= __('File Name') ?></label>
        <input type="text" class="form-control" id="text" placeholder="GalaxyOnFire2-Supernova-240x320-S60v5-Rus-v2.7"
               name="text" value="" maxlength="200" required>
        <div class="text-muted small"><?= __('max. 200 characters') ?></div>
    </div>

    <div class="form-group">
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="fail" name="fail" aria-describedby="file_label" required>
            <label class="custom-file-label" for="fail"><?= __('Choose file') ?></label>
        </div>
        <div class="text-muted mb-3 small">
            <?= __('Max. Size') ?>: <?= $config['flsz'] ?> kb.
        </div>
    </div>

    <div class="form-group">
        <label for="name_link"><?= __('Link to download file') ?></label>
        <textarea placeholder="240x320: S60v2-S60v5 Rus v.2.7 MOD Money by Motya" id="name_link" class="form-control" maxlength="65000" name="name_link" cols="24" rows="4"></textarea>
    </div>

    <div class="form-group">
        <label for="mirrors"><?= __('Mirrors') ?></label>
        <textarea placeholder="https://sefan.ru/loads/?l=games/240x320/sis/Galaxy_on_Fire_2.zip, https://namobilu.com/java-game/34-galaxy-on-fire-2-valkyrie" id="mirrors" class="form-control" maxlength="65000" name="mirrors" cols="24" rows="4"></textarea>
    </div>

    <div class="alert alert-warning mt-3">
        <?= __('Allowed extensions') ?>: <?= $extensions ?>
    </div>

    <div>
        <button type="submit" name="submit" value="1" class="btn btn-primary"><?= __('Save') ?></button>
        <a href="?id=<?= $id ?>" class="btn btn-secondary"><?= __('Cancel') ?></a>
    </div>
</form>
