<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $categories
 * @var $urls
 * @var $pagination
 * @var $can_upload
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?php if (! $config->mod_down): ?>
    <div class="alert alert-danger border-0 shadow">
        <?= _t('Downloads are closed') ?>
    </div>
<?php endif; ?>

<?php foreach ($categories as $category): ?>
    <div class="shadow border-radius-12 forum-section post-item mb-2">
        <div class="section-header d-flex justify-content-between <?= (empty($category['desc']) ? 'border-0 pb-0' : '') ?>">
            <div class="d-flex align-items-center">
                <a href="<?= $category['url'] ?>" class="text-dark-brown"><?= $category['rus_name'] ?></a>
                <span class="badge badge-pill badge-light border ml-3"><?= $category['total'] ?></span>
            </div>
            <?php if ($category['has_edit']): ?>
                <div class="actions">
                    <a href="<?= $category['up_url'] ?>" class="btn btn-sm btn-secondary"><?= _t('Up') ?></a>
                    <a href="<?= $category['down_url'] ?>" class="btn btn-sm btn-secondary"><?= _t('Down') ?></a>
                    <a href="<?= $category['edit_url'] ?>" class="btn btn-sm btn-secondary"><?= _t('Edit') ?></a>
                    <a href="<?= $category['delete_url'] ?>" class="btn btn-sm btn-secondary"><?= _t('Delete') ?></a>
                </div>
            <?php endif; ?>
        </div>
        <?php if (! empty($category['desc']) || ! empty($category['field'])): ?>
            <div class="small pt-2 text-muted">
                <?php if (! empty($category['desc'])): ?>
                    <div><?= $category['desc'] ?></div>
                <?php endif; ?>
                <?php if (! empty($category['text'])): ?>
                    <div><?= _t('Allowed extensions') ?>: <?= $category['text'] ?></div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<?php if (! empty($urls['sort_action'])): ?>
    <form class="form-inline" method="post" action="<?= $urls['sort_action'] ?>">
        <label class="my-1 mr-2" for="sort_down"><?= _t('Sorting') ?></label>
        <select class="custom-select my-1 mr-sm-2" name="sort_down" id="sort_down">
            <option value="0" <?= ! $_SESSION['sort_down'] ? ' selected="selected"' : '' ?>><?= _t('by time') ?></option>
            <option value="1" <?= $_SESSION['sort_down'] ? ' selected="selected"' : '' ?>><?= _t('by name') ?></option>
        </select>
        <select class="custom-select my-1 mr-sm-2" name="sort_down2" id="sort_down2">
            <option value="0" <?= ! $_SESSION['sort_down2'] ? ' selected="selected"' : '' ?>><?= _t('descending') ?></option>
            <option value="1" <?= $_SESSION['sort_down2'] ? ' selected="selected"' : '' ?>><?= _t('descending') ?></option>
        </select>
        <button type="submit" class="btn btn-primary my-1"><?= _t('Sort') ?></button>
    </form>
<?php endif; ?>

<?php foreach ($files as $file): ?>
    <div class="shadow border-radius-12 forum-section post-item mb-2">
        <div class="section-header d-flex justify-content-between <?= (empty($file['preview_text']) ? 'border-0 pb-0' : '') ?>">
            <div class="d-flex align-items-center">
                <span class="mr-2"><img src="<?= $file['icon'] ?>" alt="icon"></span>
                <a href="<?= $file['detail_url'] ?>" class="text-dark-brown"><?= $file['rus_name'] ?></a>
                <span class="badge badge-pill badge-light border ml-3"><?= $file['field'] ?></span>
            </div>
        </div>
        <?php if (! empty($file['preview_text'])): ?>
            <div class="small pt-2 text-muted">
                <?php if (! empty($file['preview_text'])): ?>
                    <div><?= $file['preview_text'] ?></div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
<?php endforeach; ?>

<?php if ($total_files): ?>
    <div>
        <div><?= _t('Total') ?>: <?= $total_files ?></div>
        <!-- Page switching -->
        <?php if ($total_files > $user->config->kmess): ?>
            <div class="mt-1"><?= $pagination ?></div>
        <?php endif ?>
    </div>
<?php endif; ?>

<?php if ($user->rights == 4 || $user->rights >= 6): ?>
    <!--TODO: Переделать внешний вид -->
    <?php if (! empty($id)): ?>
        <div><a href="?act=down_file&amp;id=<?= $id ?>"><?= _t('Upload File') ?></a></div>
        <div><a href="?act=import&amp;id=<?= $id ?>"><?= _t('Import File') ?></a></div>

        <div><a href="?act=folder_edit&amp;id=<?= $id ?>"><?= _t('Change Folder') ?></a></div>
        <div><a href="?act=folder_delete&amp;id=<?= $id ?>"><?= _t('Delete Folder') ?></a></div>
    <?php endif; ?>

    <div><a href="?act=folder_add&amp;id=<?= $id ?>"><?= _t('Create Folder') ?></a></div>

    <div><a href="?act=scan_dir&amp;id=<?= $id ?>"><?= _t('Update Files') ?></a></div>
    <div><a href="?act=scan_dir&amp;do=clean&amp;id=<?= $id ?>"><?= _t('Remove missing files') ?></a></div>
    <div><a href="?act=recount&amp;id=<?= $id ?>"><?= _t('Update counters') ?></a></div>

<?php elseif ($can_upload): ?>
    <div><a href="?act=down_file&amp;id=<?= $id ?>"><?= _t('Upload File') ?></a></div>
<?php endif; ?>

<?php if ($id): ?>
    <a href="<?= $urls['downloads'] ?>"><?= _t('Downloads') ?></a>
<?php else: ?>
    <?php if ($user->rights >= 7 || isset($config->mod_down_comm) && $config->mod_down_comm): ?>
        <a href="?act=review_comments"><?= _t('Review comments') ?></a><br>
    <?php endif; ?>
    <a href="?act=bookmark"><?= _t('Favorites') ?></a>
<?php endif; ?>
