<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $files
 * @var $total
 * @var $urls
 * @var $pagination
 * @var $show_empty_info
 * @var $search_query
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?php if (! $config['mod_down']): ?>
    <div class="alert alert-danger border-0 shadow">
        <?= __('Downloads are closed') ?>
    </div>
<?php endif; ?>
    <div class="mb-3 mt-n1">
	
        <?php if (! empty($urls['new'])): ?>
            <a href="<?= $urls['new'] ?>" class="btn btn-outline-primary btn-sm mr-1 mt-1">
                <?= __('New Files') ?> <span class="badge badge-secondary badge-pill ml-1"><?= $total_new ?></span>
            </a>
        <?php endif; ?>
	<?php if (!empty($catid)): ?>
        <a href="?act=search&amp;catid=<?= $catid ?>" class="btn btn-outline-primary btn-sm mr-1 mt-1"><?= __('Search') ?></a>
        <a href="?act=top_files&amp;id=1&amp;catid=<?= $catid ?>" class="btn btn-outline-primary btn-sm mr-1 mt-1"><?= __('Most Downloaded') ?></a>
        <a href="?act=top_files&amp;id=0&amp;catid=<?= $catid ?>" class="btn btn-outline-primary btn-sm mr-1 mt-1"><?= __('Popular Files') ?></a>
	<?php else: ?>
		<a href="?act=search" class="btn btn-outline-primary btn-sm mr-1 mt-1"><?= __('Search') ?></a>
        <a href="?act=top_files&amp;id=1" class="btn btn-outline-primary btn-sm mr-1 mt-1"><?= __('Most Downloaded') ?></a>
        <a href="?act=top_files&amp;id=0" class="btn btn-outline-primary btn-sm mr-1 mt-1"><?= __('Popular Files') ?></a>
	<?php endif; ?>
    </div>
	<?php if (!empty($catid)): ?>
    <form action="?act=search&catid=<?= $catid ?>" method="post" class="mb-3">
	<?php else: ?>
	<form action="?act=search" method="post" class="mb-3">
	<?php endif; ?>

    <div class="form-group">
        <label for="search_query"><?= __('Search query') ?> 
		<?php if (!empty($catid)): ?>
		-> <a href="<?= $urls['downloads'] ?>?id=<?= $catid ?>"><b><?= $catname ?></b></a>
		<?php endif; ?>
		</label>
        <input type="text" class="form-control" id="search_query" placeholder="<?= __('Search query') ?>"
               name="search" value="<?= $search_query ?>" maxlength="64" minlength="2" required>
    </div>
    <div class="form-group">
        <div class="custom-control custom-checkbox mb-3">
            <input type="checkbox" class="custom-control-input" name="id" value="1" id="search_t" <?= ($id ? 'checked="checked"' : '') ?>>
            <label class="custom-control-label" for="search_t"><?= __('Search in description') ?></label>
        </div>
    </div>
    <button type="submit" name="submit" value="1" class="btn btn-primary"><?= __('Search') ?></button>
</form>

<?php if (empty($files) && $show_empty_info): ?>
    <div class="alert alert-info"><?= __('List is empty') ?></div>
<?php endif; ?>

<?php foreach ($files as $file): ?>
    <?= $this->fetch('downloads::file_row', ['file' => $file]) ?>
<?php endforeach; ?>

<?php if ($total): ?>
    <div>
        <div><?= __('Total') ?>: <?= $total ?></div>
        <!-- Page switching -->
        <?php if ($total > $user->config->kmess): ?>
            <div class="mt-1"><?= $pagination ?></div>
        <?php endif ?>
    </div>
<?php endif; ?>

<?php if (empty($files)): ?>
    <div class="alert alert-info">
        <?= __('Search by file Name and is case insensitive.<br>The length of the request: 2 min. 64 max.') ?>
    </div>
<?php endif; ?>

<div class="mt-2">
    <div class="pb-2">
        <a href="?act=search"><?= __('New Search') ?></a>
    </div>

    <a href="<?= $urls['downloads'] ?>"><?= __('Downloads') ?></a>
</div>
