<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var $title
 * @var $page_title
 * @var $files
 * @var $buttons
 * @var $urls
 */

$this->layout(
    'system::layout/default',
    [
        'title'      => $title,
        'page_title' => $page_title,
    ]
);
?>

<?php if (! $config->mod_down): ?>
    <div class="alert alert-danger border-0 shadow">
        <?= _t('Downloads are closed') ?>
    </div>
<?php endif; ?>

<div class="mb-3">
    <?php foreach ($buttons as $button): ?>
        <a href="<?= $button['url'] ?>" class="btn btn-outline-primary mr-1 <?= $button['active'] ? 'active' : '' ?>"><?= $button['name'] ?></a>
    <?php endforeach; ?>
</div>

<?php foreach ($files as $file): ?>
    <?php $this->insert('downloads::file_row', ['file' => $file]); ?>
<?php endforeach; ?>

<div class="mt-3">
    <a href="<?= $urls['downloads'] ?>"><?= _t('Downloads') ?></a>
</div>
