<?php

/**
 * This file is part of JohnCMS Content Management System.
 *
 * @copyright JohnCMS Community
 * @license   https://opensource.org/licenses/GPL-3.0 GPL-3.0
 * @link      https://johncms.com JohnCMS Project
 */

/**
 * @var array $users
 * @var string $pagination
 * @var int $total
 * @var array $urls
 * @var \Johncms\Users\User $user
 */

$this->layout('system::layout/default');
?>

<?php if (empty($users)): ?>
    <div class="alert alert-info"><?= __('List is empty') ?></div>
<?php endif; ?>

<?php foreach ($users as $list_user): ?>
    <?= $this->fetch('downloads::user_row', ['item' => $list_user]) ?>
<?php endforeach; ?>

<?php if ($total > $user->config->kmess): ?>
    <div class="mt-2"><?= $pagination ?></div>
<?php endif; ?>

<div class="mt-3">
    <a href="<?= $urls['downloads'] ?>"><?= __('Downloads') ?></a>
</div>
