name: Node CI
on:
  push:
    paths:
      - '**.js'
      - '**.css'
      - '**.scss'
      - '**.json'
      - '**.vue'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: npm install, build
        run: |
          npm ci
          npm run build
        env:
          CI: true
